import fs from 'node:fs/promises';
import path from 'node:path';

const repoRoot = path.resolve(import.meta.dirname, '..', '..');
const root = path.join(repoRoot, 'AI 视频自主生产', 'CEF3 浏览器模块合集');
const GENERATED_AT = '2026-09-21';

const CEF3_VERSION = '3.0.0-alpha.3';
const BASIC = 'lingbuilder.win32.basic';
/** 非 CEF3 子模块的模块钉版表；缺省回落 CEF3_VERSION。 */
const MODULE_PINS: Record<string, string> = {
  'lingbuilder.http.server': '2.1.0',
  'lingbuilder.threading': '2.1.0'
};

type Control = Record<string, any>;

const page = (title: string, body: string, accent = '#2563EB') =>
  `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${title}</title>`
  + `<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:40px}`
  + `main{max-width:760px;margin:auto;background:#fff;border-left:6px solid ${accent};padding:24px 28px;border-radius:8px}`
  + `h1{margin:0 0 12px;font-size:24px}p{line-height:1.8;margin:6px 0}code{background:#e2e8f0;padding:2px 6px;border-radius:4px}</style>`
  + `<main><h1>${title}</h1>${body}</main>`;

/** 1×1 PNG，仅用于在本地测试页产生一条真实的图片资源响应。 */
const PIXEL_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

const label = (id: string, name: string, content: string, x: number, y: number, width: number, height = 30, extra: Control = {}): Control => ({
  id, type: 'Label', name, content, x, y, width, height,
  fontSize: 12, fontFamily: 'Microsoft YaHei UI', background: '#1E293B', foreground: '#E2E8F0',
  isEnabled: true, visibility: 'Visible', properties: { staticStyle: 'text', textAlign: 'left' }, ...extra
});

const button = (id: string, name: string, content: string, x: number, y: number, width: number, height = 32): Control => ({
  id, type: 'Button', name, content, x, y, width, height,
  fontSize: 12, fontFamily: 'Microsoft YaHei UI', background: '#2563EB', foreground: '#FFFFFF',
  isEnabled: true, visibility: 'Visible', properties: { buttonStyle: 'push', cornerRadius: 6 },
  events: { Click: `_${name}_被单击` }
});

const textBox = (id: string, name: string, content: string, x: number, y: number, width: number, height = 32): Control => ({
  id, type: 'TextBox', name, content, x, y, width, height,
  fontSize: 12, fontFamily: 'Microsoft YaHei UI', background: '#0F172A', foreground: '#E2E8F0',
  isEnabled: true, visibility: 'Visible', properties: { multiline: false, readOnly: false, textAlign: 'left' }
});

const browser = (id: string, name: string, x: number, y: number, width: number, height: number, properties: Control = {}): Control => ({
  id, type: 'CefBrowser', name, content: '', x, y, width, height,
  fontSize: 12, fontFamily: 'Microsoft YaHei UI', background: '#FFFFFF', foreground: '#000000',
  isEnabled: true, visibility: 'Visible',
  properties: {
    url: 'about:blank', cacheDir: '.cef3/cache', enableJs: true, enableDevTools: true,
    loadImages: true, enableWebGL: false, muteAudio: true, proxyMode: 'system', ...properties
  }
});

interface Episode {
  no: string;
  dir: string;
  id: string;
  name: string;
  className: string;
  title: string;
  /** 口播稿点名、并且本示例真实调用的中文命令。 */
  commands: string[];
  modules: string[];
  controls: Control[];
  code: string[];
  globals?: string[];
  assets?: Array<[relativePath: string, content: string, encoding?: 'base64']>;
  /** 录制前必须知道的运行边界；同时写进录制准备.md 和验证记录.md。 */
  boundaries: string[];
  /** 录制动作清单，对应口播分段。 */
  steps: string[];
  window?: Control;
  /** 设计器非可视资源（如 CEF3 无头浏览器组件）；designer 与 build-request 共用。 */
  resources?: Control[];
}

const episodesWave1: Episode[] = [
  {
    no: '01',
    dir: '01 CEF3 入门',
    id: 'cef3-ep01-intro',
    name: 'CEF3 入门示例',
    className: 'CEF3入门窗体',
    title: 'CEF3 入门 · 原生内核与 SDK 前置',
    commands: ['CEF3_导航', 'CEF3_绑定事件', 'CEF3_取地址', 'CEF3_取标题'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      label('status', '运行状态', '等待 F5 运行……', 10, 10, 1070, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'https://example.com', cacheDir: '.cef3/ep01' })
    ],
    code: [
      '// 初始地址写在设计器控件属性「打开地址」里：CEF 浏览器是异步创建的，',
      '// 「创建完毕」触发时 bridge 句柄可能还没就绪，此时调用 CEF3_导航 会落空。',
      '// CEF3_导航 用于创建完成之后的主动跳转（见第 02 集的「转到」按钮）。',
      '事件 _CEF3入门窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    控件_设置文本(运行状态, "正在加载 example.com ……")',
      '结束',
      '',
      '事件 页面加载完成()',
      '    控件_设置文本(运行状态, CEF3_取地址(浏览器1))',
      '    调试输出("CEF3 页面加载完成：", CEF3_取标题(浏览器1))',
      '结束'
    ],
    assets: [['assets/intro.html', page('CEF3 本地测试页', '<p>只用于教程录制，不访问真实业务地址。</p><p>需要离线演示时，把导航地址改成本页的 <code>file:///</code> 绝对路径。</p>')]],
    boundaries: [
      '默认打开 https://example.com（写在设计器控件属性「打开地址」里）；断网或需要完全离线时改成 assets/intro.html 的 file:/// 绝对路径。',
      'CefBrowser 由运行时在「创建完毕」之前自动创建，代码里不需要再写 CEF 初始化。',
      '**初始地址必须走设计器属性，不能在「创建完毕」里调 CEF3_导航**：CEF 浏览器是异步创建的，此时 bridge 句柄常常还没就绪，导航会静默落空、页面停在 about:blank。CEF3_导航 只适用于创建完成之后的主动跳转（第 02 集「转到」按钮）。'
    ],
    steps: [
      'S2：模块面板启用「CEF3 浏览器模块」，画面停在 lingbuilder.cef3.browser。',
      'S3：SDK 下载对话框用干净缓存环境单独录制，不与本项目 F5 镜头连拍。',
      'S4：从工具箱拖入「CEF3浏览器」，属性页展示打开地址与缓存目录。',
      'S5：属性面板里把「打开地址」设为 https://example.com；「创建完毕」里只绑定加载完成事件，花字强调 浏览器1 是裸控件引用。',
      'S6：F5，确认错误列表 0、原生窗口出现网页；产物 bin/ 目录含 libcef.dll、chrome_elf.dll、resources.pak、icudtl.dat 与 locales/。'
    ]
  },
  {
    no: '02',
    dir: '02 浏览器操作小项目',
    id: 'cef3-ep02-browser-tool',
    name: 'CEF3 浏览器操作小项目',
    className: 'CEF3浏览器操作窗体',
    title: 'CEF3 浏览器操作小项目',
    commands: ['CEF3_导航', 'CEF3_后退', 'CEF3_前进', 'CEF3_刷新', 'CEF3_强制刷新', 'CEF3_停止', 'CEF3_执行缩放', 'CEF3_设置缩放级别', 'CEF3_取缩放级别', 'CEF3_执行JS', 'CEF3_取标题', 'CEF3_取地址'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      textBox('address-bar', '地址栏', 'https://example.com', 10, 10, 300),
      button('go-button', '转到按钮', '转到', 316, 10, 60),
      button('back-button', '后退按钮', '后退', 382, 10, 60),
      button('forward-button', '前进按钮', '前进', 448, 10, 60),
      button('refresh-button', '刷新按钮', '刷新', 514, 10, 60),
      button('hard-refresh-button', '强制刷新按钮', '强制刷新', 580, 10, 80),
      button('stop-button', '停止按钮', '停止', 666, 10, 60),
      button('zoom-in-button', '放大按钮', '放大', 732, 10, 60),
      button('zoom-out-button', '缩小按钮', '缩小', 798, 10, 60),
      button('zoom-reset-button', '重置按钮', '重置', 864, 10, 60),
      label('title-label', '标题标签', 'CEF3 浏览器', 930, 10, 150, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'https://example.com', cacheDir: '.cef3/ep02' })
    ],
    code: [
      '// 初始地址由设计器控件属性「打开地址」给出（CEF 异步创建，创建完毕时导航会落空）；',
      '// 「转到」按钮发生在创建完成之后，那里的 CEF3_导航 才是有效的主动跳转。',
      '事件 _CEF3浏览器操作窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    控件_设置文本(标题标签, CEF3_取标题(浏览器1))',
      '    调试输出("当前地址：", CEF3_取地址(浏览器1))',
      '    调试输出("脚本标题：", CEF3_执行JS(浏览器1, "document.title"))',
      '结束',
      '',
      '事件 _转到按钮_被单击()',
      '    局部 文本型 目标地址 = 控件_取文本(地址栏)',
      '    CEF3_导航(浏览器1, 目标地址)',
      '结束',
      '',
      '事件 _后退按钮_被单击()',
      '    CEF3_后退(浏览器1)',
      '结束',
      '',
      '事件 _前进按钮_被单击()',
      '    CEF3_前进(浏览器1)',
      '结束',
      '',
      '事件 _刷新按钮_被单击()',
      '    CEF3_刷新(浏览器1)',
      '结束',
      '',
      '事件 _强制刷新按钮_被单击()',
      '    CEF3_强制刷新(浏览器1)',
      '结束',
      '',
      '事件 _停止按钮_被单击()',
      '    CEF3_停止(浏览器1)',
      '结束',
      '',
      '// 缩放命令取值固定为 0 缩小、1 重置、2 放大。',
      '事件 _放大按钮_被单击()',
      '    CEF3_执行缩放(浏览器1, 2)',
      '    调试输出("当前缩放：", CEF3_取缩放级别(浏览器1))',
      '结束',
      '',
      '事件 _缩小按钮_被单击()',
      '    CEF3_执行缩放(浏览器1, 0)',
      '    调试输出("当前缩放：", CEF3_取缩放级别(浏览器1))',
      '结束',
      '',
      '事件 _重置按钮_被单击()',
      '    CEF3_设置缩放级别(浏览器1, 0.0)',
      '    调试输出("缩放已重置：", CEF3_取缩放级别(浏览器1))',
      '结束'
    ],
    assets: [
      ['assets/home.html', page('CEF3 操作演示 · 首页', '<p>点击下面的链接，可以演示后退与前进。</p><p><a href="second.html">前往第二页</a></p>')],
      ['assets/second.html', page('CEF3 操作演示 · 第二页', '<p>这是第二页，用来验证后退、前进和刷新。</p><p><a href="home.html">返回首页</a></p>', '#059669')]
    ],
    boundaries: [
      '缩放命令的合法取值只有 0（缩小）、1（重置）、2（放大）；传其它值会被 Bridge 拒绝。',
      '重置按钮使用 CEF3_设置缩放级别(浏览器1, 0.0)，0.0 表示 100% 原始比例。',
      '离线录制时把地址栏改成 assets/home.html 的 file:/// 绝对路径，后退/前进用 home ↔ second 两页演示。'
    ],
    steps: [
      'S2～S5：依次演示地址栏 + 转到、后退/前进、刷新/强制刷新/停止、放大/缩小/重置。',
      'S5：执行 JS 读标题，标题标签与调试输出同时更新。',
      'S6：F5 后按上面顺序点一遍，每一步都要有真实页面变化，错误列表保持 0。'
    ]
  },
  {
    no: '03',
    dir: '03 事件驱动',
    id: 'cef3-ep03-events',
    name: 'CEF3 事件驱动示例',
    className: 'CEF3事件驱动窗体',
    title: 'CEF3 事件驱动 · 加载完成与事件数据',
    commands: ['CEF3_绑定事件', 'CEF3_取最近事件', 'CEF3_取事件数据', 'CEF3_取事件字段', 'CEF3_是否加载中'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      label('status', '事件状态', '等待事件……', 10, 10, 1070, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'https://example.com', cacheDir: '.cef3/ep03' })
    ],
    code: [
      '// 初始地址由设计器控件属性「打开地址」给出：绑定事件必须早于首次加载，',
      '// 而 CEF 异步创建导致「创建完毕」里的 CEF3_导航 会落空。',
      '事件 _CEF3事件驱动窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "开始加载", &页面开始加载)',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    CEF3_绑定事件(浏览器1, "加载状态改变", &加载状态改变)',
      '    CEF3_绑定事件(浏览器1, "加载失败", &页面加载失败)',
      '结束',
      '',
      '事件 页面开始加载()',
      '    控件_设置文本(事件状态, "开始加载")',
      '    调试输出("事件：", CEF3_取最近事件(浏览器1), " 地址：", CEF3_取事件字段(浏览器1, "url"))',
      '结束',
      '',
      '事件 页面加载完成()',
      '    控件_设置文本(事件状态, "加载完成")',
      '    调试输出("事件：", CEF3_取最近事件(浏览器1), " 事件数据：", CEF3_取事件数据(浏览器1))',
      '    调试输出("状态码：", CEF3_取事件字段(浏览器1, "statusCode"))',
      '结束',
      '',
      '事件 加载状态改变()',
      '    调试输出("是否加载中：", CEF3_是否加载中(浏览器1))',
      '结束',
      '',
      '事件 页面加载失败()',
      '    控件_设置文本(事件状态, "加载失败")',
      '    调试输出("失败地址：", CEF3_取事件字段(浏览器1, "url"), " 错误：", CEF3_取事件字段(浏览器1, "errorText"))',
      '结束',
      '',
      '// 通知类事件异步回到窗口线程；需要同步答复的决策事件用 CEF3_设置事件结果，见第 05 集。'
    ],
    assets: [['assets/events.html', page('CEF3 事件测试页', '<p>页面加载完成后，输出面板会依次记录开始加载、加载状态改变和加载完成。</p>', '#7C3AED')]],
    boundaries: [
      '事件实名以事件目录为准：开始加载 / 加载完成 / 加载失败 / 加载状态改变；不要写成「加载开始」或「加载错误」。',
      'CEF3_取事件字段 返回的是文本快照，字段缺失时返回空文本，不会抛出异常。',
      '决策类事件的 CEF3_设置事件结果 在第 05 集演示，本集只做通知类事件。'
    ],
    steps: [
      'S2：写 CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)，花字强调 &页面加载完成。',
      'S3：处理器里读 CEF3_取最近事件 与 CEF3_取事件数据。',
      'S4：读 url / statusCode 字段，状态标签与输出面板同时更新。',
      'S6：F5 后输出面板按 开始加载 → 加载状态改变 → 加载完成 顺序滚动。'
    ]
  },
  {
    no: '04',
    dir: '04 会话隔离',
    id: 'cef3-ep04-session-isolation',
    name: 'CEF3 会话隔离示例',
    className: 'CEF3会话隔离窗体',
    title: 'CEF3 会话隔离 · 缓存目录与多实例',
    commands: ['CEF3会话_取缓存目录', 'CEF3_绑定事件', 'CEF3_执行JS'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.session'],
    controls: [
      label('left-status', '左侧状态', '左侧会话：等待加载……', 10, 10, 520, 32),
      label('right-status', '右侧状态', '右侧会话：等待加载……', 540, 10, 400, 32),
      button('inspect-button', '读取会话按钮', '读取缓存目录', 950, 10, 130),
      browser('browser-left', '浏览器1', 10, 52, 520, 660, { url: 'https://example.com', cacheDir: '.cef3/ep04-left' }),
      browser('browser-right', '浏览器2', 540, 52, 540, 660, { url: 'https://example.com', cacheDir: '.cef3/ep04-right' })
    ],
    code: [
      '// 两个实例的初始地址与缓存目录都写在设计器控件属性里（创建前配置）。',
      '事件 _CEF3会话隔离窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &左侧加载完成)',
      '    CEF3_绑定事件(浏览器2, "加载完成", &右侧加载完成)',
      '结束',
      '',
      '// 脚本用方括号写法读写 LocalStorage：中文代码的语言服务会把字符串里的 “对象.方法(” 当成功能库调用。',
      '事件 左侧加载完成()',
      '    CEF3_执行JS(浏览器1, "localStorage[\'会话标记\'] = \'左侧\'")',
      '    控件_设置文本(左侧状态, CEF3_执行JS(浏览器1, "localStorage[\'会话标记\']"))',
      '结束',
      '',
      '事件 右侧加载完成()',
      '    CEF3_执行JS(浏览器2, "localStorage[\'会话标记\'] = \'右侧\'")',
      '    控件_设置文本(右侧状态, CEF3_执行JS(浏览器2, "localStorage[\'会话标记\']"))',
      '结束',
      '',
      '事件 _读取会话按钮_被单击()',
      '    调试输出("左侧缓存目录：", CEF3会话_取缓存目录(浏览器1))',
      '    调试输出("右侧缓存目录：", CEF3会话_取缓存目录(浏览器2))',
      '结束',
      '',
      '// 缓存目录是会话边界，必须在浏览器创建前确定。',
      '// 设计器控件由运行时在「创建完毕」之前自动创建，所以这里用属性面板的「缓存目录」配置。',
      '// 纯代码创建实例时才写成：先 CEF3_设置缓存目录(浏览器1, ".cef3/ep04-left")，再 CEF3_创建(浏览器1)。'
    ],
    assets: [
      ['assets/storage-left.html', page('会话隔离 · 左侧', '<p>本页把 <code>会话标记</code> 写进 LocalStorage，用来验证左右两个实例互不影响。</p>')],
      ['assets/storage-right.html', page('会话隔离 · 右侧', '<p>本页把 <code>会话标记</code> 写进 LocalStorage，用来验证左右两个实例互不影响。</p>', '#DC2626')]
    ],
    boundaries: [
      '运行时在窗口「创建完毕」之前已经创建全部 CefBrowser，因此 CEF3_设置缓存目录 只能用于纯代码创建的实例；设计器项目请用属性面板的「缓存目录」。',
      '本集用属性面板配置 .cef3/ep04-left 与 .cef3/ep04-right，两个实例使用不同 RequestContext。',
      '演示只写入自造的 LocalStorage 标记，不使用真实账号或真实 Cookie。',
      '中文代码里的 JS 字符串避免写成 `对象.方法(...)`：语言服务会把它识别成功能库调用并报「找不到功能库」，示例改用方括号写法。'
    ],
    steps: [
      'S2：设计器里展示左右两个 CEF3浏览器，名称为 浏览器1、浏览器2。',
      'S3：属性面板展示两个不同的缓存目录，花字「创建前配置」。',
      'S4：F5 后两侧分别写入并读回不同的 LocalStorage 标记。',
      'S5：点「读取缓存目录」，调试输出两条不同的实际目录。',
      'S6：交换页面刷新，两边的值始终不同即验证通过。'
    ]
  },
  {
    no: '05',
    dir: '05 代理与请求决策',
    id: 'cef3-ep05-network-decision',
    name: 'CEF3 代理与请求决策示例',
    className: 'CEF3请求决策窗体',
    title: 'CEF3 代理与请求前决策',
    commands: ['CEF3_绑定事件', 'CEF3_取事件字段', 'CEF3_设置事件结果'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.network'],
    globals: ['全局 整数型 本次目标受限 = 0'],
    controls: [
      label('status', '决策状态', '等待请求……', 10, 10, 760, 32),
      button('open-blocked', '打开受限页按钮', '打开受限测试页', 780, 10, 150),
      button('open-allowed', '打开放行页按钮', '打开放行测试页', 936, 10, 144),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep05', proxyMode: 'none' })
    ],
    code: [
      '事件 _CEF3请求决策窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "导航请求前", &导航请求前)',
      '    CEF3_绑定事件(浏览器1, "资源加载前", &资源加载前)',
      '    控件_设置文本(决策状态, "已启用请求前决策；默认直连，不使用任何真实代理。")',
      '结束',
      '',
      '事件 导航请求前()',
      '    局部 文本型 地址 = CEF3_取事件字段(浏览器1, "url")',
      '    如果 (本次目标受限 == 1)',
      '        CEF3_设置事件结果(浏览器1, 2)',
      '        控件_设置文本(决策状态, "已取消导航（命中测试拦截规则）")',
      '        调试输出("已取消：", 地址)',
      '    否则',
      '        CEF3_设置事件结果(浏览器1, 1)',
      '        调试输出("已放行：", 地址)',
      '    如果结束',
      '结束',
      '',
      '事件 资源加载前()',
      '    调试输出("资源请求：", CEF3_取事件字段(浏览器1, "url"))',
      '结束',
      '',
      '事件 _打开受限页按钮_被单击()',
      '    本次目标受限 = 1',
      '    CEF3_导航(浏览器1, "https://example.com/blocked")',
      '结束',
      '',
      '事件 _打开放行页按钮_被单击()',
      '    本次目标受限 = 0',
      '    CEF3_导航(浏览器1, "https://example.com/")',
      '结束',
      '',
      '// 结果 1 表示允许继续，结果 2 表示取消；不调用结果接口则保持默认行为。',
      '// 代理必须在创建前确定：设计器项目用「代理模式 / 自定义代理地址」属性，',
      '// 纯代码创建实例时才写成：先 CEF3_设置代理(浏览器1, "http://127.0.0.1:8888")，再 CEF3_创建(浏览器1)。'
    ],
    assets: [
      ['assets/allow.html', page('放行测试页', '<p>本页代表允许继续的请求，处理器会返回结果 1。</p>')],
      ['assets/blocked.html', page('受限测试页', '<p>地址里包含 <code>blocked</code> 时，处理器返回结果 2 取消导航，并在界面上给出中文原因。</p>', '#DC2626')]
    ],
    boundaries: [
      '示例默认直连（proxyMode=none），不配置任何真实代理；需要演示代理时改属性面板的「代理模式」为自定义并填入本地授权测试代理，凭据不得入镜。',
      'CEF3_设置代理 只能在浏览器创建前生效；设计器项目的等价配置是控件属性。',
      '拦截规则只作用于自造的 blocked 测试路径，不拦截真实业务流量。',
      '当前基础模块没有文本包含判断命令，示例用项目全局变量 `本次目标受限` 标记本次目标，再在决策事件里返回结果；换成自己的规则时只要改这一处判断。',
      '决策处理器里不做长耗时任务，避免阻塞请求线程。'
    ],
    steps: [
      'S2：展示代理模式属性；敏感字段全部打码。',
      'S4：写 CEF3_绑定事件 绑定「导航请求前」「资源加载前」。',
      'S5：点「打开受限测试页」，界面显示中文“已取消”，输出写明原因。',
      'S6：再点「打开放行测试页」，同一套处理器放行，错误列表保持 0。'
    ]
  },
  {
    no: '06',
    dir: '06 获取网页资源响应',
    id: 'cef3-ep06-resource-response',
    name: 'CEF3 资源响应元数据示例',
    className: 'CEF3资源响应窗体',
    title: 'CEF3 获取网页资源响应 · URL、状态码与 MIME',
    commands: ['CEF3_绑定事件', 'CEF3_取事件字段'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      label('status', '响应状态', '等待资源响应……', 10, 10, 1070, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep06' })
    ],
    code: [
      '事件 _CEF3资源响应窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "资源响应到达", &资源响应到达)',
      '    控件_设置文本(响应状态, "请导航到 assets/index.html，观察多条资源响应。")',
      '结束',
      '',
      '事件 资源响应到达()',
      '    局部 文本型 地址 = CEF3_取事件字段(浏览器1, "url")',
      '    局部 文本型 状态码 = CEF3_取事件字段(浏览器1, "statusCode")',
      '    局部 文本型 内容类型 = CEF3_取事件字段(浏览器1, "mimeType")',
      '    控件_设置文本(响应状态, 内容类型)',
      '    调试输出("资源：", 地址)',
      '    调试输出("    状态码：", 状态码, "    MIME：", 内容类型)',
      '结束',
      '',
      '// 边界：本集只读取公开响应元数据。响应正文、响应头映射和响应过滤器不属于当前公开 binding，',
      '// 不能把「资源响应到达」说成「已经拿到正文」。'
    ],
    assets: [
      ['assets/index.html', page('资源响应测试页', '<p>本页故意引用样式、脚本和图片，打开一次就能看到多条资源响应。</p><p><img src="pixel.png" width="120" height="8" alt="测试图片"></p>')
        .replace('</style>', '</style><link rel="stylesheet" href="style.css"><script src="script.js" defer></script>')],
      ['assets/style.css', '/* 教程用本地样式，只为产生一条 text/css 资源响应。 */\nmain { box-shadow: 0 8px 24px rgba(15, 23, 42, .08); }\n'],
      ['assets/script.js', '// 教程用本地脚本，只为产生一条 JavaScript 资源响应。\ndocument.title = document.title + " · 已加载脚本";\n'],
      ['assets/pixel.png', PIXEL_PNG_BASE64, 'base64']
    ],
    boundaries: [
      '事件实名为「资源响应到达」，录制前以事件目录为准。',
      '只读取 url、statusCode、mimeType 等公开元数据；正文读取、响应头映射、响应过滤器不在当前公开 binding 内，口播不得宣称可直接读正文。',
      'file:// 页面不会返回 HTTP 状态码，statusCode 可能为 0 或空；需要真实状态码时使用本地 HTTP 测试服务。'
    ],
    steps: [
      'S2：先展示 assets/index.html 及其 style.css、script.js、pixel.png。',
      'S3：写 CEF3_绑定事件 绑定「资源响应到达」。',
      'S4：处理器里依次读 url、statusCode、mimeType，输出按资源类型分组。',
      'S6：打能力边界卡「公开元数据 ≠ 响应正文」。'
    ]
  },
  {
    no: '07',
    dir: '07 资源加载生命周期',
    id: 'cef3-ep07-resource-lifecycle',
    name: 'CEF3 资源加载生命周期示例',
    className: 'CEF3资源生命周期窗体',
    title: 'CEF3 资源加载生命周期',
    commands: ['CEF3_绑定事件', 'CEF3_取事件字段'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      label('status', '生命周期状态', '等待资源事件……', 10, 10, 1070, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep07' })
    ],
    code: [
      '事件 _CEF3资源生命周期窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "资源加载前", &资源加载前)',
      '    CEF3_绑定事件(浏览器1, "资源响应到达", &资源响应到达)',
      '    CEF3_绑定事件(浏览器1, "资源重定向", &资源重定向)',
      '    CEF3_绑定事件(浏览器1, "资源加载完成", &资源加载完成)',
      '    控件_设置文本(生命周期状态, "已绑定资源加载前 → 响应到达 → 重定向 → 加载完成。")',
      '结束',
      '',
      '事件 资源加载前()',
      '    调试输出("[1/4] 资源加载前：", CEF3_取事件字段(浏览器1, "url"))',
      '结束',
      '',
      '事件 资源响应到达()',
      '    调试输出("[2/4] 资源响应到达：", CEF3_取事件字段(浏览器1, "url"), " 状态码：", CEF3_取事件字段(浏览器1, "statusCode"))',
      '结束',
      '',
      '事件 资源重定向()',
      '    调试输出("[3/4] 资源重定向：", CEF3_取事件字段(浏览器1, "url"), " → ", CEF3_取事件字段(浏览器1, "newUrl"))',
      '    控件_设置文本(生命周期状态, "已跟随一次重定向")',
      '结束',
      '',
      '事件 资源加载完成()',
      '    调试输出("[4/4] 资源加载完成：", CEF3_取事件字段(浏览器1, "url"), " 状态：", CEF3_取事件字段(浏览器1, "status"))',
      '结束',
      '',
      '// 边界：响应过滤器和受管资源源涉及更多对象与生命周期，本集只讲可观察、可复现的事件链。'
    ],
    assets: [
      ['assets/start.html', page('生命周期 · 起点', '<p>点击下面的链接触发一次跳转，观察四个阶段的事件顺序。</p><p><a href="redirect.html">前往重定向页</a></p>')],
      ['assets/redirect.html', page('生命周期 · 重定向', '<p>本页会自动跳转到 <code>final.html</code>。</p>', '#F59E0B')
        .replace('<main>', '<meta http-equiv="refresh" content="1;url=final.html"><main>')],
      ['assets/final.html', page('生命周期 · 终点', '<p>跳转完成。资源加载完成事件会记录成功、失败或取消。</p>', '#059669')]
    ],
    boundaries: [
      '「资源重定向」对应 HTTP 3xx。file:// 与 meta refresh 不产生 3xx，本地页链只用于讲解顺序；要拍到真实重定向事件，必须使用能返回 302 的本地 HTTP 测试服务。',
      '「资源加载完成」是高频事件，录制时页面要保持简单，避免日志刷屏。',
      '页面加载完成不等于每个资源都成功，资源级日志才能看出失败与取消。'
    ],
    steps: [
      'S2～S5：按 资源加载前 → 资源响应到达 → 资源重定向 → 资源加载完成 逐个节点讲。',
      'S4：重定向镜头如需真实 3xx，改用本地 HTTP 测试服务的 /redirect → /final。',
      'S6：打高级能力卡片，不展示未经验证的正文替换代码。'
    ]
  },
  {
    no: '08',
    dir: '08 下载打印查找',
    id: 'cef3-ep08-transfer-find',
    name: 'CEF3 下载、打印与页内查找示例',
    className: 'CEF3页面工具窗体',
    title: 'CEF3 下载、打印与页内查找',
    commands: ['CEF3传输_开始下载', 'CEF3传输_打印', 'CEF3_页内查找', 'CEF3_停止页内查找', 'CEF3_绑定事件', 'CEF3_取事件字段'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.transfer'],
    controls: [
      textBox('keyword-box', '查找框', 'LingBuilder', 10, 10, 220),
      button('find-button', '查找按钮', '查找', 236, 10, 70),
      button('find-stop-button', '停止查找按钮', '停止查找', 312, 10, 90),
      button('download-button', '下载按钮', '下载测试文件', 408, 10, 130),
      button('print-button', '打印按钮', '打印页面', 544, 10, 100),
      label('find-status', '查找结果', '等待查找……', 650, 10, 430, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep08' })
    ],
    code: [
      '事件 _CEF3页面工具窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "页内查找结果", &页内查找结果)',
      '    控件_设置文本(查找结果, "请先导航到 assets/find.html，再使用查找、下载和打印。")',
      '结束',
      '',
      '// 控件_取文本 返回文本对象，必须先落到局部文本变量再传给模块命令。',
      '事件 _查找按钮_被单击()',
      '    局部 文本型 关键词 = 控件_取文本(查找框)',
      '    CEF3_页内查找(浏览器1, 关键词, 真, 假, 真)',
      '结束',
      '',
      '事件 _停止查找按钮_被单击()',
      '    CEF3_停止页内查找(浏览器1, 真)',
      '    控件_设置文本(查找结果, "已停止查找并清除选区")',
      '结束',
      '',
      '事件 页内查找结果()',
      '    调试输出("匹配数：", CEF3_取事件字段(浏览器1, "count"), " 当前项：", CEF3_取事件字段(浏览器1, "activeMatchOrdinal"))',
      '    控件_设置文本(查找结果, CEF3_取事件字段(浏览器1, "count"))',
      '结束',
      '',
      '事件 _下载按钮_被单击()',
      '    CEF3传输_开始下载(浏览器1, "https://example.com/index.html")',
      '    控件_设置文本(查找结果, "已发起下载，保存路径由系统下载流程确认。")',
      '结束',
      '',
      '事件 _打印按钮_被单击()',
      '    CEF3传输_打印(浏览器1)',
      '结束',
      '',
      '// 页内查找不同步返回总数，匹配数量与当前序号只能从「页内查找结果」事件读取。'
    ],
    assets: [
      ['assets/find.html', page('下载与查找测试页', '<p>LingBuilder 让中文 C++ 也能写浏览器工具。</p><p>再出现一次 LingBuilder，便于验证匹配数量。</p><p>第三次 LingBuilder，用来演示查找下一项。</p><p><a href="download-demo.txt" download>下载测试文件</a></p>')],
      ['assets/download-demo.txt', 'LingBuilder CEF3 教程第 08 集下载测试文件。\n仅用于录制演示，不包含任何真实业务数据。\n']
    ],
    boundaries: [
      '打印会拉起系统打印对话框，录制时只展示测试内容，不确认真实打印，也不让个人文件路径入镜。',
      '下载保存路径由系统下载流程确认；示例不写死个人目录。',
      '离线录制时把下载地址改成 assets/download-demo.txt 的 file:/// 绝对路径。',
      'CEF3_页内查找 的参数依次为：文本、向前、区分大小写、查找下一个。'
    ],
    steps: [
      'S2：点「下载测试文件」，状态标签显示已发起下载。',
      'S3：点「打印页面」，只拍原生打印对话框出现，不完成打印。',
      'S4：查找框输入 LingBuilder，点查找，页面高亮多个匹配项。',
      'S5：结果标签显示匹配数与当前项；点「停止查找」清理选区。',
      'S6：F5 后按下载 → 打印 → 查找顺序走一遍，错误列表 0。'
    ]
  },
  {
    no: '09',
    dir: '09 JavaScript DevTools 异步任务',
    id: 'cef3-ep09-automation-devtools',
    name: 'CEF3 异步任务与开发者工具示例',
    className: 'CEF3自动化窗体',
    title: 'CEF3 JavaScript、DevTools 与异步任务',
    commands: ['CEF3自动化_执行JS异步', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_取错误', 'CEF3任务_释放', 'CEF3开发工具_打开', 'CEF3开发工具_执行协议方法'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.objects', 'lingbuilder.cef3.automation', 'lingbuilder.cef3.devtools'],
    controls: [
      button('run-script', '执行脚本按钮', '异步执行 JS', 10, 10, 130),
      button('read-result', '读取结果按钮', '读取任务结果', 146, 10, 130),
      button('open-devtools', '打开工具按钮', '打开开发者工具', 282, 10, 140),
      button('run-protocol', '协议按钮', '执行协议方法', 428, 10, 130),
      label('status', '任务状态', '等待发起异步任务……', 564, 10, 516, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep09', enableDevTools: true })
    ],
    globals: ['全局 长整数型 当前任务ID = 0'],
    code: [
      '事件 _CEF3自动化窗体_创建完毕()',
      '    控件_设置文本(任务状态, "先点「异步执行 JS」，再点「读取任务结果」。")',
      '结束',
      '',
      '事件 _执行脚本按钮_被单击()',
      '    当前任务ID = CEF3自动化_执行JS异步(浏览器1, "document.title")',
      '    控件_设置文本(任务状态, "已提交异步任务，窗口不会被阻塞。")',
      '    调试输出("任务 ID：", 当前任务ID)',
      '结束',
      '',
      '事件 _读取结果按钮_被单击()',
      '    如果 (当前任务ID == 0)',
      '        控件_设置文本(任务状态, "请先发起一个异步任务。")',
      '        返回',
      '    如果结束',
      '    调试输出("任务状态：", CEF3任务_取状态(当前任务ID))',
      '    调试输出("任务结果：", CEF3任务_取结果(当前任务ID))',
      '    调试输出("任务错误：", CEF3任务_取错误(当前任务ID))',
      '    控件_设置文本(任务状态, CEF3任务_取结果(当前任务ID))',
      '    CEF3任务_释放(当前任务ID)',
      '    当前任务ID = 0',
      '结束',
      '',
      '事件 _打开工具按钮_被单击()',
      '    CEF3开发工具_打开(浏览器1)',
      '结束',
      '',
      '事件 _协议按钮_被单击()',
      '    当前任务ID = CEF3开发工具_执行协议方法(浏览器1, "Runtime.enable", "{}")',
      '    控件_设置文本(任务状态, "已发送协议方法 Runtime.enable，请点「读取任务结果」。")',
      '结束',
      '',
      '// 任务 ID 是受管句柄，不是页面对象，也不能当成原生指针使用；读完必须调用 CEF3任务_释放。'
    ],
    assets: [['assets/automation.html', page('异步任务测试页', '<p>本页只提供一个稳定的标题，供 <code>document.title</code> 异步读取。</p>', '#0891B2')]],
    boundaries: [
      'CEF3自动化_执行JS异步 立即返回任务 ID，不等待结果；示例用两次点击分离“提交”与“读取”，这也是口播里的状态 → 结果 → 错误 → 释放四步。',
      '协议方法只使用审查过的 Runtime.enable，不演示任何可绕过安全策略的脚本。',
      '开发者工具窗口里不能出现工作区绝对路径或任何敏感数据。',
      '任务句柄读完即释放，避免受管对象泄漏。'
    ],
    steps: [
      'S2：点「异步执行 JS」，花字「任务 ID · 受管句柄」。',
      'S3：点「读取任务结果」，展示状态、结果、错误、释放四步。',
      'S4：点「打开开发者工具」，只拍短镜头并隐藏路径。',
      'S5：点「执行协议方法」，再读一次任务结果。',
      'S6：全过程窗口保持可操作，错误列表 0。'
    ]
  }
];

const episodesWave2: Episode[] = [
  {
    no: '14',
    dir: '14 无头浏览器抓取',
    id: 'cef3-ep14-headless',
    name: 'CEF3 无头抓取演练',
    className: 'CEF3无头抓取窗体',
    title: 'CEF3 无头浏览器 · 官方 OSR 无窗口抓取',
    commands: ['CEF3_创建无头浏览器', 'CEF3无头_是否已创建', 'CEF3无头_等待加载完成', 'CEF3无头_取标题', 'CEF3无头_取地址', 'CEF3无头_取页面文本', 'CEF3无头_取页面源码', 'CEF3无头_等待出帧', 'CEF3无头_取渲染帧数', 'CEF3无头_取视口JSON', 'CEF3无头_执行JS', 'CEF3无头_取事件JSON', 'CEF3无头_取主框架', 'CEF3框架_执行JS', 'CEF3框架_释放', 'CEF3无头_取浏览器句柄', 'CEF3OSR_设置窗口外帧率', 'CEF3OSR_取窗口外帧率', 'CEF3无头_导航', 'CEF3无头_关闭'],
    globals: ['全局 文本型 无头标题 = ""', '全局 文本型 无头正文 = ""', '全局 文本型 无头视口 = ""', '全局 文本型 无头执行JS信封 = ""', '全局 文本型 无头改标题 = ""', '全局 长整数型 无头帧数 = 0', '全局 整数型 无头帧率 = 0', '全局 文本型 无头失败原因 = ""'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.osr', 'lingbuilder.cef3.automation', 'lingbuilder.cef3.objects', 'lingbuilder.threading'],
    resources: [
      {
        id: 'headless-1',
        type: 'CefHeadlessBrowser',
        name: '无头抓取1',
        designerX: 260,
        designerY: 24,
        ownerWindowId: 'main-window',
        instanceId: 1,
        url: 'https://example.com',
        cacheDir: '.cef3/ep14-headless',
        proxyServer: '',
        viewWidth: 1024,
        viewHeight: 640,
        autoStart: true
      }
    ],
    controls: [
      button('run-button', '抓取按钮', '重新抓取', 24, 24, 150),
      button('nav-button', '导航按钮', '无头跳转第二页', 186, 24, 170),
      button('close-button', '关闭按钮', '关闭无头实例', 368, 24, 150),
      label('status', '状态标签', '等待 F5 运行……', 24, 76, 560, 30),
      label('result', '结果标签', '无头实例由设计器组件在窗口创建期自动建立（实例编号 1）', 24, 114, 560, 30)
    ],
    code: [
      '// 无头实例由设计器「CEF3无头浏览器」非可视组件在窗口创建期自动创建（实例编号 1），',
      '// 全部按实例编号寻址。等待类操作放进工作线程：线程_协作等待是真休眠，不冻结窗口消息泵。',
      '事件 _CEF3无头抓取窗体_创建完毕()',
      '    控件_设置文本(状态标签, "无头抓取演练运行中（工作线程）……")',
      '    线程_提交完成(&无头工作, &无头完成)',
      '结束',
      '',
      '事件 _抓取按钮_被单击()',
      '    线程_提交完成(&无头工作, &无头完成)',
      '结束',
      '',
      '// 演示 CEF3无头_导航：创建后立刻导航会被排队补发，不会静默丢失。',
      '事件 _导航按钮_被单击()',
      '    控件_设置文本(状态标签, "无头跳转第二页……")',
      '    线程_提交完成(&无头跳转工作, &无头跳转完成)',
      '结束',
      '',
      '事件 _关闭按钮_被单击()',
      '    CEF3无头_关闭(1)',
      '    控件_设置文本(状态标签, "无头实例已关闭（同一编号可再次创建）")',
      '结束',
      '',
      '整数型 无头工作()',
      '    如果 (CEF3无头_是否已创建(1) == 0)',
      '        无头失败原因 = "实例未创建：检查设计器组件与实例编号"',
      '        返回(0)',
      '    如果结束',
      '    调试输出("无头链路=实例已创建")',
      '    如果 (CEF3无头_等待加载完成(1, 25000) == 0)',
      '        无头失败原因 = "等待加载完成超时"',
      '        返回(0)',
      '    如果结束',
      '    调试输出("无头链路=加载完成 地址：", CEF3无头_取地址(1))',
      '    // 标题在加载完成之后才从渲染进程传回：协作轮询是真休眠。',
      '    无头标题 = ""',
      '    局部 整数型 标题轮询 = 0',
      '    计次循环首 (200, 标题轮询)',
      '        无头标题 = CEF3无头_取标题(1)',
      '        如果 (无头标题 != "")',
      '            跳出循环',
      '        如果结束',
      '        线程_协作等待(50)',
      '    计次循环尾',
      '    如果 (无头标题 == "")',
      '        无头失败原因 = "标题始终为空"',
      '        返回(0)',
      '    如果结束',
      '    // 主框架在「加载完成」之后才注册，同样协作轮询。',
      '    局部 长整数型 主框架 = 0',
      '    局部 整数型 框架轮询 = 0',
      '    计次循环首 (200, 框架轮询)',
      '        主框架 = CEF3无头_取主框架(1)',
      '        如果 (主框架 != 0)',
      '            跳出循环',
      '        如果结束',
      '        线程_协作等待(50)',
      '    计次循环尾',
      '    如果 (主框架 == 0)',
      '        无头失败原因 = "主框架迟迟未就绪"',
      '        返回(0)',
      '    如果结束',
      '    // 断言正文走句柄版：CEF3无头_取主框架 → CEF3框架_取文本异步。',
      '    局部 文本型 页面正文 = ""',
      '    局部 长整数型 正文任务 = 0',
      '    局部 整数型 正文状态 = 0',
      '    局部 整数型 正文轮次 = 0',
      '    计次循环首 (3, 正文轮次)',
      '        正文任务 = CEF3框架_取文本异步(主框架)',
      '        正文状态 = 0',
      '        局部 整数型 正文状态轮询 = 0',
      '        计次循环首 (100, 正文状态轮询)',
      '            正文状态 = CEF3任务_取状态(正文任务)',
      '            如果 (正文状态 == 2)',
      '                跳出循环',
      '            如果结束',
      '            如果 (正文状态 < 0)',
      '                跳出循环',
      '            如果结束',
      '            线程_协作等待(50)',
      '        计次循环尾',
      '        如果 (正文状态 == 2)',
      '            页面正文 = CEF3任务_取结果(正文任务)',
      '        如果结束',
      '        CEF3任务_释放(正文任务)',
      '        如果 (页面正文 != "")',
      '            跳出循环',
      '        如果结束',
      '        主框架 = CEF3无头_取主框架(1)',
      '        线程_协作等待(300)',
      '    计次循环尾',
      '    无头正文 = 页面正文',
      '    如果 (无头正文 == "")',
      '        无头失败原因 = "正文读取为空"',
      '        返回(0)',
      '    如果结束',
      '    如果 (CEF3无头_等待出帧(1, 8000) == 0)',
      '        无头失败原因 = "OSR 未出帧"',
      '        返回(0)',
      '    如果结束',
      '    无头帧数 = 0',
      '    局部 整数型 帧数轮询 = 0',
      '    计次循环首 (100, 帧数轮询)',
      '        无头帧数 = CEF3无头_取渲染帧数(1)',
      '        如果 (无头帧数 > 0)',
      '            跳出循环',
      '        如果结束',
      '        线程_协作等待(100)',
      '    计次循环尾',
      '    如果 (无头帧数 < 1)',
      '        无头失败原因 = "帧计数始终为零"',
      '        返回(0)',
      '    如果结束',
      '    无头视口 = CEF3无头_取视口JSON(1)',
      '    无头执行JS信封 = CEF3无头_执行JS(1, "document.title.length")',
      '    CEF3框架_执行JS(主框架, "document.title=\'LingBuilder无头改标题\'", "", 1)',
      '    CEF3无头_导航(1, CEF3无头_取地址(1))',
      '    CEF3无头_等待加载完成(1, 25000)',
      '    无头改标题 = CEF3无头_取标题(1)',
      '    CEF3框架_释放(主框架)',
      '    局部 长整数型 浏览器句柄 = CEF3无头_取浏览器句柄(1)',
      '    如果 (浏览器句柄 == 0)',
      '        无头失败原因 = "浏览器句柄为空"',
      '        返回(0)',
      '    如果结束',
      '    CEF3OSR_设置窗口外帧率(浏览器句柄, 30)',
      '    无头帧率 = CEF3OSR_取窗口外帧率(浏览器句柄)',
      '    返回(1)',
      '结束',
      '',
      '空 无头完成(线程任务 任务, 整数型 结果)',
      '    调试输出("无头标题观测：", 无头标题)',
      '    调试输出("无头正文断言：", 无头正文)',
      '    调试输出("无头视口观测：", 无头视口)',
      '    调试输出("无头执行JS信封：", 无头执行JS信封)',
      '    调试输出("无头帧数观测：", 无头帧数)',
      '    调试输出("无头改标题观测：", 无头改标题)',
      '    调试输出("无头帧率观测：", 无头帧率)',
      '    如果 (结果 == 1)',
      '        控件_设置文本(状态标签, "无头抓取演练完成，详见输出")',
      '        控件_设置文本(结果标签, "标题与正文已取到，帧数=" + 到文本(无头帧数))',
      '        调试输出("无头链路全部通过")',
      '    否则',
      '        控件_设置文本(状态标签, "无头链路失败：" + 无头失败原因)',
      '        调试输出("无头链路失败=", 无头失败原因)',
      '    如果结束',
      '结束',
      '',
      '文本型 无头跳转工作()',
      '    CEF3无头_导航(1, "https://www.example.org")',
      '    如果 (CEF3无头_等待加载完成(1, 25000) == 0)',
      '        返回("第二页加载超时")',
      '    如果结束',
      '    返回(CEF3无头_取标题(1))',
      '结束',
      '',
      '空 无头跳转完成(线程任务 任务, 文本型 结果)',
      '    控件_设置文本(状态标签, "第二页标题：" + 结果)',
      '    调试输出("无头第二页标题：", 结果)',
      '结束',
    ],
    assets: [],
    boundaries: [
      '无头实例有两种创建方式：设计器「CEF3无头浏览器」非可视组件（本示例，创建期自动建，autoStart）与控制台项目里直接调 CEF3_创建无头浏览器；两者都按实例编号寻址。',
      '受管句柄（主框架/浏览器句柄）是 64 位值且高位恒置 1，在 .lcpp 里显示为负数：判有效一律用「!= 0」，写「> 0」会把合法句柄判成无效。',
      '取内容前的必用前置是 CEF3无头_等待加载完成；「加载完成」不等于「已出帧」，证明渲染在跑必须用 CEF3无头_等待出帧（真机首帧约晚半秒）。',
      'CEF3无头_执行JS 返回 DevTools 信封 JSON，不是裸值；给无头实例绑定中文事件处理器无效，事件只能用 CEF3无头_取事件JSON 轮询（环形缓冲 200 条）。',
      '一期无画面输出：截图未开放，CEF3离屏_订阅像素帧 只点亮订阅位不外发内容；禁止用「创建可见窗口再隐藏」冒充无头。',
      '默认打开 https://example.com（设计器组件「打开地址」属性）；离线录制改成 assets 本地页的 file:/// 绝对路径。',
      'cef3-headless 缓存目录传空时默认为 cef3-headless-<实例编号>。'
    ],
    steps: [
      'S2：模块面板启用 CEF3浏览器模块 与 CEF3无头渲染模块；设计器资源区展示「CEF3无头浏览器」组件与实例编号 1。',
      'S3：F5 后窗口自动开始抓取，输出面板滚出 无头链路= 系列标记；花字「等待加载完成 → 才能取内容」。',
      'S4：特写 等待出帧 与 帧数观测，强调「加载完成≠已出帧」。',
      'S5：特写 执行JS 信封 JSON 与 事件缓冲 JSON，说明无头没有宿主窗口、事件靠轮询。',
      'S6：点「无头跳转第二页」演示 CEF3无头_导航 排队补发；点「关闭无头实例」收尾。',
      'S7：产物 bin/ 无窗口出现；控制台项目版命令链用 MCP_INSTRUCTIONS 第 3 条口径口播带过。'
    ]
  },
  {
    no: '15',
    dir: '15 自动填表',
    id: 'cef3-ep15-form-fill',
    name: 'CEF3 自动填表演练',
    className: 'CEF3填表演练窗体',
    title: 'CEF3 自动填表 · CSS 选择器操作页面元素',
    commands: ['CEF3框架_取主框架', 'CEF3填表_赋值', 'CEF3填表_置选择框', 'CEF3填表_置选择项', 'CEF3填表_置内文本', 'CEF3填表_置属性', 'CEF3填表_点击元素', 'CEF3填表_聚焦元素', 'CEF3填表_触发事件', 'CEF3填表_滚动到元素', 'CEF3填表_置外文本', 'CEF3框架_取文本异步', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_释放'],
    globals: ['全局 长整数型 框架句柄 = 0', '全局 长整数型 读取任务ID = 0', '全局 整数型 读取轮次 = 0', '全局 整数型 门控重查轮次 = 0'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.automation', 'lingbuilder.cef3.objects', 'lingbuilder.threading'],
    controls: [
      button('fill-button', '自动填写按钮', '自动填写并提交', 10, 10, 150),
      button('clear-button', '清空重填按钮', '清空表单', 168, 10, 110),
      label('status', '状态标签', '等待加载本地表单页……', 286, 10, 794, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep15' })
    ],
    code: [
      '// 填表命令的第一参数是框架句柄：先 CEF3框架_取主框架 拿主框架，再对 CSS 选择器操作。',
      '// 读页面结果用工作线程轮询任务状态：线程_协作等待真休眠，窗口消息泵不受影响。',
      '事件 _CEF3填表演练窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    局部 文本型 页面地址 = CEF3_取资源地址("form.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    调试输出("填表链路=加载完成触发 标题：", CEF3_取标题(浏览器1))',
      '    // about:blank 也会触发一次加载完成，用页面标题区分，别拿地址做包含判断。',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 填表测试页-就绪")',
      '        填表入口()',
      '    否则',
      '        如果 (CEF3_取标题(浏览器1) == "CEF3 填表测试页")',
      '            // 页面把标题改成 -就绪 的时机比加载完成事件晚半拍：延迟重查。',
      '            门控重查轮次 = 0',
      '            线程_提交完成(&门控等待工作, &门控等待完成)',
      '        如果结束',
      '    如果结束',
      '结束',
      '',
      '整数型 填表入口()',
      '    控件_设置文本(状态标签, "表单页已就绪，开始自动填写……")',
      '    填表操作()',
      '    开始读取页面文本()',
      '    返回(1)',
      '结束',
      '',
      '// 工作处理器只做纯等待；标题重查放回界面线程。',
      '整数型 门控等待工作()',
      '    线程_协作等待(500)',
      '    返回(0)',
      '结束',
      '',
      '空 门控等待完成(线程任务 任务, 整数型 结果)',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 填表测试页-就绪")',
      '        填表入口()',
      '        返回()',
      '    如果结束',
      '    门控重查轮次 = 门控重查轮次 + 1',
      '    如果 (门控重查轮次 < 12)',
      '        线程_提交完成(&门控等待工作, &门控等待完成)',
      '        返回()',
      '    如果结束',
      '    调试输出("填表链路失败=页面迟迟未就绪")',
      '结束',
      '',
      '事件 _自动填写按钮_被单击()',
      '    读取轮次 = 0',
      '    填表操作()',
      '    开始读取页面文本()',
      '结束',
      '',
      '事件 _清空重填按钮_被单击()',
      '    框架句柄 = CEF3框架_取主框架(浏览器1)',
      '    如果 (框架句柄 == 0)',
      '        返回()',
      '    如果结束',
      '    CEF3填表_赋值(框架句柄, "#username", 0, "")',
      '    CEF3填表_赋值(框架句柄, "#password", 0, "")',
      '    CEF3填表_置选择框(框架句柄, "#agree", 0, 假)',
      '    CEF3填表_置选择项(框架句柄, "#city", 0, 0)',
      '    CEF3填表_置内文本(框架句柄, "#notice", 0, "表单已清空，等待填写")',
      '    CEF3填表_置内文本(框架句柄, "#result", 0, "")',
      '    控件_设置文本(状态标签, "表单已清空")',
      '结束',
      '',
      '整数型 填表操作()',
      '    框架句柄 = CEF3框架_取主框架(浏览器1)',
      '    如果 (框架句柄 == 0)',
      '        控件_设置文本(状态标签, "主框架句柄为空：页面尚未就绪")',
      '        调试输出("填表链路失败=主框架句柄为空")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("填表链路=主框架已取得")',
      '    // 赋值会自动补发 input 与 change 事件，页面监听器能实时收到。',
      '    CEF3填表_赋值(框架句柄, "#username", 0, "林uilder")',
      '    CEF3填表_赋值(框架句柄, "#password", 0, "Lb@2026")',
      '    CEF3填表_置选择框(框架句柄, "#agree", 0, 真)',
      '    CEF3填表_置选择项(框架句柄, "#city", 0, 1)',
      '    CEF3填表_置内文本(框架句柄, "#notice", 0, "本表单由 LingBuilder 填表命令自动填写")',
      '    CEF3填表_置属性(框架句柄, "#username", 0, "data-filled", "1")',
      '    CEF3填表_聚焦元素(框架句柄, "#username", 0, 真)',
      '    CEF3填表_触发事件(框架句柄, "#username", 0, "keydown", 65)',
      '    CEF3填表_滚动到元素(框架句柄, "#submit-btn", 0, 真)',
      '    CEF3填表_点击元素(框架句柄, "#submit-btn", 0)',
      '    调试输出("填表链路=已点击提交")',
      '    返回(1)',
      '结束',
      '',
      '// 读取方向一期未开放：提交「取文本异步」任务，由工作线程轮询，完成后回界面线程。',
      '整数型 开始读取页面文本()',
      '    读取任务ID = CEF3框架_取文本异步(框架句柄)',
      '    线程_提交完成(&文本读取工作, &文本读取完成)',
      '    返回(1)',
      '结束',
      '',
      '整数型 文本读取工作()',
      '    局部 整数型 状态 = 0',
      '    局部 整数型 状态轮询 = 0',
      '    计次循环首 (100, 状态轮询)',
      '        状态 = CEF3任务_取状态(读取任务ID)',
      '        如果 (状态 == 2)',
      '            跳出循环',
      '        如果结束',
      '        如果 (状态 < 0)',
      '            跳出循环',
      '        如果结束',
      '        线程_协作等待(50)',
      '    计次循环尾',
      '    返回(状态)',
      '结束',
      '',
      '空 文本读取完成(线程任务 任务, 整数型 状态)',
      '    局部 文本型 页面文本 = ""',
      '    如果 (状态 == 2)',
      '        页面文本 = CEF3任务_取结果(读取任务ID)',
      '    如果结束',
      '    CEF3任务_释放(读取任务ID)',
      '    调试输出("填表链路=页面文本：", 页面文本)',
      '    // 页面在提交汇总写入后把标题改成 -已提交：用标题等值判断代替包含判断。',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 填表测试页-已提交")',
      '        CEF3填表_置外文本(框架句柄, "#footer-tag", 0, "已由填表命令更新")',
      '        控件_设置文本(状态标签, "填表演练完成：用户名/密码/勾选/下拉已写入并提交")',
      '        调试输出("填表链路全部通过")',
      '        返回()',
      '    如果结束',
      '    // 渲染进程偶发重启会让填写落空：整链重跑（最多 4 轮）。',
      '    读取轮次 = 读取轮次 + 1',
      '    如果 (读取轮次 < 4)',
      '        填表操作()',
      '        开始读取页面文本()',
      '        控件_设置文本(状态标签, "填写尚未送达，第 " + 到文本(读取轮次) + " 轮重试……")',
      '        返回()',
      '    如果结束',
      '    调试输出("填表链路失败=页面文本读取为空")',
      '结束',
    ],
    assets: [['assets/form.html', [
      '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 填表测试页</title>',
      '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:32px}',
      'main{max-width:640px;margin:auto;background:#fff;border-left:6px solid #2563EB;padding:24px 28px;border-radius:8px}',
      'label{display:block;margin:14px 0 4px;font-weight:600}input,select{padding:8px;border:1px solid #cbd5e1;border-radius:6px;width:280px}',
      '#notice{color:#2563EB;margin-top:10px}#result{color:#059669;font-weight:700;margin-top:12px;white-space:pre-wrap}',
      '#click-pad{margin-top:18px;width:180px;height:52px;line-height:52px;text-align:center;background:#e2e8f0;border-radius:8px}</style>',
      '<main><h1>CEF3 填表测试页</h1>',
      '<label>用户名</label><input id="username" placeholder="等待填写"><span id="key-count" style="margin-left:12px;color:#64748b">已收到按键事件：0</span>',
      '<label>密码</label><input id="password" type="password" placeholder="等待填写">',
      '<label><input id="agree" type="checkbox" style="width:auto"> 我已阅读并同意演示条款</label>',
      '<label>城市</label><select id="city"><option>北京</option><option>杭州</option><option>广州</option></select>',
      '<div id="notice">等待自动填写</div>',
      '<p><button id="submit-btn" style="padding:10px 26px;background:#2563EB;color:#fff;border:0;border-radius:6px">提交</button></p>',
      '<div id="result"></div><div id="click-pad">点我试试</div><p id="footer-tag">footer-tag：待更新</p>',
      '<script>const u=document.getElementById("username");let k=0;',
      'u.addEventListener("input",()=>{document.getElementById("notice").textContent="实时输入："+u.value;});',
      'u.addEventListener("keydown",()=>{k++;document.getElementById("key-count").textContent="已收到按键事件："+k;});',
      'document.getElementById("submit-btn").addEventListener("click",()=>{',
      'const c=document.getElementById("city");const a=document.getElementById("agree").checked;',
      'document.getElementById("result").textContent="提交成功："+u.value+" / "+c.options[c.selectedIndex].text+(a?" / 已同意":" / 未同意");});',
      'document.getElementById("click-pad").addEventListener("click",function(){this.textContent="已被单击";});',
'function __sum(){const c=document.getElementById("city");const a=document.getElementById("agree").checked;if(u.value){document.getElementById("result").textContent="提交成功："+u.value+" / "+c.options[c.selectedIndex].text+(a?" / 已同意":" / 未同意");document.title="CEF3 填表测试页-已提交";}}',
'document.addEventListener("change",__sum);document.addEventListener("input",__sum);',
'document.title="CEF3 填表测试页-就绪";</script></main></html>'
    ].join('')]],
    boundaries: [
      '填表命令的第一参数是框架句柄：CEF3框架_取主框架(控件名) 或无头实例的 CEF3无头_取主框架(实例编号)；句柄判有效只用「!= 0」。',
      '填表读取命令（取属性/取文本等）一期未开放；读页面结果用 CEF3框架_取文本异步 + CEF3任务_取状态 轮询（完成态=2），读完必须 CEF3任务_释放。',
      'CEF3填表_赋值 会自动补发 input 与 change 事件；CEF3填表_置选择框/置选择项 会补发 change，页面监听器可直接收到。',
      '本地表单页经 CEF3_取资源地址("form.html") 解析为 exe 同级 assets 目录地址；项目里对应 assets/form.html。',
      '区分「about:blank 首次加载完成」与目标页加载完成，用页面标题判断，不要对地址做包含判断。',
      '序号参数从 0 计数，传 -1 表示取首个匹配元素。'
    ],
    steps: [
      'S2：新建窗口工程，拖入「CEF3浏览器」控件与三个按钮；说明 assets/form.html 与 CEF3_取资源地址 的关系。',
      'S3：F5，浏览器自动打开本地表单页；输出面板滚出 填表链路= 标记。',
      'S4：特写浏览器画面：用户名/密码/勾选/下拉被自动写入，#notice 实时跟随（input 事件补发）。',
      'S5：特写点击提交后页面出现「提交成功：林uilder / 杭州 / 已同意」，强调点击元素回退合成 click。',
      'S6：点「清空表单」再点「自动填写并提交」，展示可重复演练。',
      'S7：口播提醒：读取方向命令后续版本提供，当前用 取文本异步+任务轮询 读结果。'
    ]
  },
  {
    no: '16',
    dir: '16 网页框架操作',
    id: 'cef3-ep16-frames',
    name: 'CEF3 网页框架演练',
    className: 'CEF3框架演练窗体',
    title: 'CEF3 网页框架 · iframe 遍历与跨框架操作',
    commands: ['CEF3框架_取主框架', 'CEF3框架_取框架数量', 'CEF3框架_取名称列表JSON', 'CEF3框架_取标识列表JSON', 'CEF3框架_按名称取框架', 'CEF3框架_按标识取框架', 'CEF3框架_取名称', 'CEF3框架_取地址', 'CEF3框架_是否主框架', 'CEF3框架_取父框架', 'CEF3框架_执行JS', 'CEF3框架_取文本异步', 'CEF3框架_取源码异步', 'CEF3框架_全选', 'CEF3框架_复制', 'CEF3框架_撤销', 'CEF3框架_释放', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_释放'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.automation', 'lingbuilder.cef3.objects'],
    controls: [
      button('demo-button', '框架演练按钮', '重新遍历框架', 10, 10, 140),
      button('edit-button', '编辑演练按钮', '主框架编辑演练', 158, 10, 150),
      label('status', '状态标签', '等待加载本地框架页……', 316, 10, 764, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep16' })
    ],
    code: [
      '// iframe 页面在 CEF 里是一棵框架树：主框架 + 若干子框架；每个框架都有受管句柄。',
      '// 框架句柄按「框架」寻址而不是控件：跨框架操作先用 按名称取框架 找到目标框架。',
      '事件 _CEF3框架演练窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    局部 文本型 页面地址 = CEF3_取资源地址("frames.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 框架演示页")',
      '        控件_设置文本(状态标签, "框架页已就绪，开始遍历……")',
      '        框架演练()',
      '    如果结束',
      '结束',
      '',
      '事件 _框架演练按钮_被单击()',
      '    框架演练()',
      '结束',
      '',
      '// 编辑命令族作用于框架的可编辑区域：演示页主框架放了一个 contenteditable 区域。',
      '事件 _编辑演练按钮_被单击()',
      '    局部 长整数型 主框架 = CEF3框架_取主框架(浏览器1)',
      '    如果 (主框架 == 0)',
      '        返回()',
      '    如果结束',
      '    CEF3框架_全选(主框架)',
      '    调试输出("编辑链路=全选结果：", CEF3框架_全选(主框架))',
      '    调试输出("编辑链路=复制结果：", CEF3框架_复制(主框架))',
      '    调试输出("编辑链路=撤销结果：", CEF3框架_撤销(主框架))',
      '    CEF3框架_释放(主框架)',
      '    控件_设置文本(状态标签, "编辑演练完成：全选 → 复制 → 撤销")',
      '结束',
      '',
      '整数型 框架演练()',
      '    局部 长整数型 主框架 = CEF3框架_取主框架(浏览器1)',
      '    如果 (主框架 == 0)',
      '        调试输出("框架链路失败=主框架句柄为空")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("框架链路=主框架地址：", CEF3框架_取地址(主框架))',
      '    局部 长整数型 框架数量 = CEF3框架_取框架数量(浏览器1)',
      '    调试输出("框架链路=框架总数：", 框架数量)',
      '    调试输出("框架链路=名称清单：", CEF3框架_取名称列表JSON(浏览器1))',
      '    调试输出("框架链路=标识清单：", CEF3框架_取标识列表JSON(浏览器1))',
      '    // 按名称取子框架：iframe 的 name 属性就是框架名。',
      '    局部 长整数型 内容框架 = CEF3框架_按名称取框架(浏览器1, "contentFrame")',
      '    如果 (内容框架 == 0)',
      '        调试输出("框架链路失败=contentFrame 未找到")',
      '        CEF3框架_释放(主框架)',
      '        返回(0)',
      '    如果结束',
      '    调试输出("框架链路=子框架名称：", CEF3框架_取名称(内容框架))',
      '    调试输出("框架链路=子框架地址：", CEF3框架_取地址(内容框架))',
      '    调试输出("框架链路=子框架是否主框架：", CEF3框架_是否主框架(内容框架))',
      '    调试输出("框架链路=子框架父句柄非零：", CEF3框架_取父框架(内容框架) != 0)',
      '    // 跨框架执行 JS：只影响该框架，不碰主框架与其它 iframe。',
      '    CEF3框架_执行JS(内容框架, "document.title=\'内容框架标题已改\'", "", 1)',
      '    局部 长整数型 文本任务 = CEF3框架_取文本异步(内容框架)',
      '    如果 (等待任务(文本任务) == 0)',
      '        调试输出("框架链路失败=子框架取文本超时")',
      '        CEF3框架_释放(内容框架)',
      '        CEF3框架_释放(主框架)',
      '        返回(0)',
      '    如果结束',
      '    调试输出("框架链路=子框架文本：", CEF3任务_取结果(文本任务))',
      '    CEF3任务_释放(文本任务)',
      '    局部 长整数型 源码任务 = CEF3框架_取源码异步(内容框架)',
      '    如果 (等待任务(源码任务) == 1)',
      '        调试输出("框架链路=子框架源码：", CEF3任务_取结果(源码任务))',
      '    如果结束',
      '    CEF3任务_释放(源码任务)',
      '    CEF3框架_释放(内容框架)',
      '    CEF3框架_释放(主框架)',
      '    控件_设置文本(状态标签, "框架演练完成：主框架 + 2 个 iframe 全部遍历")',
      '    调试输出("框架链路全部通过")',
      '    返回(1)',
      '结束',
      '',
      '整数型 等待任务(长整数型 任务ID)',
      '    局部 整数型 状态 = 0',
      '    局部 整数型 轮询 = 0',
      '    计次循环首 (1000000, 轮询)',
      '        状态 = CEF3任务_取状态(任务ID)',
      '        如果 (状态 == 2)',
      '            返回(1)',
      '        如果结束',
      '        如果 (状态 < 0)',
      '            返回(0)',
      '        如果结束',
      '    计次循环尾',
      '    返回(0)',
      '结束'
    ],
    assets: [
      ['assets/frames.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 框架演示页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;margin:0;padding:20px}',
        'h1{font-size:20px;margin:0 0 12px}iframe{border:2px solid #2563EB;border-radius:8px;background:#fff;margin-right:16px}</style>',
        '<h1>主框架页面（框架树：主框架 + 菜单框架 + 内容框架）</h1>',
        '<div id="pad" contenteditable="true" style="border:1px dashed #94a3b8;border-radius:6px;padding:10px;margin-bottom:14px;max-width:520px">主框架可编辑区域：选我试试全选与复制</div>',
        '<iframe name="menuFrame" src="frame-menu.html" width="300" height="380"></iframe>',
        '<iframe name="contentFrame" src="frame-content.html" width="620" height="380"></iframe></html>'
      ].join('')],
      ['assets/frame-menu.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>菜单框架页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;padding:14px;color:#0f172a}li{margin:8px 0}</style>',
        '<h3>菜单框架</h3><ul><li>第一课</li><li>第二课</li><li>第三课</li></ul></html>'
      ].join('')],
      ['assets/frame-content.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>内容框架页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;padding:14px;color:#0f172a}</style>',
        '<h3>内容框架</h3><p>这是 contentFrame 里的正文，供跨框架取文本与改标题演示。</p></html>'
      ].join('')]
    ],
    boundaries: [
      '框架句柄是受管句柄：判有效只用「!= 0」；用完 CEF3框架_释放，重复释放返回 0。',
      'iframe 的 name 属性就是框架名，CEF3框架_按名称取框架 直接命中；无名称框架只能走标识清单。',
      'CEF3框架_执行JS/取文本异步/取源码异步 只作用于目标框架；跨框架读取不经过页面 JS，不受同源策略困扰。',
      '异步命令返回任务句柄：CEF3任务_取状态 完成态=2，读完必须 CEF3任务_释放。',
      'about:blank 首次加载也会触发「加载完成」，用页面标题区分首次与目标页。'
    ],
    steps: [
      'S2：讲解框架树概念图版（主框架 + menuFrame + contentFrame）。',
      'S3：F5 后自动遍历：特写输出面板的 框架总数=3、名称清单 JSON。',
      'S4：特写 按名称取框架 → 子框架地址/是否主框架/父框架 三连。',
      'S5：跨框架改标题 + 取文本异步，花字「框架句柄 = 页面操作的坐标」。',
      'S6：点「主框架编辑演练」，展示全选/复制/撤销三命令。',
      'S7：口播承接第 15 集：子框架里照样可以用 CEF3填表_* 做跨框架填表。'
    ]
  },
  {
    no: '17',
    dir: '17 多实例与多店铺',
    id: 'cef3-ep17-multi-store',
    name: 'CEF3 多实例多店铺演练',
    className: 'CEF3多实例窗体',
    title: 'CEF3 多实例 · 独立缓存/独立UA 的多店铺窗口',
    commands: ['CEF3_创建区域', 'CEF3_创建弹窗浏览器', 'CEF3_设置实例用户代理', 'CEF3_取实例用户代理', 'CEF3_取实例代理', 'CEF3_取全局代理', 'CEF3会话_取上下文实例', 'CEF3会话_上下文取缓存目录', 'CEF3会话_释放上下文', 'CEF3_枚举实例JSON', 'CEF3_关闭全部实例'],
    assets: [['assets/multi-store.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>店铺演示页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:32px}',
        'main{max-width:560px;margin:auto;background:#fff;border-left:6px solid #7C3AED;padding:22px 26px;border-radius:8px}',
        'p{line-height:1.7}</style>',
        '<main><h3>多店铺演示页</h3>',
        '<p>本页由两个区域实例各自加载：缓存目录与 UA 互不相同。</p>',
        '<p>当前实例 UA 见宿主程序输出面板。</p>',
        '</main></html>'
      ].join('')]],
    globals: ['全局 整数型 弹窗店铺编号 = 10', '全局 整数型 登记轮次 = 0', '全局 文本型 店铺AUA = ""', '全局 文本型 店铺BUA = ""', '全局 文本型 店铺A代理 = ""', '全局 文本型 全局代理文本 = ""', '全局 文本型 实例清单文本 = ""'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.session', 'lingbuilder.cef3.objects'],
    controls: [
      button('demo-button', '重新演练按钮', '重建两家店铺', 10, 10, 140),
      button('enum-button', '枚举实例按钮', '枚举并核对', 158, 10, 120),
      button('popup-button', '弹窗店铺按钮', '开一家弹窗店铺', 276, 10, 150),
      button('close-button', '关闭全部按钮', '关闭全部实例', 434, 10, 130),
      label('status', '状态标签', '等待演练开始……', 572, 10, 508, 32)
    ],
    code: [
      '// 不依赖设计器控件：CEF3_创建区域 在窗口客户区按实例编号凭空创建内嵌浏览器，',
      '// 每个实例自带独立 profile 缓存目录（Cookie/会话隔离），代理留空=直连。',
      '// 实例登记到运行时表是异步的：创建后稍等片刻再点「枚举并核对」，别在创建后立刻查。',
      '事件 _CEF3多实例窗体_创建完毕()',
      '    多实例演练()',
      '结束',
      '',
      '事件 _重新演练按钮_被单击()',
      '    多实例演练()',
      '结束',
      '',
      '整数型 多实例演练()',
      '    CEF3_关闭全部实例()',
      '    局部 文本型 页面地址 = CEF3_取资源地址("multi-store.html")',
      '    局部 整数型 店铺A = CEF3_创建区域(1, 24, 96, 500, 560, 页面地址, ".cef3/ep17-store-a", "")',
      '    调试输出("店铺A创建结果：", 店铺A)',
      '    局部 整数型 店铺B = CEF3_创建区域(2, 548, 96, 500, 560, 页面地址, ".cef3/ep17-store-b", "")',
      '    调试输出("店铺B创建结果：", 店铺B)',
      '    控件_设置文本(状态标签, "两家店铺区域已创建，稍候点「枚举并核对」")',
      '    返回(1)',
      '结束',
      '',
      '// 登记完成后（页面已显示），一条链查回 UA、代理与实例清单——都在界面线程执行。',
      '事件 _枚举实例按钮_被单击()',
      '    CEF3_设置实例用户代理(1, "Mozilla/5.0 (LingBuilder-教程-店铺A)")',
      '    CEF3_设置实例用户代理(2, "Mozilla/5.0 (LingBuilder-教程-店铺B)")',
      '    店铺AUA = CEF3_取实例用户代理(1)',
      '    店铺BUA = CEF3_取实例用户代理(2)',
      '    店铺A代理 = CEF3_取实例代理(1)',
      '    全局代理文本 = CEF3_取全局代理()',
      '    实例清单文本 = CEF3_枚举实例JSON()',
      '    调试输出("店铺A UA：", 店铺AUA)',
      '    调试输出("店铺B UA：", 店铺BUA)',
      '    调试输出("店铺A 代理（空=直连）：", 店铺A代理)',
      '    调试输出("全局代理当前值（空=未设置）：", 全局代理文本)',
      '    调试输出("实例清单：", 实例清单文本)',
      '    控件_设置文本(状态标签, "两家店铺已核对：独立缓存 + 独立 UA，代理留空=直连")',
      '    调试输出("多实例链路全部通过")',
      '结束',
      '',
      '// 弹窗店铺：Chrome Runtime 独立顶层窗口，同样按实例编号登记，可被枚举与统一回收。',
      '事件 _弹窗店铺按钮_被单击()',
      '    局部 整数型 已创建 = CEF3_创建弹窗浏览器(弹窗店铺编号, "https://example.com", ".cef3/ep17-store-popup", "")',
      '    调试输出("弹窗店铺创建结果：", 已创建)',
      '    CEF3_设置实例用户代理(弹窗店铺编号, "Mozilla/5.0 (LingBuilder-教程-弹窗店)")',
      '    弹窗店铺编号 = 弹窗店铺编号 + 1',
      '    控件_设置文本(状态标签, "弹窗店铺已创建（独立顶层窗口）")',
      '结束',
      '',
      '事件 _关闭全部按钮_被单击()',
      '    局部 整数型 关闭数量 = CEF3_关闭全部实例()',
      '    调试输出("关闭全部实例数量：", 关闭数量)',
      '    控件_设置文本(状态标签, "已关闭全部实例：" + 到文本(关闭数量))',
      '结束',
    ],
    boundaries: [
      '区域/弹窗/无头实例都按「实例编号」寻址，不走设计器控件；实例表可被 CEF3_枚举实例JSON 枚举、CEF3_关闭全部实例 统一回收。',
      '实例隔离的三件套：不同 独立缓存目录（独立 profile，Cookie 互不可见）、实例级 UA（CEF3_设置实例用户代理）、实例级代理（创建参数，非空即独立出口）。',
      '带认证（用户名/密码）的代理 CEF3 不支持：CEF 150 不把 407 挑战投递给客户端；需要代理认证改用 FBro 或 EdgeView，且禁止把凭据拼进代理地址。',
      'CEF3_设置全局代理 影响之后新建的全部实例；实例自带代理优先；已创建实例不受影响。',
      '代理地址留空=直连（或回落全局代理）；演示全程留空，不展示任何真实代理凭据。',
      '创建区域 的坐标相对窗口客户区；关闭全部实例 也会关闭设计器控件实例。'
    ],
    steps: [
      'S2：概念图版「一个 exe 两家店铺」：实例编号 / 缓存目录 / UA / 代理 四要素。',
      'S3：F5 后两个区域内嵌浏览器并排出现，各自加载 example.com。',
      'S4：特写输出面板：两个缓存目录不同、两个 UA 不同（花字「隔离三件套」）。',
      'S5：点「开一家弹窗店铺」，独立顶层窗口出现；再点「枚举实例」展示 JSON 清单。',
      'S6：点「关闭全部实例」，窗口全部消失，花字「统一回收」。',
      'S7：口播红线：带认证代理请用 FBro/EdgeView，不拼凭据字符串。'
    ]
  },
  {
    no: '18',
    dir: '18 Cookie与会话管理',
    id: 'cef3-ep18-cookies',
    name: 'CEF3 Cookie 会话演练',
    className: 'CEF3会话演练窗体',
    title: 'CEF3 会话管理 · Cookie 写入/读取/删除/落盘',
    commands: ['HTTP_创建服务', 'HTTP_配置服务', 'HTTP_添加静态文件路由', 'HTTP_启动', 'CEF3会话_取上下文', 'CEF3会话_Cookie设置', 'CEF3会话_Cookie按地址读取', 'CEF3会话_Cookie落盘', 'CEF3会话_Cookie删除', 'CEF3框架_取主框架', 'CEF3框架_取文本异步', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_释放', 'CEF3_导航'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.session', 'lingbuilder.cef3.objects', 'lingbuilder.cef3.automation', 'lingbuilder.http.server'],
    controls: [
      button('write-button', '写入Cookie按钮', '写入 Cookie', 10, 10, 120),
      button('read-button', '读取Cookie按钮', '读取 Cookie', 138, 10, 120),
      button('flush-button', '落盘按钮', 'Cookie 落盘', 266, 10, 120),
      button('delete-button', '删除Cookie按钮', '删除 Cookie', 394, 10, 120),
      button('reload-button', '重新加载按钮', '刷新页面', 522, 10, 110),
      label('status', '状态标签', '等待演练开始……', 640, 10, 440, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep18' })
    ],
    globals: ['全局 长整数型 会话上下文 = 0', '全局 整数型 会话阶段 = 0', '全局 长整数型 本地服务端 = 0',
      '全局 整数型 应包含标记 = 0'],
    code: [
      '// Cookie 是会话级能力：先 CEF3会话_取上下文 拿 RequestContext 句柄，再对指定地址读写。',
      '// file:// 页面没有 Cookie；示例用内置 HTTP 服务端在 127.0.0.1:18080 起一个真实 HTTP 演示页。',
      '事件 _CEF3会话演练窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    如果 (启动本地服务() == 0)',
      '        控件_设置文本(状态标签, "本地演示服务启动失败（端口占用？），详见输出")',
      '        返回()',
      '    如果结束',
      '    调试输出("Cookie链路=本地服务已启动 127.0.0.1:18080")',
      '结束',
      '',
      '// 演示页是 assets/cookie-page.html：静态文件路由每次请求读磁盘最新内容；',
      '// 页面脚本写在 HTML 文件里，.lcpp 字符串不写带括号的 JS（会被语言服务误判功能库调用）。',
      '整数型 启动本地服务()',
      '    如果 (本地服务端 != 0)',
      '        返回(1)',
      '    如果结束',
      '    本地服务端 = HTTP_创建服务()',
      '    HTTP_配置服务(本地服务端, "127.0.0.1", 18080, 2, 64)',
      '    HTTP_添加静态文件路由(本地服务端, "GET", "/cookie-page", "assets/cookie-page.html", "", "text/html; charset=utf-8")',
      '    如果 (HTTP_启动(本地服务端) == 0)',
      '        调试输出("Cookie链路失败=HTTP_启动失败：", HTTP_取服务错误(本地服务端))',
      '        返回(0)',
      '    如果结束',
      '    返回(1)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    如果 (CEF3_取标题(浏览器1) == "Cookie 演示页")',
      '        如果 (会话阶段 == 1)',
      '            会话阶段 = 2',
      '            应包含标记 = 1',
      '            验证Cookie页面()',
      '            // 读取 → 落盘 → 删除，一条链走完。',
      '            读取并输出Cookie()',
      '            落盘Cookie()',
      '            删除Cookie()',
      '            局部 文本型 页面地址 = "http://127.0.0.1:18080/cookie-page"',
      '            CEF3_导航(浏览器1, 页面地址)',
      '        否则',
      '            如果 (会话阶段 == 2)',
      '                会话阶段 = 3',
      '                应包含标记 = 0',
      '                验证Cookie页面()',
      '                控件_设置文本(状态标签, "Cookie 演练完成：写入→读取→落盘→删除→复查")',
      '                调试输出("Cookie链路全部通过")',
      '            如果结束',
      '        如果结束',
      '    否则',
      '        如果 (会话阶段 == 0)',
      '            // 首次加载（about:blank）：浏览器对象此时已就绪，可以拿会话上下文了。',
      '            会话阶段 = 1',
      '            会话上下文 = CEF3会话_取上下文(浏览器1)',
      '            如果 (会话上下文 == 0)',
      '                调试输出("Cookie链路失败=会话上下文为空")',
      '                返回()',
      '            如果结束',
      '            调试输出("Cookie链路=会话上下文已取得")',
      '            写入Cookie()',
      '            CEF3_导航(浏览器1, "http://127.0.0.1:18080/cookie-page")',
      '        如果结束',
      '    如果结束',
      '结束',
      '',
      '整数型 写入Cookie()',
      '    局部 长整数型 写入任务 = CEF3会话_Cookie设置(会话上下文, "http://127.0.0.1:18080/", "lingbuilder_tutorial", "CEF3教程Cookie", "127.0.0.1", "/", 假, 假, 4102444800)',
      '    如果 (等待任务(写入任务) == 0)',
      '        调试输出("Cookie链路失败=写入超时")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("Cookie链路=写入结果：", CEF3任务_取结果(写入任务))',
      '    CEF3任务_释放(写入任务)',
      '    返回(1)',
      '结束',
      '',
      '整数型 读取并输出Cookie()',
      '    局部 长整数型 读取任务 = CEF3会话_Cookie按地址读取(会话上下文, "http://127.0.0.1:18080/", 假)',
      '    如果 (等待任务(读取任务) == 0)',
      '        调试输出("Cookie链路失败=读取超时")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("Cookie链路=按地址读取JSON：", CEF3任务_取结果(读取任务))',
      '    CEF3任务_释放(读取任务)',
      '    返回(1)',
      '结束',
      '',
      '整数型 落盘Cookie()',
      '    局部 长整数型 落盘任务 = CEF3会话_Cookie落盘(会话上下文)',
      '    如果 (等待任务(落盘任务) == 1)',
      '        调试输出("Cookie链路=落盘完成：", CEF3任务_取结果(落盘任务))',
      '    如果结束',
      '    CEF3任务_释放(落盘任务)',
      '    返回(1)',
      '结束',
      '',
      '整数型 删除Cookie()',
      '    局部 长整数型 删除任务 = CEF3会话_Cookie删除(会话上下文, "http://127.0.0.1:18080/", "lingbuilder_tutorial")',
      '    如果 (等待任务(删除任务) == 0)',
      '        调试输出("Cookie链路失败=删除超时")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("Cookie链路=删除结果：", CEF3任务_取结果(删除任务))',
      '    CEF3任务_释放(删除任务)',
      '    返回(1)',
      '结束',
      '',
      '// 阶段标记 1=应有 Cookie，0=应已删除；页面正文全文输出到面板，由录制断言核对。',
      '整数型 验证Cookie页面()',
      '    局部 长整数型 框架 = CEF3框架_取主框架(浏览器1)',
      '    如果 (框架 == 0)',
      '        调试输出("Cookie链路失败=主框架为空")',
      '        返回(0)',
      '    如果结束',
      '    局部 长整数型 文本任务 = CEF3框架_取文本异步(框架)',
      '    如果 (等待任务(文本任务) == 1)',
      '        调试输出("Cookie链路=页面文本（应包含=" + 到文本(应包含标记) + "）：", CEF3任务_取结果(文本任务))',
      '    如果结束',
      '    CEF3任务_释放(文本任务)',
      '    CEF3框架_释放(框架)',
      '    返回(1)',
      '结束',
      '',
      '// 手动按钮：单步重放各环节，方便录制分镜。',
      '事件 _写入Cookie按钮_被单击()',
      '    写入Cookie()',
      '    控件_设置文本(状态标签, "已写入 Cookie，点「刷新页面」查看")',
      '结束',
      '',
      '事件 _读取Cookie按钮_被单击()',
      '    读取并输出Cookie()',
      '结束',
      '',
      '事件 _落盘按钮_被单击()',
      '    落盘Cookie()',
      '    控件_设置文本(状态标签, "Cookie 已落盘到独立缓存目录")',
      '结束',
      '',
      '事件 _删除Cookie按钮_被单击()',
      '    删除Cookie()',
      '    控件_设置文本(状态标签, "已删除 Cookie，点「刷新页面」确认消失")',
      '结束',
      '',
      '事件 _重新加载按钮_被单击()',
      '    CEF3_导航(浏览器1, "http://127.0.0.1:18080/cookie-page")',
      '结束',
      '',
      '整数型 等待任务(长整数型 任务ID)',
      '    局部 整数型 状态 = 0',
      '    局部 整数型 轮询 = 0',
      '    计次循环首 (1000000, 轮询)',
      '        状态 = CEF3任务_取状态(任务ID)',
      '        如果 (状态 == 2)',
      '            返回(1)',
      '        如果结束',
      '        如果 (状态 < 0)',
      '            返回(0)',
      '        如果结束',
      '    计次循环尾',
      '    返回(0)',
      '结束'
    ],
    assets: [['assets/cookie-page.html', [
      '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Cookie 演示页</title>',
      '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:36px}',
      'main{max-width:640px;margin:auto;background:#fff;border-left:6px solid #7C3AED;padding:24px 28px;border-radius:8px}',
      '#c{color:#7C3AED;font-weight:700;white-space:pre-wrap}</style>',
      '<main><h2>Cookie 演示页（127.0.0.1:18080）</h2>',
      '<p>本页由示例内置 HTTP 服务端提供；原生侧通过会话上下文管理本站 Cookie。</p>',
      '<p id="c">本页尚未显示 Cookie。</p>',
      '<script>document.getElementById("c").textContent="当前 document.cookie = [" + document.cookie + "]";</script>',
      '</main></html>'
    ].join('')]],
    boundaries: [
      'file:// 页面没有 Cookie：演示用内置 HTTP 服务端（lingbuilder.http.server 模块）在 127.0.0.1:18080 起真实 HTTP 演示页，端口被占用时 HTTP_启动 返回失败并给中文诊断。',
      '静态文件路由的路径相对 exe 工作目录解析：assets/cookie-page.html 随构建产物部署在 bin/assets/ 下。',
      'Cookie 命令全部需要会话上下文句柄：设计器控件用 CEF3会话_取上下文，代码创建实例用 CEF3会话_取上下文实例；用完 CEF3会话_释放上下文。',
      'Cookie 设置/读取/删除/落盘都是异步命令：返回任务句柄，CEF3任务_取状态 完成态=2，读完必须释放。',
      '过期 Unix 秒传 0 或负数=会话 Cookie（不落盘）；示例传固定将来时间戳 4102444800（2100 年）造持久 Cookie。',
      '会话上下文要等浏览器对象创建完成之后才能取（「加载完成」之后最稳），创建完毕事件里调用可能失败。',
      'HTTP_允许外部监听 默认关闭，服务只绑回环地址；演示页只服务本机浏览器。'
    ],
    steps: [
      'S2：讲解会话模型图版：RequestContext = 缓存 + Cookie + 首选项的边界。',
      'S3：说明为什么必须 HTTP：file:// 没有 Cookie；内置 HTTP 服务端 3 行起服务。',
      'S4：F5 自动链：浏览器打开 127.0.0.1:18080/cookie-page，页面显示 document.cookie 已带教程 Cookie。',
      'S5：特写输出面板：写入结果、按地址读取 JSON、落盘完成。',
      'S6：自动删除并重新加载：页面 Cookie 消失（花字「删除 → 复查」）。',
      'S7：手动按钮逐个演示单步重放；口播提示 清理HTTP缓存/清理HTTP认证 等同族命令。'
    ]
  },
  {
    no: '19',
    dir: '19 模拟输入与用户代理',
    id: 'cef3-ep19-input-ua',
    name: 'CEF3 模拟输入演练',
    className: 'CEF3输入演练窗体',
    title: 'CEF3 模拟输入 · 鼠标/键盘事件与逐实例 UA',
    commands: ['CEF3_设置用户代理', 'CEF3_取用户代理', 'CEF3_发送鼠标移动事件', 'CEF3_发送鼠标单击事件', 'CEF3_发送鼠标滚轮事件', 'CEF3_发送按键事件', 'CEF3框架_取主框架', 'CEF3框架_取文本异步', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_释放', 'CEF3_执行JS'],
    globals: ['全局 整数型 UA编号 = 1', '全局 长整数型 框架句柄 = 0', '全局 长整数型 读取任务ID = 0', '全局 整数型 读取轮次 = 0', '全局 整数型 门控重查轮次 = 0'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.automation', 'lingbuilder.cef3.objects', 'lingbuilder.threading'],
    controls: [
      button('replay-button', '重放输入按钮', '重放模拟输入', 10, 10, 140),
      button('ua-button', '切换UA按钮', '换一个 UA', 158, 10, 120),
      label('status', '状态标签', '等待演练开始……', 286, 10, 794, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep19', enableJs: true })
    ],
    code: [
      '// 模拟输入走 CEF 原生输入链路：鼠标/滚轮坐标相对浏览器视图左上角，与页面坐标一致。',
      '// 逐实例 UA 在「资源加载前」改写请求头：必须在导航之前设置，才对首个页面生效。',
      '// 读取页面结果的任务轮询在工作线程里做（协作等待真休眠），UI 线程只发命令收结果。',
      '事件 _CEF3输入演练窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    CEF3_设置用户代理(浏览器1, "Mozilla/5.0 (LingBuilder教程UA/1.0)")',
      '    调试输出("输入链路=UA已设置：", CEF3_取用户代理(浏览器1))',
      '    局部 文本型 页面地址 = CEF3_取资源地址("input.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    调试输出("输入链路=加载完成触发 标题：", CEF3_取标题(浏览器1))',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 输入演示页-就绪")',
      '        输入入口()',
      '    否则',
      '        如果 (CEF3_取标题(浏览器1) == "CEF3 输入演示页")',
      '            门控重查轮次 = 0',
      '            线程_提交完成(&门控等待工作, &门控等待完成)',
      '        如果结束',
      '    如果结束',
      '结束',
      '',
      '整数型 输入入口()',
      '        控件_设置文本(状态标签, "页面就绪：先设 UA，再重放模拟输入")',
      '        调试输出("输入链路=页面UA信封：", CEF3_执行JS(浏览器1, "navigator.userAgent"))',
      '        输入注入()',
      '        开始读取页面文本()',
      '    返回(1)',
      '结束',
      '',
      '// 工作处理器只做纯等待；标题重查放回界面线程。',
      '整数型 门控等待工作()',
      '    线程_协作等待(500)',
      '    返回(0)',
      '结束',
      '',
      '空 门控等待完成(线程任务 任务, 整数型 结果)',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 输入演示页-就绪")',
      '        输入入口()',
      '        返回()',
      '    如果结束',
      '    门控重查轮次 = 门控重查轮次 + 1',
      '    如果 (门控重查轮次 < 12)',
      '        线程_提交完成(&门控等待工作, &门控等待完成)',
      '        返回()',
      '    如果结束',
      '    调试输出("输入链路失败=页面迟迟未就绪")',
      '结束',
      '',
      '事件 _重放输入按钮_被单击()',
      '    读取轮次 = 0',
      '    输入注入()',
      '    开始读取页面文本()',
      '结束',
      '',
      '// UA 置空=清除覆盖，回落 Chromium 默认 UA。',
      '事件 _切换UA按钮_被单击()',
      '    UA编号 = UA编号 + 1',
      '    CEF3_设置用户代理(浏览器1, "Mozilla/5.0 (LingBuilder教程UA/" + 到文本(UA编号) + ".0)")',
      '    调试输出("输入链路=UA已切换：", CEF3_取用户代理(浏览器1))',
      '    CEF3_刷新(浏览器1)',
      '    控件_设置文本(状态标签, "UA 已切换并刷新，页面 UA 信封见输出")',
      '结束',
      '',
      '整数型 输入注入()',
      '    // 单击输入框获得焦点：坐标相对浏览器视图左上角（输入框在页面左上角）。',
      '    CEF3_发送鼠标移动事件(浏览器1, 100, 34, 0, 假)',
      '    CEF3_发送鼠标单击事件(浏览器1, 100, 34, 0, 0, 假, 1)',
      '    CEF3_发送鼠标单击事件(浏览器1, 100, 34, 0, 0, 真, 1)',
      '    调试输出("输入链路=已单击输入框")',
"    // 字符输入：类型 1=按下触发页面 keydown 计数，类型 3=字符事件写入文本（L=76、B=66）。",
      '    CEF3_发送按键事件(浏览器1, 1, 0, 76, 76, 假, 76, 76, 真)',
      '    CEF3_发送按键事件(浏览器1, 3, 0, 76, 76, 假, 76, 76, 假)',
      '    CEF3_发送按键事件(浏览器1, 1, 0, 66, 66, 假, 66, 66, 真)',
      '    CEF3_发送按键事件(浏览器1, 3, 0, 66, 66, 假, 66, 66, 假)',
      '    // 回车：类型 1=按下、2=松开，Windows 键码 13。',
      '    CEF3_发送按键事件(浏览器1, 1, 0, 13, 13, 假, 13, 13, 真)',
      '    CEF3_发送按键事件(浏览器1, 2, 0, 13, 13, 假, 13, 13, 真)',
      '    调试输出("输入链路=已输入字符并回车")',
      '    // 单击热区（页面绝对坐标 20,120 尺寸 220×64 的中心）。',
      '    CEF3_发送鼠标移动事件(浏览器1, 130, 152, 0, 假)',
      '    CEF3_发送鼠标单击事件(浏览器1, 130, 152, 0, 0, 假, 1)',
      '    CEF3_发送鼠标单击事件(浏览器1, 130, 152, 0, 0, 真, 1)',
      '    调试输出("输入链路=已单击热区")',
      '    // 滚轮：纵向增量为负向下滚（Windows 滚轮一格 ±120）。',
      '    CEF3_发送鼠标滚轮事件(浏览器1, 130, 300, 0, 0, -120)',
      '    调试输出("输入链路=已滚动滚轮")',
      '    返回(1)',
      '结束',
      '',
      '整数型 开始读取页面文本()',
      '    框架句柄 = CEF3框架_取主框架(浏览器1)',
      '    如果 (框架句柄 == 0)',
      '        调试输出("输入链路失败=主框架为空")',
      '        返回(0)',
      '    如果结束',
      '    读取任务ID = CEF3框架_取文本异步(框架句柄)',
      '    线程_提交完成(&输入读取工作, &输入读取完成)',
      '    返回(1)',
      '结束',
      '',
      '整数型 输入读取工作()',
      '    局部 整数型 状态 = 0',
      '    局部 整数型 状态轮询 = 0',
      '    计次循环首 (100, 状态轮询)',
      '        状态 = CEF3任务_取状态(读取任务ID)',
      '        如果 (状态 == 2)',
      '            跳出循环',
      '        如果结束',
      '        如果 (状态 < 0)',
      '            跳出循环',
      '        如果结束',
      '        线程_协作等待(50)',
      '    计次循环尾',
      '    返回(状态)',
      '结束',
      '',
      '空 输入读取完成(线程任务 任务, 整数型 状态)',
      '    局部 文本型 页面文本 = ""',
      '    如果 (状态 == 2)',
      '        页面文本 = CEF3任务_取结果(读取任务ID)',
      '    如果结束',
      '    CEF3任务_释放(读取任务ID)',
      '    调试输出("输入链路=页面文本：", 页面文本)',
      '    // 页面在「3 次按键 + 热区单击」齐活后把标题改成 -已送达：标题等值判断。',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 输入演示页-已送达")',
      '        CEF3框架_释放(框架句柄)',
      '        控件_设置文本(状态标签, "模拟输入演练完成：单击/字符/回车/滚轮 全部送达")',
      '        调试输出("输入链路全部通过")',
      '        返回()',
      '    如果结束',
      '    // 渲染进程偶发重启会丢一次读取/输入：整链重放（最多 3 轮）。',
      '    读取轮次 = 读取轮次 + 1',
      '    如果 (读取轮次 < 3)',
      '        输入注入()',
      '        开始读取页面文本()',
      '        控件_设置文本(状态标签, "页面尚未就绪，第 " + 到文本(读取轮次) + " 轮重放……")',
      '        返回()',
      '    如果结束',
      '    调试输出("输入链路失败=页面文本读取为空")',
      '结束',
    ],
    assets: [['assets/input.html', [
      '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 输入演示页</title>',
      '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:24px}',
      'input{padding:8px;border:1px solid #cbd5e1;border-radius:6px;width:240px}',
      '#pad{margin-top:60px;width:220px;height:64px;line-height:64px;text-align:center;background:#dbeafe;border-radius:10px}',
      '#scroll-box{margin-top:24px;height:140px;overflow-y:auto;border:1px solid #94a3b8;border-radius:8px;padding:10px;max-width:420px}',
      '#state{color:#2563EB;font-weight:700;margin-top:10px}</style>',
      '<main><h3>CEF3 模拟输入演示页</h3>',
      '<input id="name-input" placeholder="点我获得焦点"><span id="key-count" style="margin-left:10px;color:#64748b">已收到按键事件：0</span>',
      '<div id="pad">模拟单击热区</div>',
      '<div id="scroll-box"><p>滚动区域第 1 行</p><p>滚动区域第 2 行</p><p>滚动区域第 3 行</p><p>滚动区域第 4 行</p><p>滚动区域第 5 行</p><p>滚动区域第 6 行</p></div>',
      '<div id="state">等待模拟输入……</div>',
      '<p>当前 UA（navigator.userAgent）见 IDE 输出面板。</p>',
      '<script>const i=document.getElementById("name-input");let k=0;',
      'i.addEventListener("keydown",()=>{k++;document.getElementById("key-count").textContent="已收到按键事件："+k;',
      'if(k>=3){document.getElementById("state").textContent="输入链路已送达：字符×2 + 回车";}});',
      'document.getElementById("pad").addEventListener("click",function(){this.textContent="已被模拟单击";});</script></main></html>'
    ].join('')]],
    boundaries: [
      '鼠标/滚轮坐标相对浏览器视图左上角（不是窗口客户区）；控件在窗口 (10,52)，所以页面坐标 = 视口坐标。',
      '字符输入用事件类型 3（字符），字符编码是 UTF-16 码位；按下/松开用类型 1/2 配合 Windows 键码（回车 13）。',
      '逐实例 UA 在「资源加载前」事件里改写请求头：必须在导航之前调用 CEF3_设置用户代理 才对首个页面生效；置空=清除覆盖。',
      'CEF3_设置代理 是创建前命令：设计器实例的代理走控件属性「代理模式/自定义代理地址」（第 05 集已拍），本集只演示 UA。',
      '执行JS 返回 JSON 信封（{"result":{"value":…}}），页面 UA 断言按信封内容核对。',
      '触摸事件（CEF3_发送触摸事件）只对无窗口/OSR 浏览器生效，普通控件实例不演示。'
    ],
    steps: [
      'S2：F5 后先看输出面板 UA 信封：页面拿到的 navigator.userAgent 已是自定义 UA（花字「请求头级伪装」）。',
      'S3：自动链单击输入框 → 输入 L、B → 回车；特写页面按键计数从 0 变 3。',
      'S4：特写「模拟单击热区」文字变为「已被模拟单击」。',
      'S5：滚轮滚动滚动区域；说明 ±120 一格与坐标口径。',
      'S6：点「换一个 UA」刷新页面，再看 UA 信封变化。',
      'S7：口播边界：触摸事件属 OSR 链路；代理是创建前属性（指回第 05 集）。'
    ]
  },
  {
    no: '20',
    dir: '20 弹窗管理',
    id: 'cef3-ep20-popup',
    name: 'CEF3 弹窗管理演练',
    className: 'CEF3弹窗演练窗体',
    title: 'CEF3 弹窗管理 · 新窗口打开前事件接管',
    commands: ['CEF3_绑定事件', 'CEF3_取事件字段', 'CEF3_设置事件结果', 'CEF3_取资源地址', 'CEF3_导航', 'CEF3_刷新'],
    modules: ['lingbuilder.cef3.browser'],
    controls: [
      button('toggle-button', '切换拦截按钮', '切换拦截开关', 10, 10, 140),
      button('again-button', '重新发起按钮', '重新发起弹窗', 158, 10, 140),
      label('status', '状态标签', '等待演练开始……', 306, 10, 774, 32),
      browser('browser-1', '浏览器1', 10, 52, 1070, 660, { url: 'about:blank', cacheDir: '.cef3/ep20' })
    ],
    globals: ['全局 整数型 拦截弹窗 = 1'],
    code: [
      '// 「新窗口打开前」是同步决策事件：处理器里必须用 CEF3_设置事件结果 给出裁决，',
      '// 0=默认行为、1=允许、2=拒绝、3=已处理；不放行也不拒绝时 CEF 走默认弹窗流程。',
      '事件 _CEF3弹窗演练窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "新窗口打开前", &新窗口打开前)',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    局部 文本型 页面地址 = CEF3_取资源地址("popup-opener.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 弹窗发起页")',
      '        控件_设置文本(状态标签, "页面就绪：即将模拟点击「发起弹窗」（" + 拦截状态文本() + "）")',
      '        调试输出("弹窗链路=发起页已加载，模拟用户点击……")',
      '        // 脚本弹窗没有用户手势会被 Chromium 弹窗拦截器吞掉：注入真实鼠标点击按钮。',
      '        局部 文本型 空转标题 = ""',
      '        局部 整数型 让渡轮询 = 0',
      '        计次循环首 (1000000, 让渡轮询)',
      '            空转标题 = CEF3_取标题(浏览器1)',
      '        计次循环尾',
      '        CEF3_发送鼠标移动事件(浏览器1, 100, 38, 0, 假)',
      '        CEF3_发送鼠标单击事件(浏览器1, 100, 38, 0, 0, 假, 1)',
      '        CEF3_发送鼠标单击事件(浏览器1, 100, 38, 0, 0, 真, 1)',
      '        调试输出("弹窗链路=已模拟点击「发起弹窗」按钮")',
      '    如果结束',
      '结束',
      '',
      '文本型 拦截状态文本()',
      '    如果 (拦截弹窗 == 1)',
      '        返回("拦截=开")',
      '    如果结束',
      '    返回("拦截=关")',
      '结束',
      '',
      '事件 新窗口打开前()',
      '    局部 文本型 目标地址 = CEF3_取事件字段(浏览器1, "url")',
      '    调试输出("弹窗链路=弹窗请求地址：", 目标地址)',
      '    如果 (拦截弹窗 == 1)',
      '        CEF3_设置事件结果(浏览器1, 2)',
      '        控件_设置文本(状态标签, "已拦截弹窗：" + 目标地址)',
      '        调试输出("弹窗链路=已拦截 结果=2")',
      '        调试输出("弹窗链路全部通过")',
      '    否则',
      '        CEF3_设置事件结果(浏览器1, 1)',
      '        控件_设置文本(状态标签, "已放行弹窗（独立 CEF 弹窗窗口）：" + 目标地址)',
      '        调试输出("弹窗链路=已放行 结果=1")',
      '    如果结束',
      '结束',
      '',
      '事件 _切换拦截按钮_被单击()',
      '    拦截弹窗 = 1 - 拦截弹窗',
      '    控件_设置文本(状态标签, "拦截开关已切换：" + 拦截状态文本())',
      '    调试输出("弹窗链路=拦截开关：", 拦截弹窗)',
      '结束',
      '',
      '// 重新导航发起页，再点一次页面按钮即可重拍弹窗分镜。',
      '事件 _重新发起按钮_被单击()',
      '    局部 文本型 页面地址 = CEF3_取资源地址("popup-opener.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束'
    ],
    assets: [
      ['assets/popup-opener.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 弹窗发起页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:96px 40px 40px}',
        'button{padding:12px 28px;background:#2563EB;color:#fff;border:0;border-radius:8px;font-size:16px}',
        '#open-btn{position:absolute;left:20px;top:16px;width:170px;height:44px}</style>',
        '<h2>CEF3 弹窗发起页</h2><p>点按钮发起弹窗：原生侧在「新窗口打开前」事件里裁决放行还是拦截。</p>',
        '<button id="open-btn" onclick="window.open(\'popup-child.html\',\'_blank\',\'width=420,height=320\')">发起弹窗</button>',
        '</html>'
      ].join('')],
      ['assets/popup-child.html', [
        '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 弹窗子页</title>',
        '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#ecfdf5;color:#065f46;padding:32px}</style>',
        '<h3>弹窗子页已打开</h3><p>这个独立窗口由 CEF 弹窗流程创建，可被宿主接管或拦截。</p></html>'
      ].join('')]
    ],
    boundaries: [
      '「新窗口打开前」是同步决策事件：不调用 CEF3_设置事件结果 时走 CEF 默认弹窗流程；结果 2=拒绝（什么都不出现）、1=允许继续默认流程。',
      '被放行的弹窗是独立 CEF 弹窗窗口，不是设计器控件，没有控件名；弹窗浏览器要用 打开者浏览器ID/是否弹出窗口 这类命令在 CEF 内部链路里识别。',
      '自动链由 CEF 注入鼠标事件点击页面按钮：脚本弹窗没有用户手势会被 Chromium 弹窗拦截器吞掉，这条红线口播要点出；点「切换拦截开关」后再点「重新发起弹窗」对比拦截与放行。',
      '页面脚本 window.open 写在 HTML 资源文件里，.lcpp 字符串里不写带括号的 JS（会被语言服务误判功能库调用）。'
    ],
    steps: [
      'S2：概念图版：弹窗三选择「放行 / 拦截 / 接管」与事件结果码 0/1/2/3。',
      'S3：F5 后自动模拟点击「发起弹窗」→ 弹窗被拦截：状态标签显示弹窗地址，输出面板出现 弹窗链路=已拦截。',
      'S4：点「切换拦截开关」→「重新发起弹窗」：CEF 独立弹窗窗口出现（花字「放行」）。',
      'S5：特写 取事件字段("url") 与 设置事件结果 两行代码，强调这是同步决策。',
      'S6：口播：接管弹窗（结果 3 + 自建窗口承载）是进阶玩法，本集点到为止。'
    ]
  },
  {
    no: '21',
    dir: '21 DevTools订阅与受管流',
    id: 'cef3-ep21-devtools-stream',
    name: 'CEF3 高级专题演练',
    className: 'CEF3高级专题窗体',
    title: 'CEF3 高级专题 · DevTools 协议订阅与受管流',
    commands: ['CEF3开发工具_订阅协议事件', 'CEF3开发工具_执行协议方法', 'CEF3_取事件字段', 'CEF3任务_取状态', 'CEF3任务_取结果', 'CEF3任务_释放', 'CEF3缓冲_从十六进制', 'CEF3缓冲_取大小', 'CEF3缓冲_到十六进制', 'CEF3缓冲_释放', 'CEF3传输_从文件创建写入流', 'CEF3传输_写入流', 'CEF3传输_刷新写入流', 'CEF3传输_释放写入流', 'CEF3传输_从文件创建读取流', 'CEF3传输_读取流', 'CEF3传输_释放读取流'],
    modules: ['lingbuilder.cef3.browser', 'lingbuilder.cef3.devtools', 'lingbuilder.cef3.transfer', 'lingbuilder.cef3.objects'],
    controls: [
      button('demo-button', '一键演练按钮', '一键高级演练', 10, 10, 140),
      button('write-button', '写入流按钮', '写文件流', 10, 52, 140),
      button('read-button', '读取流按钮', '读文件流', 10, 94, 140),
      label('status', '状态标签', '等待演练开始……', 160, 10, 380, 32),
      label('event', '事件标签', '协议事件：尚未收到', 160, 48, 380, 60),
      browser('browser-1', '浏览器1', 10, 136, 530, 560, { url: 'about:blank', cacheDir: '.cef3/ep21', enableDevTools: true }),
      label('hint', '提示标签', '右侧输出：受管流与受管缓冲的每一步结果', 556, 136, 520, 560, { properties: { staticStyle: 'text', textAlign: 'left' } })
    ],
    code: [
      '// 本集是合集的「高级专题」：DevTools 协议订阅（观察页面事件流）+ 受管流/受管缓冲（二进制读写）。',
      '// 订阅是开关：CEF3开发工具_订阅协议事件(控件, 真) 之后，协议事件才会投递为浏览器事件。',
      '事件 _CEF3高级专题窗体_创建完毕()',
      '    CEF3_绑定事件(浏览器1, "加载完成", &页面加载完成)',
      '    CEF3_绑定事件(浏览器1, "开发工具协议事件", &协议事件到达)',
      '    CEF3开发工具_订阅协议事件(浏览器1, 真)',
      '    局部 文本型 页面地址 = CEF3_取资源地址("devtools-page.html")',
      '    CEF3_导航(浏览器1, 页面地址)',
      '结束',
      '',
      '// 协议事件字段：method=事件方法名，paramsJson=参数 JSON（超过 1MiB 会截断并给 truncated 标记）。',
      '事件 协议事件到达()',
      '    局部 文本型 方法名 = CEF3_取事件字段(浏览器1, "method")',
      '    调试输出("高级链路=协议事件：", 方法名, " 参数：", CEF3_取事件字段(浏览器1, "paramsJson"))',
      '    控件_设置文本(事件标签, "协议事件：" + 方法名)',
      '结束',
      '',
      '事件 页面加载完成()',
      '    如果 (CEF3_取标题(浏览器1) == "CEF3 DevTools 观察页")',
      '        控件_设置文本(状态标签, "页面就绪：开始高级演练")',
      '        高级演练()',
      '    如果结束',
      '结束',
      '',
      '事件 _一键演练按钮_被单击()',
      '    高级演练()',
      '结束',
      '',
      '事件 _写入流按钮_被单击()',
      '    写入演练流()',
      '结束',
      '',
      '事件 _读取流按钮_被单击()',
      '    读取演练流()',
      '结束',
      '',
      '整数型 高级演练()',
      '    // 1) 协议方法：Runtime.enable 是审查过的安全方法，返回任务句柄。',
      '    局部 长整数型 方法任务 = CEF3开发工具_执行协议方法(浏览器1, "Runtime.enable", "{}")',
      '    如果 (等待任务(方法任务) == 0)',
      '        调试输出("高级链路失败=Runtime.enable 超时")',
      '        返回(0)',
      '    如果结束',
      '    调试输出("高级链路=Runtime.enable 结果：", CEF3任务_取结果(方法任务))',
      '    CEF3任务_释放(方法任务)',
      '    方法任务 = CEF3开发工具_执行协议方法(浏览器1, "Page.enable", "{}")',
      '    如果 (等待任务(方法任务) == 1)',
      '        调试输出("高级链路=Page.enable 结果：", CEF3任务_取结果(方法任务))',
      '    如果结束',
      '    CEF3任务_释放(方法任务)',
      '    调试输出("高级链路=协议方法完成")',
      '    // 2) 受管流：写 8 字节到工作区文件，再读回来逐字节核对。',
      '    如果 (写入演练流() == 0)',
      '        返回(0)',
      '    如果结束',
      '    如果 (读取演练流() == 0)',
      '        返回(0)',
      '    如果结束',
      '    控件_设置文本(状态标签, "高级演练完成：协议方法 + 受管流 + 受管缓冲")',
      '    调试输出("高级链路全部通过")',
      '    返回(1)',
      '结束',
      '',
      '整数型 写入演练流()',
      '    局部 长整数型 数据缓冲 = CEF3缓冲_从十六进制("4c42440001020304")',
      '    如果 (数据缓冲 == 0)',
      '        调试输出("高级链路失败=缓冲创建失败")',
      '        返回(0)',
      '    如果结束',
      '    局部 长整数型 缓冲大小 = CEF3缓冲_取大小(数据缓冲)',
      '    调试输出("高级链路=缓冲大小：", 缓冲大小)',
      '    局部 CEF3写入流句柄 写入流 = CEF3传输_从文件创建写入流("cef3-ep21-demo.bin")',
      '    如果 (写入流 == 0)',
      '        调试输出("高级链路失败=写入流创建失败")',
      '        CEF3缓冲_释放(数据缓冲)',
      '        返回(0)',
      '    如果结束',
      '    局部 长整数型 已写入 = CEF3传输_写入流(写入流, 数据缓冲, 0, 缓冲大小)',
      '    调试输出("高级链路=写入字节数：", 已写入)',
      '    CEF3传输_刷新写入流(写入流)',
      '    CEF3传输_释放写入流(写入流)',
      '    CEF3缓冲_释放(数据缓冲)',
      '    控件_设置文本(状态标签, "已写入 exe 同级 cef3-ep21-demo.bin（8 字节）")',
      '    返回(1)',
      '结束',
      '',
      '整数型 读取演练流()',
      '    局部 CEF3读取流句柄 读取流 = CEF3传输_从文件创建读取流("cef3-ep21-demo.bin")',
      '    如果 (读取流 == 0)',
      '        调试输出("高级链路失败=读取流创建失败（先执行写入）")',
      '        返回(0)',
      '    如果结束',
      '    局部 长整数型 读回缓冲 = CEF3传输_读取流(读取流, 64)',
      '    局部 长整数型 读回大小 = CEF3缓冲_取大小(读回缓冲)',
      '    调试输出("高级链路=读回字节数：", 读回大小)',
      '    调试输出("高级链路=读回十六进制：", CEF3缓冲_到十六进制(读回缓冲))',
      '    CEF3缓冲_释放(读回缓冲)',
      '    CEF3传输_释放读取流(读取流)',
      '    控件_设置文本(状态标签, "已读回并核对：4c42440001020304")',
      '    返回(1)',
      '结束',
      '',
      '整数型 等待任务(长整数型 任务ID)',
      '    局部 整数型 状态 = 0',
      '    局部 整数型 轮询 = 0',
      '    计次循环首 (1000000, 轮询)',
      '        状态 = CEF3任务_取状态(任务ID)',
      '        如果 (状态 == 2)',
      '            返回(1)',
      '        如果结束',
      '        如果 (状态 < 0)',
      '            返回(0)',
      '        如果结束',
      '    计次循环尾',
      '    返回(0)',
      '结束'
    ],
    assets: [['assets/devtools-page.html', [
      '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>CEF3 DevTools 观察页</title>',
      '<style>body{font-family:"Microsoft YaHei UI",sans-serif;background:#f8fafc;color:#0f172a;padding:32px}</style>',
      '<h3>CEF3 DevTools 观察页</h3><p>本页保持简单稳定，供协议订阅与协议方法演示。</p>',
      '<p id="tick">页面已就绪。</p></html>'
    ].join('')]],
    boundaries: [
      '订阅是开关：CEF3开发工具_订阅协议事件(控件, 真) 之后协议事件才投递为浏览器事件；字段 method/paramsJson，paramsJson 超过 1MiB 截断并带 truncated 标记。',
      '协议事件是否流动取决于 CEF 内部协议活动，演示里 Page.enable + 重新导航最容易观察到 Page.frame* 事件；事件不到达不影响受管流断言。',
      '执行协议方法 的参数必须是 JSON 对象文本；返回任务句柄，结果用 CEF3任务_取结果 读取。',
      '受管流/缓冲的允许文件根目录=exe 同级目录：示例直接写 cef3-ep21-demo.bin；子目录需已存在，越界路径返回 0。',
      '受管句柄（流/缓冲/任务）读完即释放；缓冲_到十六进制 输出小写十六进制。',
      '设计器要允许开发者工具（控件属性 enableDevTools），否则 CEF3开发工具_打开 返回 0。'
    ],
    steps: [
      'S2：概念图版：DevTools 协议 = CDP；受管流 = CEF 官方 CefStreamReader/Writer 的受管版。',
      'S3：F5 自动演练：特写 Runtime.enable / Page.enable 任务结果 JSON。',
      'S4：协议事件到达时事件标签滚动（观察性镜头，不强求特定事件名）。',
      'S5：特写受管流：写 8 字节 → 读回 → 十六进制逐字节一致（花字「二进制安全」）。',
      'S6：点「写文件流」「读文件流」单步重放；口播：写入处理器/读取处理器族是同一底座的回调形态。'
    ]
  }
];

const episodes: Episode[] = [...episodesWave1, ...episodesWave2];

const solutionOf = (item: Episode) => ({
  schemaVersion: 2,
  id: `${item.id}-solution`,
  name: item.name,
  startupProjectId: item.id,
  startupProjectIds: [item.id],
  folders: [],
  projects: [{
    type: 'visual-cpp',
    id: item.id,
    name: item.name,
    sourceRoot: 'src',
    configRoot: 'config',
    designerPath: '.lingbuilder/window-designer.json',
    isDefault: true,
    references: []
  }]
});

const modulesOf = (item: Episode) => ({
  schemaVersion: 1,
  enabledModuleIds: [BASIC, ...item.modules],
  pinnedVersions: Object.fromEntries([
    [BASIC, '1.0.0'],
    ...item.modules.map(id => [id, MODULE_PINS[id] ?? CEF3_VERSION])
  ])
});

const designerOf = (item: Episode) => ({
  schemaVersion: 2,
  id: item.id,
  name: item.name,
  resources: item.resources ?? [],
  windows: [{
    id: 'main-window',
    fileName: `${item.className}.xml`,
    className: item.className,
    title: item.title,
    width: 1100,
    height: 760,
    background: '#111827',
    description: `${item.name}（CEF3 合集第 ${item.no} 集）。`,
    designerBackend: 'win32',
    openPlacement: 'center',
    titleBarBackground: '#1E293B',
    titleBarForeground: '#E2E8F0',
    borderStyle: 'normal-resizable',
    resizable: true,
    maximizable: true,
    events: { Loaded: `_${item.className}_创建完毕` },
    controls: item.controls,
    ...item.window
  }]
});

const sourceOf = (item: Episode) => [
  `包 CEF3教程第${item.no}集`,
  '使用 Win32窗口基础模块',
  '使用 CEF3浏览器模块',
  '',
  `类 ${item.className} : 窗口`,
  '公开',
  '  构造()',
  '  结束',
  '',
  ...item.code.map(line => (line ? `  ${line}` : '')),
  '结束类',
  '',
  `// 本集口播命令：${item.commands.join('、')}`,
  ''
].join('\n');

const buildRequestOf = (item: Episode) => ({
  project: {
    schemaVersion: 2,
    id: item.id,
    name: item.name,
    resources: item.resources ?? [],
    windows: designerOf(item).windows
  },
  activeWindowId: 'main-window',
  // 不写 lingCppSourceFilePath：CLI 一旦收到它就只会把这一个文件当作权威源码集合，
  // 项目全局变量.lcpp 会被排除在聚合之外。留空则由服务扫描 sourceRoot 下的全部 .lcpp。
  run: false,
  approved: true
});

const projectRelativePath = (item: Episode) => `AI 视频自主生产/CEF3 浏览器模块合集/${item.dir}/示例项目/${item.id}`;

const readmeOf = (item: Episode) => [
  `# ${item.name}`,
  '',
  `对应 CEF3 浏览器模块合集第 ${item.no} 集《${item.title}》。`,
  '',
  '## 打开与运行',
  '',
  '1. 把 `示例项目/` 下的整个项目文件夹复制到一个纯 ASCII 路径的工作区（例如 `D:\\lb-demo\\`）。',
  '2. 在 LingBuilder 中打开 `.lingbuilder/solution.json`。',
  '3. 确认模块面板已启用：' + [BASIC, ...item.modules].map(id => `\`${id}\``).join('、') + '。',
  '4. 按 F5 构建运行，确认错误列表为 0。',
  '',
  '## 本集命令',
  '',
  ...item.commands.map(command => `- \`${command}\``),
  '',
  '## 运行边界',
  '',
  ...item.boundaries.map(text => `- ${text}`),
  '',
  '## 前置条件',
  '',
  '- Windows x64 + Visual Studio / MSVC 工具链。',
  '- 已安装并通过 SHA-256 校验的 `lingbuilder.cef3.sdk`。',
  '- 构建产物 `bin/` 目录需包含 `libcef.dll`、`chrome_elf.dll`、`LingBuilderCefBridge.dll`、`resources.pak`、`icudtl.dat` 与 `locales/` 等 CEF 运行时资源。',
  '',
  '## 命令行构建',
  '',
  '每个示例项目本身就是一个工作区，需要能找到已安装的 CEF3 SDK（`.lingbuilder/modules`）。',
  '仓库提供的构建脚本会把项目复制到 `.tmp-cef3-verify/` 再构建，顺带用目录联接共享 SDK，',
  '并且把体积很大的构建产物挡在示例目录之外：',
  '',
  '```powershell',
  'cd electron',
  'npm run build:cli',
  'npm run tutorial:cef3:build',
  '```',
  '',
  '也可以原地构建（路径含中文没有影响，实测通过），只要先把 SDK 联接进本项目工作区：',
  '',
  '```powershell',
  `cd "<本项目目录>/.lingbuilder"`,
  'cmd /c mklink /J modules T:\electron\lingbuilder\.lingbuilder\modules',
  'cd T:\electron\lingbuilder\electron',
  `node dist/cli.cjs project build --request "<本项目目录>/build-request.json" --workspace "<本项目目录>" --yes --json`,
  '```',
  '',
  '> mklink 的目标路径不要加引号，加了会生成一个坏联接。',
  '',
  '> `build-request.json` 刻意不写 `lingCppSourceFilePath`：一旦写了，CLI 只会把那一个文件当作权威源码，`src/项目全局变量.lcpp` 不会参与聚合。',
  ''
].join('\n');

const recordingOf = (item: Episode) => [
  `# 第 ${item.no} 集录制准备：${item.title}`,
  '',
  '## 项目入口',
  '',
  `- 示例项目：\`示例项目/${item.id}/\``,
  `- 解决方案：\`示例项目/${item.id}/.lingbuilder/solution.json\``,
  `- 项目 ID：\`${item.id}\``,
  `- 窗体类：\`${item.className}\`，源码 \`src/${item.className}.lcpp\``,
  '',
  '## 录制前置',
  '',
  '- Windows x64、Visual Studio / MSVC 工具链已就绪。',
  '- `lingbuilder.cef3.sdk` 已安装并校验通过；SDK 下载对话框镜头单独在干净缓存环境录制后复用。',
  `- 已启用模块：${[BASIC, ...item.modules].map(id => `\`${id}\``).join('、')}。`,
  '- 该项目工作区能找到 CEF3 SDK（`.lingbuilder/modules/lingbuilder.cef3.sdk`，可用目录联接共享）；路径含中文不影响构建。',
  '- 代码镜头使用新手「结构化中文编辑」模式，采集画幅至少 `1920×1080 DIP`。',
  '- F5 前确认错误列表为 0；原生窗口置前后至少保持 3 秒再切镜头。',
  '',
  '## 关键控件',
  '',
  ...item.controls.map(control => `- \`${control.name}\`（${control.type}）`),
  '',
  '## 本集命令',
  '',
  ...item.commands.map(command => `- \`${command}\``),
  '',
  '## 分镜动作',
  '',
  ...item.steps.map(text => `- ${text}`),
  '',
  '## 运行边界与红线',
  '',
  ...item.boundaries.map(text => `- ${text}`),
  '- 全程只使用本地测试页与自造测试数据；禁止真实账号、Cookie 值、代理凭据、私钥和个人文件路径入镜。',
  '- 不使用「绕过检测」「规避风控」一类表述。',
  ''
].join('\n');

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

async function writeText(file: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, 'utf8');
}

async function writeEpisode(item: Episode): Promise<void> {
  const projectDir = path.join(root, item.dir, '示例项目', item.id);
  await fs.rm(path.join(root, item.dir, '示例项目'), { recursive: true, force: true });

  await writeJson(path.join(projectDir, '.lingbuilder', 'solution.json'), solutionOf(item));
  await writeJson(path.join(projectDir, '.lingbuilder', 'window-designer.json'), designerOf(item));
  await writeJson(path.join(projectDir, '.lingbuilder', 'build-configuration.json'), { schemaVersion: 1, mode: 'Debug', architecture: 'x64' });
  // 根清单是工作区回退，projects/<id> 清单是项目权威清单；两份都写，保证任意打开方式都能启用模块。
  await writeJson(path.join(projectDir, '.lingbuilder', 'project-modules.json'), modulesOf(item));
  await writeJson(path.join(projectDir, '.lingbuilder', 'projects', item.id, 'project-modules.json'), modulesOf(item));
  await writeJson(path.join(projectDir, 'build-request.json'), buildRequestOf(item));

  await writeText(path.join(projectDir, 'src', `${item.className}.lcpp`), sourceOf(item));
  if (item.globals) {
    await writeText(path.join(projectDir, 'src', '项目全局变量.lcpp'), [
      '// 项目全局变量：作用域为当前项目，生命周期为整个进程。',
      ...item.globals,
      ''
    ].join('\n'));
  }
  await writeText(path.join(projectDir, 'config', item.id, 'config.ini'),
    `[project]\nname=${item.id}\ntoolchain=msvc\narchitecture=x64\n`);
  for (const [relativePath, content, encoding] of item.assets ?? []) {
    const target = path.join(projectDir, relativePath);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, encoding === 'base64' ? Buffer.from(content, 'base64') : content, encoding === 'base64' ? undefined : 'utf8');
  }
  await writeText(path.join(projectDir, 'README.md'), readmeOf(item));
  await writeText(path.join(root, item.dir, '录制准备.md'), recordingOf(item));
}

const COMPARE_ROWS: Array<[dimension: string, cef3: string, edgeview: string]> = [
  ['内核来源', '自带 Chromium 运行时，随 CEF3 SDK 分发', '系统 WebView2 Runtime，Windows 10/11 通常已具备'],
  ['版本可控性', '固定在 SDK 打包的 Chromium 版本，行为可复现', '跟随目标机 Runtime 更新，版本由系统决定'],
  ['SDK 体积', 'SDK 压缩包约 177 MiB，需下载并做 SHA-256 校验', '不需要下载大型 SDK'],
  ['分发文件', '需随程序分发 libcef.dll、chrome_elf.dll、resources.pak、icudtl.dat 与 locales/ 等运行时资源', '仅依赖目标机已安装的 WebView2 Runtime'],
  ['离线部署', '可完整离线分发，适合内网与固定环境', '目标机缺少 Runtime 时需先安装引导程序'],
  ['会话隔离', '每个实例独立 RequestContext，缓存目录即会话边界', '按实例与用户数据目录隔离，贴近 WebView2 模型'],
  ['代理配置', '创建前按实例配置，围绕原生 RequestContext', '支持全局与实例级代理，接口风格贴近 WebView2'],
  ['事件模型', '原生 CEF 回调目录，覆盖资源、下载、打印、DevTools 等 96 项事件', 'WebView2 事件模型，覆盖导航、消息、下载与权限等常用事件'],
  ['首次构建成本', '首次构建/预览/导出会触发 SDK 下载与校验', '直接构建，无 SDK 下载步骤'],
  ['典型取舍', '需要固定内核、完整离线分发或更深 CEF 回调时选它', '只要快速嵌入网页、执行脚本、处理常见事件时更省部署成本']
];

async function writeComparisonEpisode(): Promise<void> {
  const dir = path.join(root, '10 CEF3还是EdgeView');
  const materialDir = path.join(dir, '对比资料');
  await fs.rm(materialDir, { recursive: true, force: true });

  await writeText(path.join(materialDir, '对比矩阵.md'), [
    '# CEF3 与 EdgeView 对比矩阵',
    '',
    `- 生成时间：${GENERATED_AT}`,
    '- 用途：第 10 集图版与花字的唯一数据来源；改数据请先改本文件，再重做图版。',
    '- 口径来源：`electron/docs/modules/cef3/README.md`、`guide/user/modules/edgeview`、`guide/user/advanced/sdk-download.md` 与本合集 01～09 集实测。',
    '',
    '| 维度 | CEF3 | EdgeView |',
    '| --- | --- | --- |',
    ...COMPARE_ROWS.map(([dimension, cef3, edgeview]) => `| ${dimension} | ${cef3} | ${edgeview} |`),
    '',
    '## 一句话结论',
    '',
    '> 想快速把网页嵌进软件，优先 EdgeView；需要原生 CEF 能力、固定内核和离线资源控制，就选 CEF3。',
    '',
    '无论选哪一个，导出的 exe 都要按目标机器重新验收。',
    ''
  ].join('\n'));

  await writeText(path.join(materialDir, '截图采集清单.md'), [
    '# 第 10 集截图采集清单',
    '',
    '本集不新建 C++ 工程，全部画面复用 01～09 集已验证的示例项目与既有素材。',
    '',
    '| 编号 | 画面 | 来源 | 采集方式 | 注意 |',
    '| --- | --- | --- | --- | --- |',
    '| c1 | 标题卡 | 合集模板 | 图版 | 标注 B 合集 10/10 |',
    '| c2 | 内核与运行方式对比 | `对比矩阵.md` 前两行 | 图版 | 左右两列，不放版本号以外的细节 |',
    '| c3 | SDK 大小与运行时文件 | 第 01 集 SDK 对话框静帧 + 构建产物目录 | 复用 + PrintWindow | 文件名只做花字，不展示工作区绝对路径 |',
    '| c4 | 能力矩阵 | `对比矩阵.md` 全表 | 图版 | 突出「离线完整分发」与「快速嵌入」 |',
    '| c5 | 会话/代理/事件三行对比 | `对比矩阵.md` 对应行 | 图版 | 不展示真实账号与代理凭据 |',
    '| c6 | 结论卡 | 一句话结论 | 图版 | 「快速内嵌 → EdgeView / 原生 CEF → CEF3」 |',
    '| c7 | 运行时资源抓拍 | 第 01 集构建产物 `bin` 目录 | PrintWindow | 只框选 libcef.dll、chrome_elf.dll、resources.pak、locales |',
    '| c8 | 合集收官与 FBro 导流卡 | 合集模板 | 图版 | 引出 FBro 合集第 1 集 |',
    ''
  ].join('\n'));

  await writeText(path.join(materialDir, '引用来源.md'), [
    '# 第 10 集数据引用来源',
    '',
    '录制前必须逐条复核，数值以复核当天的实际文档与产物为准。',
    '',
    '- CEF3 接口与事件规模：`electron/docs/modules/cef3/README.md`',
    '- CEF3 SDK 体积与校验流程：`guide/user/advanced/sdk-download.md`、第 01 集 SDK 对话框静帧',
    '- CEF3 运行时分发文件：第 01 集构建产物 `bin` 目录（`libcef.dll`、`chrome_elf.dll`、`LingBuilderCefBridge.dll`、`resources.pak`、`icudtl.dat`、`locales/`）',
    '- EdgeView 能力与 Runtime 依赖：`guide/user/modules/edgeview`、EdgeView 合集 01～12 集示例项目',
    '- 会话与代理差异：本合集第 04、05 集示例项目实测',
    '',
    '> 口播中出现的任何数字（体积、接口数量、事件数量）都必须能在上面的来源里查到；查不到就改口播，不改数据。',
    ''
  ].join('\n'));

  await writeText(path.join(dir, '录制准备.md'), [
    '# 第 10 集录制准备：CEF3 还是 EdgeView · 部署与选型',
    '',
    '## 本集定位',
    '',
    '- 收官集，不新建 C++ 工程；画面由图版 + 01～09 集已验证素材构成。',
    '- 数据只来自 `对比资料/对比矩阵.md`，来源登记在 `对比资料/引用来源.md`。',
    '',
    '## 素材清单',
    '',
    '- `对比资料/对比矩阵.md`：图版与花字的唯一数据源。',
    '- `对比资料/截图采集清单.md`：c1～c8 逐镜头采集方式。',
    '- `对比资料/引用来源.md`：每个数字的出处，录制前逐条复核。',
    '',
    '## 录制注意',
    '',
    '- 体积、接口数量、事件数量等数字必须当天复核；对不上就改口播，不改数据。',
    '- 运行时资源抓拍只框选 `libcef.dll`、`chrome_elf.dll`、`resources.pak` 与 `locales/`，不展示工作区绝对路径。',
    '- 不展示真实账号、Cookie、代理凭据。',
    '- 片尾导流 FBro 合集第 1 集。',
    ''
  ].join('\n'));
}

async function writeOverview(): Promise<void> {
  await writeText(path.join(root, '示例项目总览.md'), [
    '# CEF3 浏览器模块合集 · 示例项目总览',
    '',
    `- 生成时间：${GENERATED_AT}`,
    '- 生成脚本：`electron/scripts/generate-cef3-tutorial-projects.ts`（`npm run tutorial:cef3:generate`）',
    '- 构建脚本：`electron/scripts/build-cef3-tutorial-projects.ts`（`npm run tutorial:cef3:build`），暂存到 ASCII 路径后跑真实 MSVC + CEF3 构建',
    '- 验证脚本：`electron/scripts/verify-cef3-tutorial-projects.ts`（`npm run tutorial:cef3:verify`），并把构建结果写进各集验证记录',
    '- 每集验证结论见各集 `验证记录.md`。',
    '',
    '## 项目清单',
    '',
    '| 集 | 示例项目 | 窗体类 | 启用模块（除基础模块） | 本集命令 |',
    '| --- | --- | --- | --- | --- |',
    ...episodes.map(item => `| ${item.no} | \`${item.dir}/示例项目/${item.id}\` | \`${item.className}\` | ${item.modules.map(id => `\`${id}\``).join('、')} | ${item.commands.map(command => `\`${command}\``).join('、')} |`),
    '| 10 | `10 CEF3还是EdgeView/对比资料`（无 C++ 工程） | — | — | — |',
    '',
    '## 统一运行方式',
    '',
    '1. 把目标项目文件夹复制到任意工作区目录（路径含中文没有影响）。',
    '2. 打开 `.lingbuilder/solution.json`。',
    '3. 确认模块面板已启用该集所需模块。',
    '4. F5 构建运行，确认错误列表为 0。',
    '',
    '批量验证（生成 → 构建 → 刷新验证记录）：',
    '',
    '```powershell',
    'cd electron',
    'npm run build:cli',
    'npm run tutorial:cef3:generate',
    'npm run tutorial:cef3:build',
    'npm run tutorial:cef3:verify',
    '```',
    '',
    '## 统一前置',
    '',
    '- Windows x64 + Visual Studio / MSVC 工具链。',
    '- 已安装并通过 SHA-256 校验的 `lingbuilder.cef3.sdk`。',
    '- 构建产物 `bin/` 目录包含 `libcef.dll`、`chrome_elf.dll`、`LingBuilderCefBridge.dll`、`resources.pak`、`icudtl.dat` 与 `locales/` 等 CEF 运行时资源；口播里说的「Resources」在实际产物中是这组 `.pak` / `.dat` 文件与 `locales/` 目录，不是同名文件夹。',
    '',
    '## 已知边界（录制前必读）',
    '',
    '- 运行时在窗口「创建完毕」之前已经创建全部 `CefBrowser`，因此 `CEF3_设置缓存目录` 与 `CEF3_设置代理` 只对纯代码创建的实例生效；设计器项目的等价配置是控件属性「缓存目录」「代理模式 / 自定义代理地址」（第 04、05 集）。',
    '- `file://` 页面不返回 HTTP 状态码，`statusCode` 可能为 0 或空；需要真实状态码与 3xx 重定向事件时，改用本地 HTTP 测试服务（第 06、07 集）。',
    '- 资源响应只提供 URL、状态码、MIME 等公开元数据；响应正文、响应头映射与响应过滤器不在当前公开 binding 内（第 06、07 集）。',
    '- **浏览器初始地址必须写在设计器控件属性「打开地址」里，不能在「创建完毕」事件里调 `CEF3_导航`**：CEF 浏览器异步创建，窗口 Loaded 时 bridge 句柄常常尚未就绪，导航会静默落空、页面停在 `about:blank`。`CEF3_导航` 只用于创建完成后的主动跳转（第 01～04 集）。',
    '- 缩放命令取值固定为 0 缩小、1 重置、2 放大（第 02 集）。',
    '- 事件实名以事件目录为准：`开始加载`、`加载完成`、`加载失败`、`加载状态改变`（第 03 集）。',
    '- 构建的真实前置是「工作区能找到 CEF3 SDK」，即该项目的 `.lingbuilder/modules` 下有 `lingbuilder.cef3.sdk`；**路径含中文不影响构建**（已在本合集中文原地路径实测通过）。`npm run tutorial:cef3:build` 复制到 `.tmp-cef3-verify/` 构建，是为了共享 SDK 联接并把大体积产物挡在示例目录外，不是为了绕开中文路径。',
    '- `控件_取文本` 等返回文本对象的命令，不能直接作为模块命令的文本参数；必须先落到 `局部 文本型` 变量（第 02、08 集）。',
    '- 中文代码里的 JS 字符串避免写成 `对象.方法(...)`，语言服务会把它识别成功能库调用（第 04 集）。',
    '- `build-request.json` 不写 `lingCppSourceFilePath`，否则 `src/项目全局变量.lcpp` 不会参与聚合（第 05、09 集）。',
    '',
    '## 安全红线',
    '',
    '- 只使用本地测试页与自造测试数据。',
    '- 禁止真实账号、Cookie 值、代理凭据、私钥与个人文件路径入镜。',
    '- 不使用「绕过检测」「规避风控」一类表述。',
    ''
  ].join('\n'));
}

for (const item of episodes) await writeEpisode(item);
await writeComparisonEpisode();
await writeOverview();
console.log(JSON.stringify({ ok: true, episodes: episodes.length + 1, root }, null, 2));
