import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { BUILTIN_MODULES } from '../src/services/modules/builtinModules';
import type { InstalledModule } from '../src/services/modules/types';
import { generateLingCppNativeWin32Project } from '../src/services/windowDesigner/lingCppWin32Project';
import type { LingWindowProject } from '../src/services/windowDesigner/types';
import { exportVisualStudioProject } from '../src/services/windowDesigner/visualStudioProjectExporter';

const execFileAsync = promisify(execFile);
const repoRoot = path.resolve(import.meta.dirname, '..', '..');
const projectDir = path.resolve(repoRoot, '.lingbuilder-build', 'cookie-native-smoke');

function builtin(id: string): InstalledModule {
  const manifest = BUILTIN_MODULES.find(item => item.id === id);
  if (!manifest) throw new Error(`缺少内置模块：${id}`);
  return { manifest, installPath: `builtin://${id}`, isBuiltin: true, isInstalled: true, isEnabledForProject: true, diagnostics: [] };
}

async function main() {
  if (!projectDir.startsWith(`${repoRoot}${path.sep}`)) throw new Error('Cookie 冒烟测试目录越出工作区。');
  const enabledModules = [builtin('lingbuilder.win32.basic'), builtin('lingbuilder.net.cookie')];
  const project: LingWindowProject = {
    schemaVersion: 2,
    id: 'cookie-native-smoke',
    name: 'Cookie导出模块原生冒烟测试',
    windows: [{ id: 'main', fileName: 'MainWindow.xml', className: 'MainWindow', title: 'Cookie导出模块原生冒烟测试', width: 420, height: 240, background: '#202028', description: '验证真实 Cookie 导出运行时', controls: [] }]
  };
  const source = [
    '类 MainWindow',
    '    事件 _MainWindow_创建完毕()',
    '        @ std::vector<std::string> failures;',
    '        @ auto check = [&](bool value, const char* name) { if (!value) failures.emplace_back(name); };',
    '        @ auto utf8 = [](const wchar_t* text) { return LB_WideToUtf8(text); };',
    '        @ auto net = [](const wchar_t* text) { return std::wstring(Cookie_导出Netscape(text)); };',
    '        @ auto etc = [](const wchar_t* text) { return std::wstring(Cookie_导出EditThisCookieJSON(text)); };',
    // Chromium cookies 表列名形态：会话 Cookie（expires_utc = 0）+ HttpOnly + Secure。
    '        @ const std::wstring sessionRow = L"[{\\"host_key\\":\\"mms.pinduoduo.com\\",\\"name\\":\\"PASS_ID\\",\\"value\\":\\"windows_1-abc\\",\\"path\\":\\"/\\",\\"is_secure\\":1,\\"is_httponly\\":1,\\"expires_utc\\":0,\\"samesite\\":-1}]";',
    '        @ const std::wstring netscape = net(sessionRow.c_str());',
    '        @ check(netscape == L"# Netscape HTTP Cookie File\\n# https://curl.se/docs/http-cookies.html\\n# This file was generated by LingBuilder! Edit at your own risk.\\n\\n#HttpOnly_mms.pinduoduo.com\\tFALSE\\t/\\tTRUE\\t0\\tPASS_ID\\twindows_1-abc\\n", "NETSCAPE-SESSION-ROW");',
    '        @ const std::wstring editThis = etc(sessionRow.c_str());',
    '        @ check(editThis == L"[\\n  {\\n    \\"domain\\": \\"mms.pinduoduo.com\\",\\n    \\"hostOnly\\": true,\\n    \\"httpOnly\\": true,\\n    \\"name\\": \\"PASS_ID\\",\\n    \\"path\\": \\"/\\",\\n    \\"sameSite\\": null,\\n    \\"secure\\": true,\\n    \\"session\\": true,\\n    \\"storeId\\": null,\\n    \\"value\\": \\"windows_1-abc\\"\\n  }\\n]", "EDITTHIS-SESSION-ROW");',
    // Chromium 微秒到期时间必须按整数换算成 Unix 秒并保留小数位，不得被双精度吃掉。
    '        @ const std::wstring datedRow = L"[{\\"host_key\\":\\".example.com\\",\\"name\\":\\"S\\",\\"value\\":\\"1\\",\\"path\\":\\"/api\\",\\"is_secure\\":0,\\"is_httponly\\":0,\\"expires_utc\\":13436785294206754,\\"samesite\\":1}]";',
    '        @ check(net(datedRow.c_str()).find(L".example.com\\tTRUE\\t/api\\tFALSE\\t1792311694\\tS\\t1\\n") != std::wstring::npos, "NETSCAPE-EPOCH-CONVERSION");',
    '        @ check(etc(datedRow.c_str()).find(L"\\"expirationDate\\": 1792311694.206754") != std::wstring::npos, "EDITTHIS-EXPIRATION-DATE");',
    '        @ const std::wstring editThisDated = etc(datedRow.c_str());',
    '        @ check(editThisDated.find(L"\\"hostOnly\\": false") != std::wstring::npos && editThisDated.find(L"\\"sameSite\\": \\"lax\\"") != std::wstring::npos && editThisDated.find(L"\\"session\\": false") != std::wstring::npos, "EDITTHIS-HOSTONLY-AND-SAMESITE");',
    // 浏览器扩展键名形态 + sameSite 字符串透传 + 引号/反斜杠转义。
    '        @ const std::wstring browserRow = L"[{\\"domain\\":\\"a.example.org\\",\\"name\\":\\"Q\\",\\"value\\":\\"x\\\\\\"y\\\\\\\\z\\",\\"path\\":\\"/\\",\\"expirationDate\\":1800000000.5,\\"hostOnly\\":true,\\"httpOnly\\":false,\\"secure\\":true,\\"sameSite\\":\\"strict\\"}]";',
    '        @ const std::wstring browserJson = etc(browserRow.c_str());',
    '        @ const std::wstring expectedEscaped = L"\\"value\\": \\"x\\\\\\"y\\\\\\\\z\\"";',
    '        @ check(browserJson.find(expectedEscaped) != std::wstring::npos, "EDITTHIS-ESCAPING");',
    '        @ check(browserJson.find(L"\\"sameSite\\": \\"strict\\"") != std::wstring::npos && browserJson.find(L"\\"expirationDate\\": 1800000000.5") != std::wstring::npos, "EDITTHIS-PASSTHROUGH");',
    '        @ check(net(L"[{\\"domain\\":\\"a.example.org\\",\\"name\\":\\"Q\\"}]").find(L"a.example.org\\tFALSE\\t/\\tFALSE\\t0\\tQ\\t\\n") != std::wstring::npos, "NETSCAPE-DEFAULTS");',
    // 空数组、缺字段、嵌套值和语法错误都必须给出中文错误而不是静默产出半成品。
    '        @ check(net(L"[]") == L"# Netscape HTTP Cookie File\\n# https://curl.se/docs/http-cookies.html\\n# This file was generated by LingBuilder! Edit at your own risk.\\n\\n", "NETSCAPE-EMPTY-ARRAY");',
    '        @ check(net(L"[{\\"name\\":\\"X\\"}]").empty() && std::wstring(Cookie_取错误()).find(L"缺少域名") != std::wstring::npos, "NETSCAPE-MISSING-DOMAIN");',
    '        @ check(etc(L"{\\"domain\\":\\"a\\",\\"name\\":\\"X\\"}").find(L"\\"hostOnly\\": true") != std::wstring::npos, "SINGLE-OBJECT-ACCEPTED");',
    '        @ check(etc(L"[{\\"domain\\":\\"a\\",\\"name\\":\\"X\\",\\"value\\":{\\"nested\\":1}}]").empty() && !std::wstring(Cookie_取错误()).empty(), "NESTED-VALUE-REJECTED");',
    '        @ check(net(L"[oops]").empty() && !std::wstring(Cookie_取错误()).empty(), "BAD-JSON-REJECTED");',
    '        @ std::ofstream report("cookie-native-smoke.txt", std::ios::binary | std::ios::trunc);',
    '        @ if (failures.empty()) report << "OK\\n"; else { report << "FAIL\\n"; for (const auto& failure : failures) report << failure << "\\n"; report << utf8(Cookie_取错误()) << "\\n"; }',
    '        @ report.close();',
    '        @ ExitProcess(failures.empty() ? 0 : 2);',
    '    结束',
    '结束类'
  ].join('\n');

  const generated = generateLingCppNativeWin32Project(project, { enabledModules, lingCppSourceCode: source });
  if (generated.blockingDiagnostics.length) throw new Error(generated.blockingDiagnostics.join('\n'));
  await fs.rm(projectDir, { recursive: true, force: true });
  await fs.mkdir(projectDir, { recursive: true });
  for (const file of generated.files) {
    const target = path.resolve(projectDir, file.relativePath);
    if (!target.startsWith(`${projectDir}${path.sep}`)) throw new Error(`生成文件越界：${file.relativePath}`);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, file.content, 'utf8');
  }
  await fs.mkdir(path.join(projectDir, 'resources'), { recursive: true });
  await fs.copyFile(path.join(repoRoot, 'image', 'lingbuilder-ide-icon-v1.ico'), path.join(projectDir, 'resources', 'lingbuilder-app.ico'));
  const exported = await exportVisualStudioProject({ projectDir, projectId: project.id, generatedFiles: generated.files, enabledModules });
  const vswhere = path.join(process.env['ProgramFiles(x86)'] || 'C:\\Program Files (x86)', 'Microsoft Visual Studio', 'Installer', 'vswhere.exe');
  const installation = (await execFileAsync(vswhere, ['-latest', '-products', '*', '-requires', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', '-property', 'installationPath'], { windowsHide: true })).stdout.trim();
  const msbuild = path.join(installation, 'MSBuild', 'Current', 'Bin', 'MSBuild.exe');
  for (const platform of ['Win32', 'x64']) {
    await execFileAsync(msbuild, [exported.solutionPath, '/m', '/t:Build', '/p:Configuration=Release', `/p:Platform=${platform}`, '/v:minimal'], { cwd: projectDir, windowsHide: true, timeout: 10 * 60 * 1000, maxBuffer: 32 * 1024 * 1024 });
  }
  const executable = path.join(projectDir, 'x64', 'Release', 'bin', `${exported.projectName}.exe`);
  const run = await execFileAsync(executable, [], { cwd: path.dirname(executable), windowsHide: true, timeout: 3 * 60 * 1000, maxBuffer: 1024 * 1024 }).catch(error => ({ error }));
  if ('error' in run) throw run.error;
  const report = await fs.readFile(path.join(path.dirname(executable), 'cookie-native-smoke.txt'), 'utf8');
  if (report.trim() !== 'OK') throw new Error(`原生 Cookie 导出验证失败：\n${report}`);
  console.log(JSON.stringify({ ok: true, projectDir, executable, platforms: ['Win32', 'x64'], report: report.trim() }, null, 2));
}

main().catch(error => { console.error(error instanceof Error ? error.stack || error.message : error); process.exitCode = 1; });
