import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { ExtensionService } from '../src/services/extensions/extensionService';

async function extension(root: string, directory: string, manifest: any, source: string) { const target = path.join(root, '.lingbuilder', 'extensions', directory); await fs.mkdir(target, { recursive: true }); await fs.writeFile(path.join(target, 'package.json'), JSON.stringify(manifest)); await fs.writeFile(path.join(target, 'extension.js'), source); for (const theme of manifest.contributes?.themes || []) await fs.writeFile(path.resolve(target, theme.path), JSON.stringify({ colors: { 'editor.background': '#111111' } })); }
const contributionSet = { commands: [{ command: 'sample.hello', title: '你好命令' }], menus: [{ menu: 'editor/context', command: 'sample.hello' }], views: [{ id: 'sample.view', name: '示例视图' }], languages: [{ id: 'sample-lang', extensions: ['.sample'] }], themes: [{ id: 'sample-dark', label: '示例深色', path: './theme.json', uiTheme: 'vs-dark' }] };

test('independent Extension Host activates, contributes, enforces permissions and recovers from crash', { timeout: 60_000 }, async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'lingbuilder-extension-')); t.after(() => fs.rm(root, { recursive: true, force: true })); await fs.writeFile(path.join(root, 'marker.txt'), 'yes'); await fs.writeFile(path.join(root, 'input.txt'), 'hello');
  await extension(root, 'sample', { name: 'sample', publisher: 'lingbuilder', version: '1.0.0', main: 'extension.js', activationEvents: ['workspaceContains:marker.txt', 'onCommand:sample.hello'], permissions: ['workspace.read', 'workspace.write'], contributes: contributionSet }, `exports.activate = async context => { const text = await context.workspace.readTextFile('input.txt'); context.commands.registerCommand('sample.hello', async () => { await context.workspace.writeTextFile('output.txt', text + '!'); return text + ' world'; }); };`);
  await extension(root, 'denied', { name: 'denied', publisher: 'lingbuilder', version: '1.0.0', main: 'extension.js', activationEvents: ['onCommand:denied.read'], permissions: [], contributes: { commands: [{ command: 'denied.read', title: '拒绝读取' }] } }, `exports.activate = context => context.commands.registerCommand('denied.read', () => context.workspace.readTextFile('input.txt'));`);
  await extension(root, 'require', { name: 'require', publisher: 'lingbuilder', version: '1.0.0', main: 'extension.js', activationEvents: ['onCommand:require.fs'], contributes: { commands: [{ command: 'require.fs', title: '加载 FS' }] } }, `exports.activate = () => { require('node:fs'); };`);
  const service = new ExtensionService(root); t.after(() => service.stop()); const started = await service.start(); assert.equal(started.state, 'ready'); assert.ok(started.pid && started.pid !== process.pid); const sample = service.getSnapshot().extensions.find(item => item.id === 'lingbuilder.sample')!; assert.equal(sample.state, 'active'); assert.equal(sample.manifest.contributes?.menus?.[0].menu, 'editor/context'); assert.equal(sample.manifest.contributes?.languages?.[0].id, 'sample-lang');
  assert.equal(await service.executeCommand('sample.hello'), 'hello world'); assert.equal(await fs.readFile(path.join(root, 'output.txt'), 'utf8'), 'hello!'); await assert.rejects(service.executeCommand('denied.read'), /未声明权限 workspace\.read/u); await assert.rejects(service.executeCommand('require.fs'), /无权加载 Node 模块/u);
  const theme = await service.loadTheme('lingbuilder.sample', 'sample-dark'); assert.equal(theme.base, 'vs-dark'); assert.equal(theme.colors['editor.background'], '#111111');
  const oldPid = service.getSnapshot().pid; await service.simulateCrashForTest(); assert.equal(service.getSnapshot().state, 'ready'); assert.notEqual(service.getSnapshot().pid, oldPid); assert.equal(service.getSnapshot().restartCount, 1);
  await service.setEnabled('lingbuilder.sample', false); assert.equal(service.getSnapshot().extensions.find(item => item.id === 'lingbuilder.sample')?.state, 'disabled'); await assert.rejects(service.executeCommand('sample.hello'), /未注册|禁用/u);
  assert.equal(JSON.parse(await fs.readFile(path.join(root, '.lingbuilder', 'extensions-state.json'), 'utf8'))['lingbuilder.sample'], false);
});

test('extension scan reports invalid manifests without starting them', async t => { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'lingbuilder-extension-invalid-')); t.after(() => fs.rm(root, { recursive: true, force: true })); const target = path.join(root, '.lingbuilder', 'extensions', 'bad'); await fs.mkdir(target, { recursive: true }); await fs.writeFile(path.join(target, 'package.json'), '{"name":"bad"}'); const service = new ExtensionService(root); t.after(() => service.stop()); const snapshot = await service.start(); assert.equal(snapshot.extensions[0].state, 'error'); assert.match(snapshot.extensions[0].error || '', /缺少/u); });
