import React, { useState } from 'react';
import { Database, RefreshCw, Search, Square } from 'lucide-react';

export default function AiIndexPanel({ isDarkMode }: { isDarkMode: boolean }) {
  const [busy, setBusy] = useState(false); const [status, setStatus] = useState('尚未建立 AI 工作区索引。'); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [hits, setHits] = useState<Array<{ path: string; score: number; preview: string }>>([]);
  const rebuild = async () => { setBusy(true); setError(''); try { const response = await fetch('/api/ai-index/rebuild', { method: 'POST' }); const value = await response.json(); if (!response.ok) throw new Error(value.error); setStatus(`索引完成：${value.fileCount} 个文件`); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const cancel = async () => { await fetch('/api/ai-index/cancel', { method: 'POST' }); };
  const search = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const response = await fetch(`/api/ai-index/search?query=${encodeURIComponent(query)}`); const value = await response.json(); if (!response.ok) throw new Error(value.error); setHits(value.hits); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  const surface = isDarkMode ? 'border-slate-800 bg-[#1b1b1d] shadow-black/10' : 'border-slate-200 bg-white shadow-slate-200/50';
  const iconButton = `flex h-7 w-7 items-center justify-center rounded-md border transition-colors focus:outline-none focus:ring-1 focus:ring-violet-500 disabled:cursor-not-allowed disabled:opacity-40 ${isDarkMode ? 'border-slate-700 bg-slate-800/70 text-slate-300 hover:bg-slate-700 hover:text-white' : 'border-slate-200 bg-slate-50 text-slate-600 hover:bg-slate-100 hover:text-slate-900'}`;
  return (
    <section className={`rounded-lg border p-3 text-xs shadow-sm ${surface}`} aria-labelledby="ai-index-title">
      <div className="flex min-w-0 items-center gap-2.5"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${isDarkMode ? 'bg-violet-500/10 text-violet-400' : 'bg-violet-50 text-violet-600'}`}><Database className="h-4 w-4" /></span><div className="min-w-0 flex-1"><strong id="ai-index-title" className={isDarkMode ? 'text-slate-100' : 'text-slate-800'}>AI 工作区索引</strong><div role="status" aria-live="polite" className="mt-0.5 truncate text-[10px] text-slate-500">{busy ? '正在建立索引…' : status}</div></div><button aria-label="重建 AI 工作区索引" title="重建索引" disabled={busy} onClick={() => void rebuild()} className={iconButton}><RefreshCw className={`h-3.5 w-3.5 ${busy ? 'animate-spin' : ''}`} /></button><button aria-label="取消索引构建" title="停止构建" disabled={!busy} onClick={() => void cancel()} className={iconButton}><Square className="h-3 w-3" /></button></div>
      {error && <div role="alert" className={`mt-2 rounded-md border px-2.5 py-2 text-[10px] ${isDarkMode ? 'border-rose-500/20 bg-rose-500/10 text-rose-300' : 'border-rose-200 bg-rose-50 text-rose-700'}`}>{error}</div>}
      <form onSubmit={search} className="relative mt-2"><label className="sr-only" htmlFor="ai-index-query">搜索工作区索引</label><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-500" /><input id="ai-index-query" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索已索引的代码和文件…" className={`h-8 w-full rounded-md border pl-8 pr-14 text-[10px] outline-none transition-colors focus:border-violet-500 ${isDarkMode ? 'border-slate-700 bg-slate-900/70 text-slate-200 placeholder:text-slate-600' : 'border-slate-200 bg-slate-50 text-slate-800 placeholder:text-slate-400'}`} /><button type="submit" disabled={!query.trim()} className="absolute right-1 top-1 h-6 rounded px-2 text-[9px] font-medium text-violet-400 transition-colors hover:bg-violet-500/10 disabled:opacity-40">搜索</button></form>
      {hits.length > 0 && <div aria-label="索引搜索结果" className={`mt-2 max-h-32 overflow-auto rounded-md border ${isDarkMode ? 'border-slate-800' : 'border-slate-200'}`}>{hits.map(hit => <div key={hit.path} tabIndex={0} className={`border-b px-2.5 py-2 text-[10px] last:border-b-0 ${isDarkMode ? 'border-slate-800 hover:bg-slate-800/40' : 'border-slate-100 hover:bg-slate-50'}`}><div className="flex items-center justify-between gap-2"><span className="truncate font-medium">{hit.path}</span><span className="text-violet-400">{hit.score}</span></div><div className="mt-0.5 truncate text-slate-500">{hit.preview}</div></div>)}</div>}
    </section>
  );
}
