import React, { useState } from 'react';
import { Activity, FileInput, Play, Square } from 'lucide-react';
import { requestWorkbenchPrompt } from '../services/workbench/workbenchConfirmService';

interface Report { state: 'completed' | 'cancelled'; durationMs: number; samples: unknown[]; hotFunctions: Array<{ name: string; selfMs: number }>; summary: { peakWorkingSetBytes: number; cpuMs: number; readBytes: number; writeBytes: number } }
export default function PerformancePanel() { const [report, setReport] = useState<Report | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const request = async (url: string, body: unknown = {}) => { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok || !value.ok) throw new Error(value.error || '性能分析失败。'); return value.report as Report; };
  const run = async () => { const executablePath = await requestWorkbenchPrompt({ title: '开始性能采集', description: '输入工作区内可执行文件路径', inputLabel: '可执行文件路径' }); if (!executablePath) return; setBusy(true); setError(''); try { setReport(await request('/api/performance/collect', { executablePath, durationMs: 5000, intervalMs: 250 })); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const cancel = async () => { await request('/api/performance/cancel').catch(reason => setError(String(reason))); };
  const importProfile = async () => { const filePath = await requestWorkbenchPrompt({ title: '导入 CPU Profile', description: '输入工作区内 Chrome CPU Profile（.cpuprofile）路径', inputLabel: 'Profile 路径' }); if (!filePath) return; setError(''); try { setReport(await request('/api/performance/import', { filePath })); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } };
  const mb = (value: number) => (value / 1024 / 1024).toFixed(2);
  return <section className="mt-4 border-t border-slate-500/30 pt-3" aria-label="CPU、内存和 I/O 性能分析"><div className="mb-2 flex items-center gap-2"><Activity className="h-4 w-4 text-cyan-500"/><strong>CPU / 内存 / I/O 性能分析</strong><button disabled={busy} onClick={run} className="ml-auto rounded border px-2 py-1"><Play className="inline h-3 w-3"/> 开始采集</button><button disabled={!busy} onClick={cancel} className="rounded border px-2 py-1"><Square className="inline h-3 w-3"/> 取消</button><button disabled={busy} onClick={importProfile} className="rounded border px-2 py-1"><FileInput className="inline h-3 w-3"/> 导入 CPU Profile</button></div>{error && <div role="alert" className="text-rose-500">{error}</div>}{busy && <div role="status">正在采集性能数据…</div>}{!busy && !report && <div className="opacity-60">尚无性能报告。</div>}{report && <div><div>{report.state === 'cancelled' ? '已取消' : '已完成'} · {report.durationMs}ms · CPU {report.summary.cpuMs.toFixed(1)}ms · 峰值内存 {mb(report.summary.peakWorkingSetBytes)}MB · 读取 {mb(report.summary.readBytes)}MB · 写入 {mb(report.summary.writeBytes)}MB</div><div className="max-h-28 overflow-auto">{report.hotFunctions.map(item => <div key={item.name} className="flex justify-between"><span>{item.name}</span><span>{item.selfMs}ms</span></div>)}</div></div>}</section>;
}
