import React, { useState } from 'react';
import { BarChart3, FileWarning, Play } from 'lucide-react';

interface Report { coverage: Array<{ filePath: string; covered: number; total: number; percentage: number; lines: Array<{ line: number; hits: number; state: 'covered' | 'uncovered' }> }>; diagnostics: Array<{ source: string; severity: string; message: string; filePath?: string; line?: number; column?: number; code?: string }>; summary: { coveredLines: number; totalLines: number; coveragePercentage: number; errors: number; warnings: number } }
export default function QualityPanel({ isDarkMode }: { isDarkMode: boolean }) { const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const request = async (url: string, body: unknown) => { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok || !value.ok) throw new Error(value.error || '质量分析失败。'); return value.report as Report; };
  const run = async (action: () => Promise<Report>) => { setBusy(true); setError(''); try { const next = await action(); setReport(next); window.dispatchEvent(new CustomEvent('lingbuilder-quality-diagnostics', { detail: { diagnostics: next.diagnostics } })); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const nodeCoverage = () => { const filePath = window.prompt('输入 Node 测试文件路径（*.test/spec.ts/js）'); if (filePath) void run(() => request('/api/quality/node-coverage', { filePath })); };
  const importReports = () => { const coveragePath = window.prompt('LCOV 或 coverage-final.json 路径（可留空）') || undefined; const sarifPath = window.prompt('SARIF 静态分析报告路径（可留空）') || undefined; const sanitizerPath = window.prompt('ASan/UBSan 日志路径（可留空）') || undefined; if (coveragePath || sarifPath || sanitizerPath) void run(() => request('/api/quality/import', { coveragePath, sarifPath, sanitizerPath })); };
  const showCoverage = (file: Report['coverage'][number]) => window.dispatchEvent(new CustomEvent('lingbuilder-coverage-updated', { detail: { filePath: file.filePath, lines: file.lines } }));
  return <div className="mt-5 border-t border-slate-500/30 pt-3" aria-label="代码质量"><div className="mb-2 flex items-center gap-2"><BarChart3 className="h-4 w-4 text-violet-500" /><strong>覆盖率 / 静态分析 / Sanitizer</strong><button disabled={busy} onClick={nodeCoverage} className="ml-auto rounded border border-slate-500/40 px-2 py-1"><Play className="inline h-3 w-3" /> Node 覆盖率</button><button disabled={busy} onClick={importReports} className="rounded border border-slate-500/40 px-2 py-1"><FileWarning className="inline h-3 w-3" /> 导入报告</button></div>{error && <div role="alert" className="mb-2 text-rose-500">{error}</div>}{busy && <div className="text-amber-500">正在分析…</div>}{report && <><div className="mb-2">行覆盖率 <span className="font-semibold text-violet-500">{report.summary.coveragePercentage}%</span>（{report.summary.coveredLines}/{report.summary.totalLines}） · 错误 {report.summary.errors} · 警告 {report.summary.warnings}</div><div className="max-h-36 overflow-auto">{report.coverage.map(file => <button key={file.filePath} onClick={() => showCoverage(file)} className={`flex w-full items-center gap-2 border-t py-1 text-left ${isDarkMode ? 'border-slate-700' : 'border-slate-200'}`}><span className="w-14 text-right font-mono">{file.percentage}%</span><span className="min-w-0 flex-1 truncate">{file.filePath}</span><span className="opacity-60">{file.covered}/{file.total}</span></button>)}{report.diagnostics.map((item, index) => <div key={`${item.source}:${index}`} className={`border-t py-1 ${item.severity === 'error' ? 'text-rose-500' : item.severity === 'warning' ? 'text-amber-500' : ''}`}><div>{item.source.toUpperCase()}{item.code ? ` ${item.code}` : ''} · {item.message}</div>{item.filePath && <div className="opacity-70">{item.filePath}:{item.line || 1}:{item.column || 1}</div>}</div>)}</div></>}</div>;
}
