import React, { useEffect, useState } from 'react';
import { Check, ChevronDown, ChevronRight, Cloud, GitBranch, GitMerge, History, Minus, Plus, RefreshCw, Search } from 'lucide-react';
import type { SourceControlStatus } from '../types';

interface Branch { name: string; current: boolean; commit: string; subject: string }
interface Commit { hash: string; shortHash: string; authorName: string; authoredAt: string; subject: string; refs: string[] }
interface Remote { name: string; fetchUrl: string; pushUrl: string }
interface ConflictDetail { path: string; base: string; ours: string; theirs: string; working: string }

export default function SourceControlPanel({ initialStatus, isDarkMode, onChanged }: { initialStatus: SourceControlStatus | null; isDarkMode: boolean; onChanged?: () => void }) {
  const [status, setStatus] = useState(initialStatus); const [open, setOpen] = useState(false); const [message, setMessage] = useState('');
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [branches, setBranches] = useState<Branch[]>([]); const [history, setHistory] = useState<Commit[]>([]); const [remotes, setRemotes] = useState<Remote[]>([]); const [conflicts, setConflicts] = useState<any[]>([]); const [conflictDetails, setConflictDetails] = useState<Record<string, ConflictDetail>>({}); const [detail, setDetail] = useState<'changes' | 'branches' | 'history' | 'remote' | 'conflicts'>('changes');
  useEffect(() => setStatus(initialStatus), [initialStatus]);
  const request = async (url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok || body.ok === false) throw new Error(body.error || 'Git 操作失败。'); return body.result ?? body; };
  const refresh = async () => { const next = await request('/api/source-control/status'); setStatus(next); setSelected(current => new Set([...current].filter(item => next.files.some((file: any) => file.path === item)))); onChanged?.(); };
  const perform = async (action: () => Promise<void>) => { setBusy(true); setError(''); try { await action(); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const paths = selected.size ? [...selected] : (status?.files || []).map(file => file.path);
  const loadBranches = () => perform(async () => { setBranches(await request('/api/source-control/branches')); setDetail('branches'); });
  const loadHistory = () => perform(async () => { setHistory(await request('/api/source-control/history?limit=50')); setDetail('history'); });
  const loadRemote = () => perform(async () => { setRemotes(await request('/api/source-control/remotes')); setDetail('remote'); });
  const loadConflicts = () => perform(async () => { const files = await request('/api/source-control/conflicts'); setConflicts(files); const details = await Promise.all(files.map(async (file: any) => await request(`/api/source-control/conflicts/file?path=${encodeURIComponent(file.path)}`))); setConflictDetails(Object.fromEntries(details.map((item: ConflictDetail) => [item.path, item]))); setDetail('conflicts'); });
  const createBranch = () => { const name = window.prompt('新分支名称'); if (name) void perform(async () => { setBranches(await request('/api/source-control/branches', { method: 'POST', body: JSON.stringify({ name, checkout: true }) })); }); };
  const blame = () => { const filePath = window.prompt('输入工作区文件路径'); if (!filePath) return; const line = Number(window.prompt('起始行', '1')); void perform(async () => { const lines = await request(`/api/source-control/blame?path=${encodeURIComponent(filePath)}&startLine=${line}&endLine=${line + 19}`); window.alert(lines.map((item: any) => `${item.line} ${item.author} ${item.shortHash || item.hash.slice(0, 8)} · ${item.text}`).join('\n') || '没有可显示的 blame 记录。'); }); };
  const surface = isDarkMode ? 'border-[#2d2d34] bg-[#1e1e1e]' : 'border-slate-200 bg-white';
  if (!status?.isRepository) return <div className={`rounded border px-2 py-1.5 text-[10px] ${surface}`}><span>Git：当前工作区不是仓库</span>{status?.error && <div className="mt-1 truncate text-rose-500" title={status.error}>{status.error}</div>}</div>;
  return <div className={`rounded border text-[10px] ${surface}`} aria-label="Git 源代码管理">
    <button className="flex w-full items-center gap-1 px-2 py-1.5 text-left" onClick={() => setOpen(value => !value)}>{open ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}<GitBranch className="h-3 w-3" /><span className="min-w-0 flex-1 truncate">{status.branch || 'detached'}{status.ahead ? ` ↑${status.ahead}` : ''}{status.behind ? ` ↓${status.behind}` : ''}</span><span className="font-semibold text-amber-500">{status.files.length}</span></button>
    {open && <div className="border-t border-inherit p-2">
      <div className="mb-2 flex gap-1"><button title="改动" onClick={() => setDetail('changes')} className="rounded border border-inherit p-1"><Check className="h-3 w-3" /></button><button title="分支" onClick={loadBranches} className="rounded border border-inherit p-1"><GitBranch className="h-3 w-3" /></button><button title="远程同步" onClick={loadRemote} className="rounded border border-inherit p-1"><Cloud className="h-3 w-3" /></button><button title="冲突" onClick={loadConflicts} className="rounded border border-inherit p-1"><GitMerge className="h-3 w-3" /></button><button title="历史" onClick={loadHistory} className="rounded border border-inherit p-1"><History className="h-3 w-3" /></button><button title="Blame" onClick={blame} className="rounded border border-inherit p-1"><Search className="h-3 w-3" /></button><button title="刷新" onClick={() => void perform(refresh)} className="ml-auto rounded border border-inherit p-1"><RefreshCw className={`h-3 w-3 ${busy ? 'animate-spin' : ''}`} /></button></div>
      {error && <div role="alert" className="mb-2 whitespace-pre-wrap text-rose-500">{error}</div>}
      {detail === 'changes' && <>
        <textarea value={message} onChange={event => setMessage(event.target.value)} placeholder="提交说明" rows={2} className={`mb-1 w-full resize-y rounded border border-inherit px-2 py-1 ${isDarkMode ? 'bg-black/20' : 'bg-white'}`} />
        <button disabled={busy || !message.trim()} onClick={() => void perform(async () => { await request('/api/source-control/commit', { method: 'POST', body: JSON.stringify({ message }) }); setMessage(''); })} className="mb-2 w-full rounded bg-blue-600 px-2 py-1 text-white disabled:opacity-40">提交已暂存更改</button>
        <div className="mb-1 flex gap-1"><button disabled={!paths.length} onClick={() => void perform(async () => { await request('/api/source-control/stage', { method: 'POST', body: JSON.stringify({ paths }) }); setSelected(new Set()); })} className="rounded border border-inherit px-1.5 py-0.5"><Plus className="inline h-3 w-3" /> 暂存</button><button disabled={!paths.length} onClick={() => void perform(async () => { await request('/api/source-control/unstage', { method: 'POST', body: JSON.stringify({ paths }) }); setSelected(new Set()); })} className="rounded border border-inherit px-1.5 py-0.5"><Minus className="inline h-3 w-3" /> 取消暂存</button></div>
        <div className="max-h-48 overflow-auto">{status.files.map(file => <label key={file.path} className="flex items-center gap-1 border-t border-inherit py-1"><input type="checkbox" checked={selected.has(file.path)} onChange={event => setSelected(current => { const next = new Set(current); event.target.checked ? next.add(file.path) : next.delete(file.path); return next; })} /><span className="w-7 font-mono text-amber-500">{file.indexStatus || '·'}{file.workingTreeStatus || '·'}</span><span className="min-w-0 flex-1 truncate" title={file.path}>{file.path}</span></label>)}</div>
      </>}
      {detail === 'branches' && <div><button onClick={createBranch} className="mb-1 rounded border border-inherit px-1.5 py-0.5"><Plus className="inline h-3 w-3" /> 新建分支</button>{branches.map(branch => <div key={branch.name} className="flex items-center border-t border-inherit"><button disabled={branch.current} onClick={() => void perform(async () => { setBranches(await request('/api/source-control/branches/checkout', { method: 'POST', body: JSON.stringify({ name: branch.name }) })); })} className={`min-w-0 flex-1 truncate py-1 text-left ${branch.current ? 'text-blue-500' : ''}`} title={branch.subject}>{branch.current ? '● ' : ''}{branch.name}</button>{!branch.current && <button title={`删除分支 ${branch.name}`} onClick={() => { if (window.confirm(`确定删除已合并分支“${branch.name}”吗？`)) void perform(async () => { setBranches(await request(`/api/source-control/branches/${encodeURIComponent(branch.name)}`, { method: 'DELETE' })); }); }} className="px-1 text-rose-500"><Minus className="h-3 w-3" /></button>}</div>)}</div>}
      {detail === 'history' && <div className="max-h-56 overflow-auto">{history.map(commit => <div key={commit.hash} className="border-t border-inherit py-1"><div className="truncate font-medium">{commit.subject}</div><div className="truncate opacity-60">{commit.shortHash} · {commit.authorName} · {new Date(commit.authoredAt).toLocaleString()}</div></div>)}</div>}
      {detail === 'remote' && <div><div className="mb-1 font-semibold">远程同步</div>{remotes.length === 0 && <div className="opacity-60">没有已配置的远程仓库。</div>}{remotes.map(remote => <div key={remote.name} className="border-t border-inherit py-1"><div className="truncate" title={remote.fetchUrl}>{remote.name} · {remote.fetchUrl}</div><div className="mt-1 flex flex-wrap gap-1"><button onClick={() => void perform(async () => { await request('/api/source-control/fetch', { method: 'POST', body: JSON.stringify({ remote: remote.name }) }); })} className="rounded border border-inherit px-1">获取</button><button onClick={() => void perform(async () => { await request('/api/source-control/pull', { method: 'POST', body: JSON.stringify({ remote: remote.name, branch: status.branch, strategy: 'ff-only' }) }); })} className="rounded border border-inherit px-1">拉取</button><button onClick={() => void perform(async () => { await request('/api/source-control/push', { method: 'POST', body: JSON.stringify({ remote: remote.name, branch: status.branch, setUpstream: !status.upstream }) }); })} className="rounded border border-inherit px-1">推送</button><button onClick={() => { const base = window.prompt('PR 目标分支', 'main'); const title = window.prompt('PR 标题'); if (base && title) void perform(async () => { const pr = await request('/api/source-control/pull-requests', { method: 'POST', body: JSON.stringify({ remote: remote.name, base, title, body: window.prompt('PR 说明', '') || '' }) }); window.alert(`PR 已创建：${pr.url}`); }); }} className="rounded border border-inherit px-1">创建 PR</button></div></div>)}<div className="mt-2 flex gap-1"><button onClick={() => { const branch = window.prompt('要合并到当前分支的分支'); if (branch) void perform(async () => { await request('/api/source-control/merge', { method: 'POST', body: JSON.stringify({ branch }) }); }); }} className="rounded border border-inherit px-1">合并…</button><button onClick={() => { const branch = window.prompt('要变基到的分支'); if (branch) void perform(async () => { await request('/api/source-control/rebase', { method: 'POST', body: JSON.stringify({ branch }) }); }); }} className="rounded border border-inherit px-1">变基…</button></div></div>}
      {detail === 'conflicts' && <div><div className="mb-1 font-semibold">三方冲突编辑</div>{conflicts.length === 0 && <div className="opacity-60">当前没有未解决冲突。</div>}{conflicts.map(file => { const item = conflictDetails[file.path]; return <div key={file.path} className="border-t border-inherit py-1"><div className="truncate">{file.indexStatus}{file.workingTreeStatus} · {file.path}</div>{item && <><div className="mt-1 grid grid-cols-3 gap-1"><pre className="max-h-20 overflow-auto whitespace-pre-wrap rounded bg-black/10 p-1" title="共同基础">基础\n{item.base}</pre><pre className="max-h-20 overflow-auto whitespace-pre-wrap rounded bg-black/10 p-1" title="当前分支">当前\n{item.ours}</pre><pre className="max-h-20 overflow-auto whitespace-pre-wrap rounded bg-black/10 p-1" title="传入分支">传入\n{item.theirs}</pre></div><textarea aria-label={`合并内容 ${file.path}`} value={item.working} onChange={event => setConflictDetails(current => ({ ...current, [file.path]: { ...item, working: event.target.value } }))} rows={5} className={`mt-1 w-full resize-y rounded border border-inherit p-1 font-mono ${isDarkMode ? 'bg-black/20' : 'bg-white'}`} /></>}<div className="mt-1 flex gap-1"><button onClick={() => void perform(async () => { await request('/api/source-control/conflicts/resolve', { method: 'POST', body: JSON.stringify({ path: file.path, resolution: 'ours' }) }); await loadConflicts(); })} className="rounded border border-inherit px-1">采用当前</button><button onClick={() => void perform(async () => { await request('/api/source-control/conflicts/resolve', { method: 'POST', body: JSON.stringify({ path: file.path, resolution: 'theirs' }) }); await loadConflicts(); })} className="rounded border border-inherit px-1">采用传入</button><button disabled={!item} onClick={() => void perform(async () => { await request('/api/source-control/conflicts/resolve', { method: 'POST', body: JSON.stringify({ path: file.path, resolution: 'manual', content: item.working }) }); await loadConflicts(); })} className="rounded border border-inherit px-1">保存合并结果</button></div></div>; })}<div className="mt-2 flex flex-wrap gap-1"><button onClick={() => { const kind = window.prompt('继续 merge 或 rebase', 'merge'); if (kind === 'merge' || kind === 'rebase') void perform(async () => { await request('/api/source-control/integration/continue', { method: 'POST', body: JSON.stringify({ kind }) }); }); }} className="rounded border border-inherit px-1">继续</button><button onClick={() => { const kind = window.prompt('中止 merge 或 rebase', 'merge'); if (kind === 'merge' || kind === 'rebase') void perform(async () => { await request('/api/source-control/integration/abort', { method: 'POST', body: JSON.stringify({ kind }) }); }); }} className="rounded border border-inherit px-1 text-rose-500">中止</button></div></div>}
    </div>}
  </div>;
}
