import crypto from 'node:crypto'; import fs from 'node:fs/promises'; import path from 'node:path';
export interface SettingsSyncBundle { schemaVersion: 1; exportedAt: string; entries: Array<{ scope: 'user' | 'workspace' | 'extensions'; content: unknown }> }
export class SettingsSyncService { constructor(private readonly workspaceRoot: string, private readonly userSettingsPath: string, private readonly beforeCommit?: (scope: string, index: number) => Promise<void> | void) {}
  async exportBundle(relative = '.lingbuilder/settings-sync.json'): Promise<{ path: string; bundle: SettingsSyncBundle }> { const target = await this.resolveWorkspaceWrite(relative); const entries: SettingsSyncBundle['entries'] = []; for (const [scope, file] of this.sources()) { const content = await readJson(file); if (content !== undefined) entries.push({ scope, content: sanitize(content) }); } const bundle: SettingsSyncBundle = { schemaVersion: 1, exportedAt: new Date().toISOString(), entries }; await atomicWrite(target, JSON.stringify(bundle, null, 2)); return { path: path.relative(await fs.realpath(this.workspaceRoot), target).replace(/\\/gu, '/'), bundle }; }
  async preview(relative: string): Promise<{ token: string; scopes: string[] }> { const file = await this.resolveWorkspaceExisting(relative); const bytes = await fs.readFile(file); const bundle = validateBundle(JSON.parse(bytes.toString('utf8'))); return { token: crypto.createHash('sha256').update(bytes).digest('hex'), scopes: bundle.entries.map(item => item.scope) }; }
  async importBundle(relative: string, token: string): Promise<{ scopes: string[] }> { const file = await this.resolveWorkspaceExisting(relative); const bytes = await fs.readFile(file); if (crypto.createHash('sha256').update(bytes).digest('hex') !== token) throw new Error('同步包已被外部修改，请重新预览。'); const bundle = validateBundle(JSON.parse(bytes.toString('utf8'))); const sourceMap = new Map(this.sources()); const staged: Array<{ scope: string; target: string; temp: string; backup: string; existed: boolean }> = []; try { for (const entry of bundle.entries) { const target = sourceMap.get(entry.scope)!; await fs.mkdir(path.dirname(target), { recursive: true }); const temp = `${target}.${crypto.randomUUID()}.sync`; await fs.writeFile(temp, JSON.stringify(sanitize(entry.content), null, 2)); staged.push({ scope: entry.scope, target, temp, backup: `${target}.${crypto.randomUUID()}.backup`, existed: await exists(target) }); } for (let index = 0; index < staged.length; index++) { const item = staged[index]; await this.beforeCommit?.(item.scope, index); if (item.existed) await fs.rename(item.target, item.backup); try { await fs.rename(item.temp, item.target); } catch (error) { if (item.existed) await fs.rename(item.backup, item.target); throw error; } } await Promise.all(staged.map(item => fs.rm(item.backup, { recursive: true, force: true }))); return { scopes: bundle.entries.map(item => item.scope) }; } catch (error) { for (const item of [...staged].reverse()) { await fs.rm(item.temp, { recursive: true, force: true }); if (await exists(item.backup)) { await fs.rm(item.target, { recursive: true, force: true }); await fs.rename(item.backup, item.target); } } throw error; } }
  private sources(): Array<[SettingsSyncBundle['entries'][number]['scope'], string]> { return [['user', this.userSettingsPath], ['workspace', path.join(this.workspaceRoot, '.lingbuilder', 'settings.json')], ['extensions', path.join(this.workspaceRoot, '.lingbuilder', 'extensions-state.json')]]; }
  private async resolveWorkspaceExisting(relative: string): Promise<string> { const root = await fs.realpath(this.workspaceRoot); const file = await fs.realpath(path.resolve(root, relative)); if (!inside(root, file) || !(await fs.stat(file)).isFile()) throw new Error('同步包必须位于工作区内。'); return file; }
  private async resolveWorkspaceWrite(relative: string): Promise<string> { const root = await fs.realpath(this.workspaceRoot); const file = path.resolve(root, relative); if (!inside(root, file) || file === root) throw new Error('同步包输出必须位于工作区内。'); return file; }
}
function validateBundle(value: any): SettingsSyncBundle { if (value?.schemaVersion !== 1 || !Array.isArray(value.entries) || value.entries.length > 3) throw new Error('设置同步包无效。'); const seen = new Set<string>(); for (const entry of value.entries) { if (!['user', 'workspace', 'extensions'].includes(entry?.scope) || seen.has(entry.scope) || !entry.content || typeof entry.content !== 'object' || Array.isArray(entry.content)) throw new Error('设置同步包条目无效。'); seen.add(entry.scope); } return value; }
function sanitize(value: any): any { if (Array.isArray(value)) return value.map(sanitize); if (!value || typeof value !== 'object') return value; return Object.fromEntries(Object.entries(value).filter(([key]) => !/(?:api.?key|token|secret|password|credential)/iu.test(key)).map(([key, item]) => [key, sanitize(item)])); }
async function readJson(file: string): Promise<unknown | undefined> { try { return JSON.parse(await fs.readFile(file, 'utf8')); } catch (error: any) { if (error?.code === 'ENOENT') return undefined; throw new Error(`设置文件 ${path.basename(file)} JSON 无效。`); } }
async function atomicWrite(file: string, content: string): Promise<void> { await fs.mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temp, content); await fs.rename(temp, file); }
function inside(root: string, value: string): boolean { const relative = path.relative(root, value); return !relative.startsWith('..') && !path.isAbsolute(relative); }
async function exists(file: string): Promise<boolean> { try { await fs.access(file); return true; } catch { return false; } }
