import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bot, Boxes, CalendarDays, ChevronRight, CircleDollarSign, Gauge, Globe2, KeyRound, LogOut, Menu, Network, PackageCheck, RefreshCw, Search, ShieldCheck, ShieldAlert, Users, X } from 'lucide-react';
import './styles.css';
import './mfa.css';
import { HomePage } from './HomePage';
import { SystemAiProviderAdmin } from './SystemAiProviderAdmin';
import { PUBLIC_WEBSITE_PATHS, WebsitePortal } from './WebsitePortal';
import { WebsiteContentAdmin } from './WebsiteContentAdmin';
import { ModuleCommerceAdmin } from './ModuleCommerceAdmin';
import { PromotionAdmin } from './PromotionAdmin';
import { ModelRouteAdmin } from './ModelRouteAdmin';
import { UsersAdmin } from './UsersAdmin';

const API = import.meta.env.VITE_CLOUD_API_URL || 'http://127.0.0.1:17900';
type Page = 'overview'|'site'|'users'|'credits'|'promotions'|'modules'|'providers'|'models'|'usage'|'audit';
const NAV: Array<{id:Page;label:string;icon:React.ComponentType<{size?:number}>}> = [
  {id:'overview',label:'运营总览',icon:Gauge},{id:'site',label:'官网内容',icon:Globe2},{id:'users',label:'用户账号',icon:Users},{id:'credits',label:'点数调账',icon:CircleDollarSign},{id:'promotions',label:'AI 赠送与免费日',icon:CalendarDays},{id:'modules',label:'收费模块',icon:PackageCheck},{id:'providers',label:'系统 AI 供应商',icon:Network},{id:'models',label:'模型路由',icon:Bot},{id:'usage',label:'AI 用量',icon:Activity},{id:'audit',label:'审计日志',icon:ShieldCheck}
];

function App(){
  const [tokens,setTokens]=useState(()=>({access:sessionStorage.getItem('lb-admin-access')||'',refresh:sessionStorage.getItem('lb-admin-refresh')||''}));
  const [page,setPage]=useState<Page>('overview'); const [mobile,setMobile]=useState(false); const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [needsMfa,setNeedsMfa]=useState(false); const [showPassword,setShowPassword]=useState(false); const [showMfaSetup,setShowMfaSetup]=useState(false); const [mfaBannerDismissed,setMfaBannerDismissed]=useState(()=>sessionStorage.getItem('lb-mfa-banner-dismissed')==='1');
  const request=async(path:string,init:RequestInit={})=>{const binary=typeof Blob!=='undefined'&&init.body instanceof Blob;const response=await fetch(`${API}${path}`,{...init,headers:{...(binary?{}:{'content-type':'application/json'}),authorization:`Bearer ${tokens.access}`,...init.headers}});const text=await response.text();const value=text?(()=>{try{return JSON.parse(text)}catch{return {message:text}}})():{};if(!response.ok)throw new Error(value.message||'请求失败');return value};
  const refreshToken=async()=>{if(!tokens.refresh)throw new Error('无刷新令牌');const response=await fetch(`${API}/v1/auth/token/refresh`,{method:'POST',body:JSON.stringify({refreshToken:tokens.refresh}),headers:{'content-type':'application/json'}});const v=await response.json();if(!response.ok)throw new Error(v.message);sessionStorage.setItem('lb-admin-access',v.accessToken);sessionStorage.setItem('lb-admin-refresh',v.refreshToken);setTokens({access:v.accessToken,refresh:v.refreshToken});return v};
  const load=async(retried=false)=>{if(!tokens.access)return;setBusy(true);setError('');try{const route=page==='models'?'model-routes':page==='providers'?'system-ai/providers':page;setData(await request(`/v1/admin/${route}`))}catch(reason){const msg=reason instanceof Error?reason.message:String(reason);if(!retried&&msg.includes('令牌无效或已过期')&&tokens.refresh){try{await refreshToken()}catch{sessionStorage.clear();setTokens({access:'',refresh:''});return}setBusy(false);return load(true)}setError(msg)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[page,tokens.access]);
  useEffect(()=>{if(tokens.access)void request('/v1/me').then(value=>setNeedsMfa(Boolean(value.user?.role&&!value.user?.mfa))).catch(()=>undefined)},[tokens.access]);
  if(location.pathname==='/'||location.pathname==='/index.html')return <HomePage/>;
  if(PUBLIC_WEBSITE_PATHS.includes(location.pathname.replace(/\/$/u,'')))return <WebsitePortal/>;
  if(!tokens.access)return <Login onLogin={value=>{sessionStorage.setItem('lb-admin-access',value.accessToken);sessionStorage.setItem('lb-admin-refresh',value.refreshToken);setTokens({access:value.accessToken,refresh:value.refreshToken})}}/>;
  if(showPassword)return <PasswordChange request={request} onClose={()=>{sessionStorage.clear();setTokens({access:'',refresh:''})}}/>;
  if(showMfaSetup)return <MfaSetup request={request} onComplete={()=>{sessionStorage.clear();setTokens({access:'',refresh:''})}} onExit={()=>setShowMfaSetup(false)}/>;
  if(location.pathname==='/device')return <DeviceApproval request={request}/>;
  const active=NAV.find(item=>item.id===page)!;
  return <div className="app-shell">
    <a className="skip-link" href="#main">跳到主要内容</a>
    <aside className={`sidebar ${mobile?'open':''}`} aria-label="管理导航"><div className="brand"><div className="brand-mark"><Boxes size={20}/></div><div><strong>LingBuilder</strong><span>AI 管理中心</span></div><button className="icon-btn mobile-only" aria-label="关闭导航" onClick={()=>setMobile(false)}><X/></button></div><nav>{NAV.map(item=>{const Icon=item.icon;return <button key={item.id} className={page===item.id?'active':''} aria-current={page===item.id?'page':undefined} onClick={()=>{setPage(item.id);setMobile(false)}}><Icon size={18}/><span>{item.label}</span><ChevronRight size={15}/></button>})}</nav><div className="sidebar-footer"><div className="secure"><ShieldCheck size={17}/><span>管理员 MFA 会话</span></div><button onClick={()=>setShowPassword(true)}><KeyRound size={17}/>修改密码</button>{needsMfa&&<button onClick={()=>setShowMfaSetup(true)}><ShieldAlert size={17}/>绑定 MFA</button>}<button onClick={()=>{sessionStorage.clear();setTokens({access:'',refresh:''})}}><LogOut size={17}/>退出登录</button></div></aside>
    {mobile&&<button className="scrim" aria-label="关闭导航遮罩" onClick={()=>setMobile(false)}/>}<section className="workspace"><header><button className="icon-btn mobile-only" aria-label="打开导航" onClick={()=>setMobile(true)}><Menu/></button><div><span className="eyebrow">系统运营</span><h1>{active.label}</h1></div><button className="refresh" onClick={()=>void load()} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'正在刷新':'刷新数据'}</button></header><main id="main" tabIndex={-1}>{needsMfa&&!mfaBannerDismissed&&<div className="mfa-banner" role="status"><ShieldAlert size={18}/><div><strong>建议为管理员账号绑定 MFA 动态验证码</strong><p>绑定后登录需要动态验证码，更安全；密钥只会生成一次，不会重复占用你的验证器。随时可在左下角“绑定 MFA”完成。</p></div><div className="mfa-banner-actions"><button className="primary" onClick={()=>setShowMfaSetup(true)}>立即绑定</button><button onClick={()=>{sessionStorage.setItem('lb-mfa-banner-dismissed','1');setMfaBannerDismissed(true)}}>稍后再说</button></div></div>}{error&&<div role="alert" className="alert">{error}<button onClick={()=>void load()}>重试</button></div>}{busy&&!data?<Skeleton/>:<PageContent page={page} data={data} request={request} reload={load}/>}</main></section>
  </div>
}

function DeviceApproval({request}:{request:(path:string,init?:RequestInit)=>Promise<any>}){const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{await request('/v1/auth/device/approve',{method:'POST',body:JSON.stringify({userCode:code})});setMessage('设备已授权，可以返回 LingBuilder CLI。')}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};return <main className="login-page"><section className="login-copy"><div className="brand-lockup"><Boxes/>LINGBUILDER</div><p className="eyebrow">CLI DEVICE AUTHORIZATION</p><h1>只授权你正在使用的<br/>可信命令行设备。</h1><p>LingBuilder CLI 不会读取你的账号密码。确认后，它只获得可撤销的设备会话。</p></section><section className="login-panel"><form onSubmit={submit}><div className="form-heading"><span>设备登录</span><h2>输入设备码</h2><p>设备码显示在发起登录的 LingBuilder CLI 终端中。</p></div><label htmlFor="device-code">设备码</label><input id="device-code" value={code} onChange={event=>setCode(event.target.value.toUpperCase())} autoComplete="one-time-code" maxLength={8} required/><button className="primary" disabled={busy}>{busy?'正在授权…':'确认授权此设备'}</button>{message&&<p role="status" className="privacy">{message}</p>}</form></section></main>}
function MfaSetup({request,onComplete,onExit}:{request:(path:string,init?:RequestInit)=>Promise<any>;onComplete:()=>void;onExit:()=>void}){const[uri,setUri]=useState('');const[code,setCode]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[already,setAlready]=useState(false);useEffect(()=>{void request('/v1/auth/mfa/setup',{method:'POST',body:'{}'}).then(value=>setUri(value.otpauthUrl)).catch(error=>{if(String(error.message).includes('已绑定'))setAlready(true);else setMessage(error.message)})},[]);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{if(already){await request('/v1/auth/mfa/disable',{method:'POST',body:JSON.stringify({code})});setMessage('MFA 已解绑，请使用新密码重新登录后重新绑定。');setTimeout(onComplete,1500);return}await request('/v1/auth/mfa/enable',{method:'POST',body:JSON.stringify({code})});setMessage('MFA 已启用，请使用密码 + 动态验证码重新登录。');setTimeout(onComplete,1500)}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};return <main className="login-page"><section className="login-copy"><div className="brand-lockup"><ShieldCheck/>LINGBUILDER SECURITY</div><p className="eyebrow">ADMIN MFA SETUP</p><h1>{already?'MFA 已绑定。':'绑定一个动态验证码<br/>密钥只会生成一次。'}</h1><p>{already?'当前账号已启用 MFA，无需重复绑定。如需更换验证器，可输入当前动态验证码解绑后重新绑定；解绑后所有会话会被撤销。':'使用身份验证器添加下方 otpauth 地址，然后输入六位动态验证码。已生成过的密钥会直接复用，不会在你的验证器里产生重复令牌。'}</p></section><section className="login-panel"><form onSubmit={submit}><div className="form-heading"><span>安全设置</span><h2>{already?'解绑 MFA':'绑定动态验证码'}</h2>{already?<p className="mfa-uri">当前账号已启用 MFA</p>:<p className="mfa-uri">{uri||'正在读取安全密钥…'}</p>}</div><label htmlFor="mfa-setup-code">{already?'当前动态验证码（用于解绑）':'六位动态验证码'}</label><input id="mfa-setup-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/gu,''))} required/><button className="primary" disabled={busy}>{busy?'正在处理…':already?'解绑 MFA':'验证并启用 MFA'}</button>{message&&<p role="status" className="privacy">{message}</p>}<button type="button" className="secondary-action" onClick={onExit}>{already?'返回管理后台（保持已绑定）':'返回管理后台（稍后绑定）'}</button></form></section></main>}
function PasswordChange({request,onClose}:{request:(path:string,init?:RequestInit)=>Promise<any>;onClose:()=>void}){const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');if(next.length<10||!/[A-Za-z]/u.test(next)||!/\d/u.test(next)){setMessage('新密码需要 10 至 128 位，并同时包含字母和数字。');return}if(next!==confirm){setMessage('两次输入的新密码不一致。');return}setBusy(true);try{await request('/v1/auth/password/change',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next})});setMessage('密码已修改，请使用新密码重新登录。');setTimeout(onClose,1500)}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};return <main className="login-page"><section className="login-copy"><div className="brand-lockup"><KeyRound/>LINGBUILDER SECURITY</div><p className="eyebrow">CHANGE PASSWORD</p><h1>修改管理员密码。</h1><p>修改成功后所有已登录会话会被撤销，需要使用新密码重新登录。建议同时删除服务器上的初始密码文件。</p></section><section className="login-panel"><form onSubmit={submit}><div className="form-heading"><span>安全设置</span><h2>修改密码</h2><p>新密码需要 10 至 128 位，并同时包含字母和数字。</p></div><label htmlFor="pw-current">当前密码</label><input id="pw-current" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/><label htmlFor="pw-next">新密码</label><input id="pw-next" type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} required minLength={10}/><label htmlFor="pw-confirm">确认新密码</label><input id="pw-confirm" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={10}/><button className="primary" disabled={busy}>{busy?'正在修改…':'确认修改密码'}</button>{message&&<p role="status" className="privacy">{message}</p>}</form></section></main>}

function Login({onLogin}:{onLogin:(value:any)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[mfaCode,setMfaCode]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API}/v1/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,mfaCode,deviceName:'LingBuilder 管理后台'})});const value=await response.json();if(!response.ok)throw new Error(value.message);onLogin(value)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};return <main className="login-page"><section className="login-copy"><div className="brand-lockup"><Boxes/>LINGBUILDER</div><p className="eyebrow">AI OPERATIONS PLATFORM</p><h1>让模型、成本与用户额度<br/>始终处于可控状态。</h1><p>集中管理模型路由、第三方通道、AI 点数与免费活动。用户源码默认零保留。</p><div className="trust-row"><span><ShieldCheck/>强制 MFA</span><span><KeyRound/>密钥加密</span><span><Activity/>完整审计</span></div></section><section className="login-panel"><form onSubmit={submit}><div className="form-heading"><span>管理员登录</span><h2>欢迎回来</h2><p>使用已绑定管理角色的 LingBuilder 账号。</p></div>{error&&<div className="alert" role="alert">{error}</div>}<label htmlFor="email">邮箱地址</label><input id="email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/><label htmlFor="password">密码</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><label htmlFor="mfa">MFA 动态验证码</label><input id="mfa" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/gu,''))}/><button className="primary" disabled={busy}>{busy?'正在验证…':'安全登录'}</button><p className="privacy"><ShieldCheck size={15}/>登录行为会写入管理员审计日志。</p></form></section></main>}

function PageContent({page,data,request,reload}:{page:Page;data:any;request:(p:string,i?:RequestInit)=>Promise<any>;reload:()=>Promise<void>}){
 if(page==='overview'){const d=data||{};return <><div className="metric-grid"><Metric label="注册用户" value={d.users||0} note="全部账号"/><Metric label="AI 请求" value={d.requests||0} note="累计请求"/><Metric label="可用模型" value={d.models||0} note="逻辑模型"/><Metric label="供应通道" value={d.providers||0} note="健康通道"/></div><section className="panel"><div className="panel-head"><div><span className="eyebrow">运行状态</span><h2>系统 AI 服务</h2></div><span className="status ok">运行正常</span></div><div className="health-grid"><Health title="零保留策略" detail="提示词与源码不写入数据库"/><Health title="点数账本" detail="冻结、结算和退款使用事务"/><Health title="模型路由" detail="IDE 只访问逻辑模型别名"/></div></section></>}
 if(page==='site')return <WebsiteContentAdmin data={data} request={request} reload={reload}/>;
 if(page==='users')return <UsersAdmin data={data} request={request} reload={reload}/>;
 if(page==='credits')return <><ActionForm title="人工点数调整" description="每次调整都会写入不可变账本和管理员审计。" fields={[['userId','用户 ID 或邮箱','text'],['points','调整点数（可为负数）','number'],['reason','调整原因','text']]} onSubmit={async value=>{await request('/v1/admin/credits/adjust',{method:'POST',body:JSON.stringify(value)});await reload()}}/><DataTable title="最近点数流水" rows={(data?.ledger||[]).map((row:any)=>({...row,userEmail:row.user?.email??'—',kindLabel:({SIGNUP_GIFT:'注册赠送',ADMIN_ADJUSTMENT:'人工调账',RECHARGE:'充值',RESERVE:'冻结',RELEASE:'释放',CHARGE:'AI 消耗',REFUND:'退款'} as any)[row.kind]??row.kind,at:row.createdAt?new Date(row.createdAt).toLocaleString('zh-CN'):''}))} columns={[['at','时间'],['userEmail','用户'],['kindLabel','类型'],['availableDelta','变动点数'],['balanceAfter','变动后余额'],['reason','原因']]} empty="尚无点数流水"/></>;
 if(page==='promotions')return <PromotionAdmin data={data} request={request} reload={reload}/>;
 if(page==='modules')return <ModuleCommerceAdmin data={data} request={request} reload={reload}/>;
 if(page==='providers')return <SystemAiProviderAdmin data={data} request={request} reload={reload}/>;
 if(page==='models')return <ModelRouteAdmin data={data} request={request} reload={reload}/>;
 if(page==='usage')return <DataTable title="最近 AI 请求" rows={data?.requests||[]} columns={[['id','请求 ID'],['modelAlias','模型'],['status','状态'],['inputTokens','输入 Token'],['outputTokens','输出 Token'],['chargedPoints','扣除点数']]} empty="尚无 AI 请求"/>;
 return <DataTable title="管理员审计" rows={data?.entries||[]} columns={[['createdAt','时间'],['actorUserId','操作者'],['action','操作'],['targetType','对象']]} empty="尚无审计记录"/>;
}
function LegacyModuleCommerceAdmin({data,request,reload}:{data:any;request:(p:string,i?:RequestInit)=>Promise<any>;reload:()=>Promise<void>}){
 const products=data?.products||[];const[productId,setProductId]=useState('');const[start,setStart]=useState('');const[end,setEnd]=useState('');
 useEffect(()=>{if(!productId&&products[0]?.id)setProductId(products[0].id)},[products,productId]);
 const schedule24Hours=(value:string)=>{setStart(value);if(!value){setEnd('');return}const date=new Date(value);setEnd(new Date(date.getTime()+86_400_000).toISOString().slice(0,16))};
 return <><ActionForm title="发布收费模块" description="商品状态由云端 moduleId 决定，不信任本地模块清单。" fields={[['moduleId','模块 ID','text'],['name','商品名称','text'],['description','商品说明','text']]} onSubmit={async value=>{await request('/v1/admin/modules/products',{method:'POST',body:JSON.stringify({...value,listed:true,enabled:true})});await reload()}}/>
 {products.length>0&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">MODULE COMMERCE</span><h2>报价与限时免费</h2><p>免费只是价格暂时为零，用户仍须注册并登录。</p></div></div><div className="action-form"><label>目标模块<select aria-label="目标收费模块" value={productId} onChange={event=>setProductId(event.target.value)}>{products.map((product:any)=><option key={product.id} value={product.id}>{product.name} · {product.moduleId}</option>)}</select></label>
 <ActionForm title="新增报价" description="支持永久买断或固定期限，价格单位为人民币分。" fields={[['name','报价名称','text'],['kind','perpetual / fixed_term','text'],['priceMinor','价格（分）','number'],['durationDays','授权天数（买断可留空）','number']]} onSubmit={async value=>{await request(`/v1/admin/modules/products/${encodeURIComponent(productId)}/offers`,{method:'POST',body:JSON.stringify(value)});await reload()}}/>
 <form className="action-form" onSubmit={async event=>{event.preventDefault();await request(`/v1/admin/modules/products/${encodeURIComponent(productId)}/free-windows`,{method:'POST',body:JSON.stringify({name:new FormData(event.currentTarget).get('name'),startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),timezone:'Asia/Shanghai',enabled:true})});await reload()}}><div className="form-heading"><span>24 小时快捷活动</span><h2>安排模块限时免费</h2><p>按本机北京时间选择，云端统一保存为 UTC。</p></div><label>活动名称<input name="name" required defaultValue="new_emoji 免费体验日"/></label><label>开始时间<input type="datetime-local" required value={start} onChange={event=>schedule24Hours(event.target.value)}/></label><label>结束时间<input type="datetime-local" required value={end} onChange={event=>setEnd(event.target.value)}/></label><button className="primary" disabled={!productId||!start||!end}>保存免费时段</button></form></div></section>}
 <DataTable title="收费模块商品" rows={products} columns={[['moduleId','模块 ID'],['name','商品'],['listed','上架'],['enabled','启用'],['policyVersion','策略版本']]} empty="尚未发布收费模块"/></>;
}
function Metric({label,value,note}:{label:string;value:any;note:string}){return <article className="metric"><span>{label}</span><strong>{String(value)}</strong><small>{note}</small></article>}
function Health({title,detail}:{title:string;detail:string}){return <div className="health"><span className="dot"/><div><strong>{title}</strong><p>{detail}</p></div></div>}
function DataTable({title,rows,columns,empty}:{title:string;rows:any[];columns:string[][];empty:string}){const[query,setQuery]=useState('');const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row,(_key,value)=>typeof value==='bigint'?value.toString():value).toLowerCase().includes(query.toLowerCase())),[rows,query]);return <section className="panel"><div className="panel-head"><h2>{title}</h2><label className="search"><Search size={16}/><span className="sr-only">筛选{title}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="筛选当前列表"/></label></div><div className="table-wrap"><table><thead><tr>{columns.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={row.id||i}>{columns.map(([key])=><td key={key}>{format(row[key])}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">{empty}</div>}</div></section>}
function ActionForm({title,description,fields,onSubmit}:{title:string;description:string;fields:string[][];onSubmit:(v:any)=>Promise<void>}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;const value=Object.fromEntries(new FormData(form).entries());try{await onSubmit(value);setMessage('保存成功。');form.reset()}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};return <section className="panel"><div className="panel-head"><div><h2>{title}</h2><p>{description}</p></div></div><form className="action-form" onSubmit={submit}>{fields.map(([name,label,type])=><label key={name}>{label}<input name={name} type={type} required={!['giftPoints','perUserListPriceCap','providerId','upstreamModel','durationDays'].includes(name)}/></label>)}<button className="primary" disabled={busy}>{busy?'正在保存…':'保存配置'}</button>{message&&<span role="status">{message}</span>}</form></section>}
function Skeleton(){return <div className="metric-grid" aria-label="正在加载"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div>}
function format(value:any){if(typeof value==='boolean')return value?'启用':'停用';if(value===null||value===undefined)return '—';if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/u.test(value))return new Date(value).toLocaleString('zh-CN');return String(value)}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
