import { useMemo, useState } from 'react';
import { Bot, CheckCircle2, Cpu, KeyRound, Pencil, Server, ShieldCheck, Sparkles } from 'lucide-react';
import './system-ai-provider.css';

type Request = (path: string, init?: RequestInit) => Promise<any>;
type Protocol = 'openai-compatible' | 'anthropic';
type Preset = 'deepseek-v4' | 'custom';
interface ProviderRoute { id:string; alias:string; upstreamModel:string; enabled:boolean; model?:{displayName?:string} }
interface ProviderRecord { id:string; name:string; kind:'OPENAI_COMPATIBLE'|'ANTHROPIC'; baseUrl:string; enabled:boolean; secretConfigured:boolean; timeoutMs:number; routes:ProviderRoute[] }
const initialForm = {providerId:'',name:'DeepSeek 系统 AI',preset:'deepseek-v4' as Preset,protocol:'openai-compatible' as Protocol,baseUrl:'https://api.deepseek.com/',apiKey:'',modelName:'',displayName:'',enabled:true};

export function SystemAiProviderAdmin({data,request,reload}:{data:any;request:Request;reload:()=>Promise<void>}){
 const providers=(data?.providers||[]) as ProviderRecord[]; const[form,setForm]=useState(initialForm);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');const editing=Boolean(form.providerId);
 const activeRoutes=useMemo(()=>providers.reduce((count,provider)=>count+(provider.enabled?provider.routes.filter(route=>route.enabled).length:0),0),[providers]);
 const update=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(current=>({...current,[key]:value}));
 const selectPreset=(preset:Preset)=>setForm(current=>preset==='deepseek-v4'?{...current,preset,name:current.providerId?current.name:'DeepSeek 系统 AI',protocol:'openai-compatible',baseUrl:'https://api.deepseek.com/',modelName:'',displayName:''}:{...current,preset,name:current.providerId?current.name:'自定义系统 AI',baseUrl:'',modelName:'',displayName:''});
 const editProvider=(provider:ProviderRecord)=>{const deepseek=provider.routes.some(route=>route.upstreamModel==='deepseek-v4-flash')&&provider.routes.some(route=>route.upstreamModel==='deepseek-v4-pro');const route=provider.routes.find(item=>item.enabled)||provider.routes[0];setForm({providerId:provider.id,name:provider.name,preset:deepseek?'deepseek-v4':'custom',protocol:provider.kind==='ANTHROPIC'?'anthropic':'openai-compatible',baseUrl:provider.baseUrl,apiKey:'',modelName:deepseek?'':route?.upstreamModel||'',displayName:deepseek?'':route?.model?.displayName||'',enabled:provider.enabled});setMessage('');setError('');document.getElementById('system-ai-provider-form')?.scrollIntoView({behavior:'smooth',block:'start'})};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');setError('');try{const path=editing?`/v1/admin/system-ai/providers/${encodeURIComponent(form.providerId)}`:'/v1/admin/system-ai/providers';await request(path,{method:editing?'PATCH':'POST',body:JSON.stringify({name:form.name,preset:form.preset,protocol:form.protocol,baseUrl:form.baseUrl,apiKey:form.apiKey||undefined,modelName:form.preset==='custom'?form.modelName:undefined,displayName:form.preset==='custom'?form.displayName:undefined,enabled:form.enabled})});setMessage(editing?'系统 AI 供应商已更新，新的模型路由已经生效。':'系统 AI 供应商已保存，模型路由已经建立。');setForm(initialForm);await reload()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
 return <>
  <div className="metric-grid provider-metrics"><div className="metric"><span>系统 AI 供应商</span><strong>{providers.length}</strong><small>已配置通道</small></div><div className="metric"><span>启用模型路由</span><strong>{activeRoutes}</strong><small>供 IDE 系统 AI 选择</small></div><div className="metric"><span>支持协议</span><strong>2</strong><small>OpenAI / Anthropic</small></div><div className="metric"><span>密钥保护</span><strong><ShieldCheck size={25}/></strong><small>加密保存，不再回显</small></div></div>
  <section className="panel system-ai-panel" id="system-ai-provider-form"><div className="panel-head"><div><span className="eyebrow">SYSTEM AI PROVIDER</span><h2>{editing?'编辑系统 AI 供应商':'配置系统 AI 供应商'}</h2><p>用于 IDE“AI 智能编程助手 → 系统 AI”。保存时同时建立可用的逻辑模型路由。</p></div><div className="secure-badge"><KeyRound size={15}/> API Key 加密保存</div></div>
   <form className="provider-config-form" onSubmit={submit}>
    <fieldset className="preset-picker"><legend>配置类型</legend><button type="button" className={form.preset==='deepseek-v4'?'selected':''} onClick={()=>selectPreset('deepseek-v4')}><Sparkles size={19}/><span><strong>DeepSeek V4</strong><small>自动配置 Flash 与 Pro</small></span>{form.preset==='deepseek-v4'&&<CheckCircle2 size={17}/>}</button><button type="button" className={form.preset==='custom'?'selected':''} onClick={()=>selectPreset('custom')}><Server size={19}/><span><strong>自定义供应商</strong><small>Base URL 与 Model Name</small></span>{form.preset==='custom'&&<CheckCircle2 size={17}/>}</button></fieldset>
    {form.preset==='deepseek-v4'&&<div className="deepseek-models"><div><Cpu size={17}/><span><strong>deepseek-v4-flash</strong><small>速度优先</small></span></div><div><Bot size={17}/><span><strong>deepseek-v4-pro</strong><small>能力优先</small></span></div></div>}
    <div className="provider-fields"><label>供应商名称<input value={form.name} onChange={event=>update('name',event.target.value)} required maxLength={80}/></label><label>接口协议<select value={form.protocol} disabled={form.preset==='deepseek-v4'} onChange={event=>update('protocol',event.target.value as Protocol)}><option value="openai-compatible">OpenAI 兼容协议</option><option value="anthropic">Anthropic Messages 协议</option></select></label><label className="wide">Base URL<input type="url" value={form.baseUrl} onChange={event=>update('baseUrl',event.target.value)} placeholder="https://api.example.com/v1" required/></label>{form.preset==='custom'&&<><label>Model Name<input value={form.modelName} onChange={event=>update('modelName',event.target.value)} placeholder="例如：claude-sonnet-4" required/></label><label>模型显示名称（可选）<input value={form.displayName} onChange={event=>update('displayName',event.target.value)} placeholder="留空则使用 Model Name"/></label></>}<label className="wide">API Key<input type="password" autoComplete="new-password" value={form.apiKey} onChange={event=>update('apiKey',event.target.value)} placeholder={editing?'留空表示保留当前密钥':'仅在保存时提交，之后不再回显'} required={!editing}/></label></div>
    <label className="provider-enabled"><input type="checkbox" checked={form.enabled} onChange={event=>update('enabled',event.target.checked)}/><span>启用此供应商和新建模型路由</span></label>{error&&<div className="alert" role="alert">{error}</div>}{message&&<div className="success-message" role="status"><CheckCircle2 size={17}/>{message}</div>}<div className="form-actions"><button className="primary" disabled={busy}>{busy?'正在保存…':editing?'保存供应商修改':'保存并建立模型路由'}</button>{editing&&<button type="button" className="secondary-action" onClick={()=>setForm(initialForm)}>取消编辑</button>}</div>
   </form>
  </section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">CONFIGURED CHANNELS</span><h2>已配置的系统 AI 通道</h2><p>密钥只显示配置状态；点击编辑时不会读取已有明文密钥。</p></div></div><div className="provider-list">{providers.map(provider=><article key={provider.id} className="provider-card"><div className="provider-card-head"><div className="provider-icon"><Server size={20}/></div><div><h3>{provider.name}</h3><p>{provider.kind==='ANTHROPIC'?'Anthropic Messages':'OpenAI 兼容'} · {provider.enabled?'已启用':'已停用'}</p></div><button onClick={()=>editProvider(provider)}><Pencil size={15}/>编辑</button></div><div className="provider-url">{provider.baseUrl}</div><div className="provider-route-list">{provider.routes.filter(route=>route.enabled).map(route=><span key={route.id}><Cpu size={13}/>{route.upstreamModel}</span>)}</div><div className="provider-card-foot"><span><KeyRound size={13}/>{provider.secretConfigured?'密钥已配置':'未配置密钥'}</span><span>超时 {Math.round(provider.timeoutMs/1000)} 秒</span></div></article>)}{!providers.length&&<div className="empty">尚未配置系统 AI 供应商。可从 DeepSeek V4 预设开始。</div>}</div></section>
 </>;
}
