import type {
  LingBuilderModuleManifest,
  ModuleBindingValueType,
  ModuleCommandBinding,
  ModuleCommandBindingParameter,
  ModuleCommandContribution
} from './types';
import { createModuleBindingSnippetArgument, isWideStringAbiBindingType, normalizeControlReferenceCallSnippet, normalizeControlReferenceParameter, withParamDocs, type ParamDocTable } from './bindingValueType';
import {
  FBRO_VIP_AGGREGATE_CATEGORY,
  FBRO_VIP_OFFICIAL_ENTRIES
} from './fbroVipApiCatalog';

const CORE_DEPENDENCY = [{ moduleId: 'lingbuilder.fbro.browser', minimumVersion: '2.1.0' }];
const TARGET = [{
  id: 'windows-msvc-x64' as const,
  platform: 'windows' as const,
  arch: 'x64' as const,
  toolchain: 'msvc' as const
}];

type Parameter = ModuleCommandBindingParameter;

function api(
  name: string,
  officialAlias: string,
  parameters: Parameter[],
  returnType: ModuleBindingValueType,
  description: string,
  options: {
    runtimeName?: string;
    visibility?: 'default' | 'advanced';
    example?: string;
    category?: string;
    capabilityKind?: ModuleCommandContribution['capabilityKind'];
  } = {}
): { command: ModuleCommandContribution; binding: ModuleCommandBinding } {
  const normalizedParameters = parameters.map(parameter => normalizeControlReferenceParameter(parameter, { controlTypes: ['FBroBrowser'] }));
  const signature = `${name}(${normalizedParameters.map(item => item.name).join(', ')})`;
  const normalizedExample = normalizeControlReferenceCallSnippet(options.example, normalizedParameters);
  return {
    command: {
      name,
      aliases: [officialAlias],
      signature,
      description,
      insertText: normalizedExample || `${name}(${normalizedParameters.map(createModuleBindingSnippetArgument).join(', ')})`,
      returnType: returnType === 'void' ? '空' : returnType === 'wideString' ? '文本型' : returnType === 'longLong' || returnType === 'handle' ? '长整数型' : returnType === 'double' ? '小数型' : returnType === 'bool' ? '逻辑型' : '整数型',
      category: options.category,
      capabilityKind: options.capabilityKind,
      visibility: options.visibility
    },
    binding: {
      command: name,
      runtimeName: options.runtimeName || name,
      parameters: normalizedParameters,
      returnType,
      encoding: normalizedParameters.some(item => isWideStringAbiBindingType(item.type)) ? 'wide' : undefined,
      example: normalizedExample
    }
  };
}

function module(
  id: string,
  name: string,
  category: LingBuilderModuleManifest['category'],
  description: string,
  entries: ReturnType<typeof api>[]
): LingBuilderModuleManifest {
  return {
    schemaVersion: 2,
    id,
    name,
    version: '2.1.0',
    category,
    description,
    author: 'LingBuilder',
    tags: ['内置', 'FBro', 'CEF135', 'x64'],
    dependencies: CORE_DEPENDENCY,
    contributes: {
      commands: entries.map(item => item.command)
    },
    targets: TARGET,
    bindings: {
      commands: entries.map(item => item.binding)
    }
  };
}

const FBRO_EVENT_PARAM_DOCS: ParamDocTable = {
  字段名: '要读取的事件字段名，取值见各事件说明（如 url、downloadItem、menuHandle）。',
  动作: '同步事件动作码：0 默认、1 继续、2 取消、3 已处理、4 延迟决定；未设置时使用事件清单默认动作。',
  文本: '同步事件返回给调用方的文本内容。',
  响应JSON: 'UTF-16 JSON 响应内容；作为事件或延续的结果交回浏览器，字段结构见对应事件说明。',
  延续句柄: '“FBro_取事件延续”取得的受管延续句柄，一次延迟决策事件对应一个；完成或取消后即失效，重复操作返回稳定错误码。',
  事件名: 'FBro 事件名，须与事件清单名称一致（如 OnBeforeDownload）；名称不匹配时绑定或采样设置不生效。',
  每秒次数: '该事件每秒最大投递次数；0 表示暂停投递。',
  最大字节数: '允许捕获的响应正文最大字节数；超出部分截断，事件字段 truncated 为 1。'
};

const FBRO_SESSION_PARAM_DOCS: ParamDocTable = {
  地址: 'Cookie 目标的完整 URL（含协议），如 "https://example.com/"；按该 URL 匹配 Cookie 域和路径。',
  代理地址: '代理地址，格式 "scheme://host:port"，如 "http://127.0.0.1:8080"。',
  用户名: '代理认证用户名；代理不要求认证时传空文本。',
  密码: '代理认证密码；代理不要求认证时传空文本。',
  包含HttpOnly: '是否包含 HttpOnly Cookie：1 包含，0 排除。',
  名称: 'Cookie 名称；删除命令传空文本时删除该地址全部 Cookie。',
  值: 'Cookie 内容文本。',
  域: 'Cookie 归属域，如 "example.com"。',
  路径: 'Cookie 生效路径，如 "/"。',
  安全: '是否标记仅 HTTPS 传输（Secure）：1 是，0 否。',
  仅HTTP: '是否标记 HttpOnly（禁止页面脚本读取）：1 是，0 否。',
  来源: '缓存来源限定文本；空文本时不限定来源。',
  移除标志: '缓存移除标志位掩码；0 使用默认清除范围。',
  配额标志: '配额数据移除标志位掩码；0 使用默认。',
  设置JSON: '上下文设置 JSON 文本，支持 cachePath、persistSessionCookies、acceptLanguageList、cookieableSchemesList、cookieableSchemesExcludeDefaults 键。',
  上下文句柄: '“FBro会话_创建上下文”任务结果中 context 字段的上下文句柄；只用于“FBro会话_使用上下文重建”。'
};

const FBRO_TRANSFER_PARAM_DOCS: ParamDocTable = {
  地址: '要下载的资源完整 URL（含协议）；空文本按无效参数拒绝。',
  下载句柄: '“下载前”“下载更新”事件字段 downloadItem 携带的下载项受管句柄；句柄失效或类型不符时命令返回负错误码。',
  输出路径: 'PDF 保存路径，必须以 .pdf 结尾（大小写不限）；父目录不存在会自动创建，路径非法时不产生任务（返回 0）。',
  设置JSON: 'PDF 生成设置 JSON 文本；传空文本使用默认设置，JSON 解析失败时不产生任务（返回 0）。',
  模式: '对话框模式：0 打开单文件、1 多选打开、2 选择文件夹、3 保存；越界不产生任务（返回 0）。',
  标题: '对话框标题文本，可传空。',
  默认路径: '对话框初始目录或默认文件名，可传空文本。',
  筛选器JSON: '扩展名筛选器 JSON 字符串数组，如 ["*.txt","*.png"]；必须是合法 JSON 数组，否则不产生任务（返回 0）。',
  格式: '截图格式 "png" 或 "jpeg"（大小写不限）；传空按 "png"，其他值不产生任务（返回 0）。',
  质量: 'JPEG 压缩质量 0~100；png 格式忽略，越界不产生任务。',
  横坐标: '截图区域左上角 X（CSS 像素，≥0；负数不产生任务）。',
  纵坐标: '截图区域左上角 Y（CSS 像素，≥0；负数不产生任务）。',
  宽度: '截图区域宽度（CSS 像素，≥0）。',
  高度: '截图区域高度（CSS 像素，≥0）。',
  缩放: '页面缩放因子 0~8；越界不产生任务。',
  来自表面: '真=等待从渲染表面截取，结果更稳定；假=直接从当前视图截取。',
  超出视口: '真=允许截取视口之外的完整页面内容。'
};

const FBRO_AUTOMATION_PARAM_DOCS: ParamDocTable = {
  脚本: '要执行的 JavaScript 源码文本。',
  脚本地址: '模拟脚本来源 URL，仅用于错误定位信息；可传空文本。',
  起始行: '配合脚本地址在错误信息中定位行号的起始行号，一般传 1。',
  标识: '框架官方字符串标识，可从“FBro框架_取标识列表JSON”获得。',
  地址: '要让该框架载入的完整 URL（含协议）。',
  名称: '框架名称，可从“FBro框架_取名称列表JSON”获得。',
  框架句柄: '“FBro框架_取主框架”“FBro框架_按标识取框架”等命令返回的受管框架句柄；框架销毁后失效，无效句柄返回负错误码。',
  请求句柄: '“FBro请求_创建”创建的受管请求对象句柄。',
  目标进程: '消息目标进程：0 浏览器进程、1 渲染进程。',
  消息句柄: '“FBro消息_创建”创建的受管进程消息句柄。',
  URL请求句柄: '异步 URL 请求任务结果中 urlRequest 字段的受管请求句柄；用 FBro异步请求_取状态 等命令查询。',
  选择器: 'CSS 选择器文本，如 "#submit" 或 "input[name=q]"；匹配多个元素时用序号选择。',
  序号: '同选择器匹配结果中的元素下标，从 0 起；超出匹配数量时失败。',
  滚到顶部: '真=滚动到元素顶部对齐，假=尽量贴底对齐。',
  是否聚焦: '真=聚焦该元素，假=移除焦点。',
  值: '要写入的表单值文本。',
  是否选中: '真=勾选，假=取消勾选。',
  选项序号: '下拉框 option 下标，从 0 起。',
  文本: '要写入的纯文本内容。',
  代码文本: '要写入的 HTML 片段文本。',
  属性名: '要读取或设置的 HTML 属性名，如 "href"。',
  属性值: '要写入的属性值文本。',
  事件名: '要合成的 DOM 事件名，如 onclick、ondblclick、keydown、change、input。',
  按键代码: '键盘类事件的虚拟键码，回车传 13。',
  最大深度: 'DOM 遍历最大嵌套深度；0 使用默认值 16。',
  最大节点数: 'DOM 快照最多捕获的节点总数；0 使用默认值 4000。',
  快照句柄: '“FBro框架_遍历DOM”返回的 DOM 快照受管句柄，0 表示遍历失败；内容是遍历时刻的静态数据。',
  节点序号: '快照节点下标，从 0 起、小于“FBro遍历_取节点数”；越界返回负错误码。',
  属性序号: '元素属性下标，从 0 起、小于“FBro遍历_取节点属性数”；越界返回负错误码或空文本。',
  路径JSON: '“FBro遍历_取节点路径”返回的节点路径 JSON，如 "[0,2,1]"。'
};

const FBRO_OBJECTS_PARAM_DOCS: ParamDocTable = {
  任务ID: '异步命令返回的受管任务 ID；释放后再使用返回负错误码。',
  超时毫秒: '最长等待毫秒数；0 表示只查当前状态不等待，上限 600000（10 分钟），负数或超限按无效参数拒绝。',
  文本: '要写入或发送的文本内容。',
  路径: '保存目标文件的完整路径。',
  缓冲句柄: '“FBro缓冲_从文本”“FBro任务_取缓冲”等返回的受管缓冲句柄；释放后再用返回负错误码。',
  MIME类型: 'MIME 类型文本，如 "image/png"、"text/html"。',
  数据: '要编码为 data URI 的文本内容。',
  请求句柄: '“FBro请求_创建”返回的受管请求对象句柄；失效后返回负错误码。',
  地址: '完整 URL（含协议）。',
  方法: 'HTTP 方法文本，如 "GET"、"POST"。',
  引用页: '引用页 URL，配合策略参数使用。',
  策略: '引用页策略：0 清除、1 省略、2 降级、3 始终、4 源。',
  头列表JSON: '请求头 JSON 数组，格式 [{"name":"...","value":"..."}]。',
  提交数据句柄: '“FBro提交数据_创建”创建的 POST 提交数据对象句柄。',
  元素句柄: '“FBro提交数据_创建元素”创建或“FBro提交数据_取元素句柄列表JSON”注册的提交元素句柄。',
  消息名: '进程消息名称，接收方按该名称识别消息。',
  消息句柄: '“FBro消息_创建”创建的受管进程消息句柄。',
  菜单句柄: '“上下文菜单显示前”事件字段 menuHandle 携带的菜单模型句柄；仅事件处理期内有效，事件结束后被回收。',
  句柄: '菜单模型句柄：事件字段 menuHandle，或“FBro菜单_添加子菜单”返回的子菜单句柄；仅在对应事件处理期内有效。',
  命令ID: '菜单项命令 ID，同一菜单内唯一；添加后用它定位、修改或删除该菜单项。',
  标题: '菜单项显示文本。',
  键码: '加速键的 Windows 虚拟键码，如 13=回车、65=字母 A。',
  Shift: '是否按住 Shift 键。',
  Ctrl: '是否按住 Ctrl 键。',
  Alt: '是否按住 Alt 键。',
  是否Shift: '是否按住 Shift 键。',
  是否Ctrl: '是否按住 Ctrl 键。',
  是否Alt: '是否按住 Alt 键。',
  颜色类型: '菜单颜色类型常量，指定读取或设置哪一类颜色（文字、悬停背景等）。',
  'FBro图像_转位图缓冲::颜色类型': '位图像素颜色类型常量（RGBA 等），决定输出缓冲的像素布局。',
  'FBro图像_转位图缓冲::透明类型': '图像透明类型常量，决定输出位图透明通道的处理方式。',
  'FBro字典_复制::排除空子项': '真=复制时跳过值为空的子项。',
  标签: '菜单项标签文本。',
  分组ID: '单选项分组标识；同分组内的单选项互斥。',
  序号: '菜单项下标，从 0 起、小于“FBro菜单_取数量”；越界时命令失败。',
  是否可见: '真=显示，假=隐藏。',
  是否启用: '真=可用，假=置灰。',
  是否选中: '真=勾选，假=取消勾选。',
  字体列表: 'CSS 字体列表文本，如 "Microsoft YaHei, Arial"。',
  Alpha: 'Alpha 透明度分量 0~255。',
  Red: '红色分量 0~255。',
  Green: '绿色分量 0~255。',
  Blue: '蓝色分量 0~255。',
  参数句柄: '“上下文菜单显示前”事件字段 paramsHandle 携带的右键菜单参数句柄；仅事件处理期内有效，事件结束后被回收。',
  响应句柄: '资源响应类事件字段 response 携带的响应句柄，或“FBro响应_创建”创建的自定义响应句柄。',
  错误码: '响应错误码；0 表示无错误。',
  状态码: 'HTTP 状态码，如 200、404。',
  状态文本: 'HTTP 状态文本，如 "OK"、"Not Found"。',
  字符集: '响应字符集名称，如 "utf-8"。',
  头名: '协议头名称，如 "Content-Type"。',
  覆盖同名: '真=替换已存在的同名协议头。',
  协议头JSON: '协议头 JSON 数组，格式 [{"name":"...","value":"..."}]。',
  清除原有: '真=先移除全部已有协议头再写入。',
  对象句柄: '任意 FBro 受管对象句柄；已释放后再操作返回负错误码。',
  值句柄: '“FBro值_创建”创建或“FBro任务_取对象”“FBro字典_取值对象”等返回的 Value 受管句柄。',
  另一值句柄: '参与比较的另一个 Value 受管句柄。',
  值: '要写入的值。',
  字典句柄: '“FBro字典_创建”创建或“FBro值_取字典”“FBro字典_取字典”等返回的 Dictionary 受管句柄。',
  键: '字典键名；键不存在时读取类命令返回默认值（0、假或空文本）。',
  另一字典句柄: '参与比较的另一个 Dictionary 受管句柄。',
  子字典句柄: '要交给该键管理的子 Dictionary 受管句柄。',
  列表句柄: '“FBro列表_创建”创建或“FBro消息_取参数列表”“FBro值_取列表”等返回的 List 受管句柄。',
  另一列表句柄: '参与比较的另一个 List 受管句柄。',
  子列表句柄: '要交给该下标管理的子 List 受管句柄。',
  索引: '元素下标，从 0 起；负数按无效参数拒绝，证书链越界返回 0。',
  数量: '新列表长度；扩大的位置填充空值。',
  流句柄: '“FBro流_从文件创建”“FBro流_从缓冲创建”返回的只读流句柄。',
  元素大小: '单个元素的字节数，如 1=字节。',
  元素数量: '最多读取的元素个数；单次总读取上限 256 MiB。',
  偏移: '目标字节偏移，配合基准参数使用。',
  基准: '定位基准：0 开头、1 当前位置、2 结尾。',
  图像句柄: '“FBro图像_下载”“FBro拖放数据_取图像”等返回的受管图像句柄。',
  缩放因子: '目标缩放因子，如 1.0、1.5、2.0，用于匹配对应 DPI 的图像表示。',
  质量: 'JPEG 编码质量 0~100。',
  保留透明: '真=保留 PNG 透明通道。',
  作为图标: '真=按图标用途下载（浏览器优先选择图标尺寸资源）。',
  最大尺寸: '返回图像的最大尺寸（像素），超出会被缩放。',
  绕过缓存: '真=绕过本地缓存重新下载。',
  证书句柄: '证书异步任务或证书错误事件返回的受管证书句柄。',
  主体句柄: '“FBro证书_取主体”“FBro证书_取颁发者”返回的 Principal 受管句柄。',
  拖放数据句柄: 'DragEnter 事件携带的受管拖放数据句柄。'
};

const FBRO_NETWORK_PARAM_DOCS: ParamDocTable = {
  代理地址: '代理地址，格式 "scheme://host:port"，如 "http://127.0.0.1:8080"。',
  用户名: '代理认证用户名；代理不要求认证时传空文本。',
  密码: '代理认证密码；代理不要求认证时传空文本。',
  监听地址: '服务器监听地址，如 "127.0.0.1"；实际监听地址见任务结果 address 字段。',
  端口: 'TCP 监听端口 1~65535。',
  最大连接数: '允许的最大并发连接数。',
  服务器句柄: '“FBro服务器_创建”任务结果 server 字段携带的内嵌服务器句柄；关闭后失效。',
  连接ID: '服务器事件字段 connectionId 携带的连接编号。',
  通道名: '页面拦截挂钩脚本使用的通道名称，须与页面侧注册的通道一致。',
  文本: '要发送的文本内容（按 UTF-8 传输）。',
  缓冲句柄: '“FBro缓冲_从文本”“FBro任务_取缓冲”等返回的受管缓冲句柄；释放后再用返回负错误码。',
  WS客户端句柄: 'WebSocket 拦截事件字段 websocket 携带的受管客户端句柄；为 0 表示当前没有客户端。'
};

const eventEntries = [
  api('FBro_取事件数据', 'LB_FBro_GetLastEventData', [{ name: '控件名', type: 'controlRef' }], 'wideString', '取得当前处理中的事件主数据。'),
  api('FBro_取事件字段', 'LB_FBro_GetEventField', [{ name: '控件名', type: 'controlRef' }, { name: '字段名', type: 'wideString' }], 'wideString', '从 UTF-16 JSON 事件包读取结构化字段。'),
  api('FBro_设置事件结果', 'LB_FBro_SetEventResult', [{ name: '控件名', type: 'controlRef' }, { name: '动作', type: 'int' }], 'int', '设置同步事件动作；未设置时使用事件清单默认动作。'),
  api('FBro_设置事件返回文本', 'LB_FBro_SetEventResultText', [{ name: '控件名', type: 'controlRef' }, { name: '文本', type: 'wideString' }], 'int', '设置同步事件返回文本。'),
  api('FBro_设置事件响应JSON', 'LB_FBro_SetEventResponseJson', [{ name: '控件名', type: 'controlRef' }, { name: '响应JSON', type: 'wideString' }], 'int', '设置 C ABI v3 事件结构化响应；回调返回后 Bridge 会立即复制。'),
  api('FBro_取事件对象', 'LB_FBro_GetLastEventObject', [{ name: '控件名', type: 'controlRef' }], 'longLong', '取得 CertificateError 或 DragEnter 事件携带的受管对象句柄。', { visibility: 'advanced' }),
  api('FBro_取事件延续', 'LB_FBro_GetLastEventContinuation', [{ name: '控件名', type: 'controlRef' }], 'longLong', '取得当前延迟决策事件的受管延续句柄；只允许传给完成或取消命令。', { visibility: 'advanced' }),
  api('FBro_取事件对象字段', 'LB_FBro_GetEventObjectField', [{ name: '控件名', type: 'controlRef' }, { name: '字段名', type: 'wideString' }], 'wideString', '读取事件包中复制后的对象字段或受管句柄字段。', { visibility: 'advanced' }),
  api('FBro事件_完成延续', 'LB_FBro_CompleteEventContinuation', [{ name: '延续句柄', type: 'longLong' }, { name: '响应JSON', type: 'wideString' }], 'int', '完成认证、权限、查询或下载等延迟决策；重复完成返回稳定错误码。', { visibility: 'advanced' }),
  api('FBro事件_取消延续', 'LB_FBro_CancelEventContinuation', [{ name: '延续句柄', type: 'longLong' }], 'int', '取消尚未完成的受管事件延续。', { visibility: 'advanced' }),
  api('FBro_设置事件采样率', 'LB_FBro_SetEventSamplingRate', [{ name: '控件名', type: 'controlRef' }, { name: '事件名', type: 'wideString' }, { name: '每秒次数', type: 'int' }], 'int', '按浏览器和事件设置高频事件采样率；零表示暂停投递。'),
  api('FBro_绑定事件', 'LB_FBro_BindEvent', [{ name: '控件名', type: 'controlRef' }, { name: '事件名', type: 'wideString' }, { name: '处理器', type: 'handler', description: '必须使用 &处理器名' }], 'int', '动态绑定 FBro 事件处理器。', { example: 'FBro_绑定事件(FBro浏览器1, "BeforePopup", &$1)' }),
  api('FBro_读资源响应正文', 'LB_FBro_ResourceBodyBegin', [{ name: '控件名', type: 'controlRef' }, { name: '最大字节数', type: 'longLong' }, { name: '完成处理器', type: 'handler', description: '必须使用 &处理器名；只能在“资源响应到达”处理器中调用。' }], 'int', '在“资源响应到达”处理器执行期间，为当前资源安装有界正文捕获；完成后触发“资源响应正文到达”，通过 FBro_取事件字段读取 url、status_code、mime_type、received_bytes、truncated、error、body_text 和 body_base64。不会重新发起请求。', { example: 'FBro_读资源响应正文($1, 1048576, &$2)' })
];

const sessionEntries = [
  api('FBro会话_取Cookie', 'LB_FBro_GetCookies', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }], 'wideString', '读取指定 RequestContext 中的 Cookie。', { runtimeName: 'FBro_取Cookie' }),
  api('FBro会话_清空Cookie', 'LB_FBro_ClearCookies', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }], 'int', '清空指定地址 Cookie。', { runtimeName: 'FBro_清空Cookie' }),
  api('FBro会话_设置代理认证', 'LB_FBro_SetProxy', [{ name: '控件名', type: 'controlRef' }, { name: '代理地址', type: 'wideString' }, { name: '用户名', type: 'wideString' }, { name: '密码', type: 'wideString' }], 'int', '设置隔离会话代理及认证信息。'),
  api('FBro会话_异步取全部Cookie', 'LB_FBro_CookieVisitAllAsync', [{ name: '控件名', type: 'controlRef' }], 'longLong', '异步读取当前 RequestContext 的全部 Cookie，任务结果为 UTF-16 JSON 数组。'),
  api('FBro会话_异步取地址Cookie', 'LB_FBro_CookieVisitUrlAsync', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }, { name: '包含HttpOnly', type: 'int' }], 'longLong', '异步读取指定地址 Cookie，任务结果为 UTF-16 JSON 数组。'),
  api('FBro会话_异步设置Cookie', 'LB_FBro_CookieSetAsync', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }, { name: '名称', type: 'wideString' }, { name: '值', type: 'wideString' }, { name: '域', type: 'wideString' }, { name: '路径', type: 'wideString' }, { name: '安全', type: 'int' }, { name: '仅HTTP', type: 'int' }], 'longLong', '通过官方 CookieManager 异步设置 Cookie，并返回受管任务 ID。'),
  api('FBro会话_异步删除Cookie', 'LB_FBro_CookieDeleteAsync', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }, { name: '名称', type: 'wideString' }], 'longLong', '异步删除指定 Cookie；名称留空时删除该地址全部 Cookie。'),
  api('FBro会话_异步刷新Cookie存储', 'LB_FBro_CookieFlushAsync', [{ name: '控件名', type: 'controlRef' }], 'longLong', '异步请求 FBro 将 Cookie 写入持久化存储。'),
  api('FBro会话_异步清理缓存', 'LB_FBro_ClearCacheAsync', [{ name: '控件名', type: 'controlRef' }, { name: '来源', type: 'wideString' }, { name: '移除标志', type: 'int' }, { name: '配额标志', type: 'int' }], 'longLong', '异步清理当前浏览器实例指定来源的缓存数据。', { visibility: 'advanced' }),
  api('FBro会话_异步清理全局缓存', 'LB_FBro_ClearGlobalCacheAsync', [{ name: '来源', type: 'wideString' }, { name: '移除标志', type: 'int' }, { name: '配额标志', type: 'int' }], 'longLong', '异步清理所有 FBro 实例共享的全局缓存数据。', { visibility: 'advanced' }),
  api('FBro会话_是否全局上下文', 'LB_FBro_IsGlobalRequestContext', [{ name: '控件名', type: 'controlRef' }], 'int', '判断指定浏览器使用的 RequestContext 是否为全局上下文；独立 Profile 返回 0。', { visibility: 'advanced' }),
  api('FBro会话_取上下文缓存路径', 'LB_FBro_GetRequestContextCachePath', [{ name: '控件名', type: 'controlRef' }], 'wideString', '返回 RequestContext 缓存路径 JSON（global 与 cachePath 字段）；全局上下文同样返回其真实路径。', { visibility: 'advanced' }),
  api('FBro会话_创建上下文', 'LB_FBro_RequestContextCreateAsync', [{ name: '设置JSON', type: 'wideString' }], 'longLong', '运行时创建独立 RequestContext（设置 JSON：cachePath、persistSessionCookies、acceptLanguageList、cookieableSchemesList、cookieableSchemesExcludeDefaults）；任务结果包含 context 句柄，可传给 FBro会话_使用上下文重建。', { visibility: 'advanced' }),
  api('FBro会话_使用上下文重建', 'LB_FBro_RecreateBrowserWithContext', [{ name: '控件名', type: 'controlRef' }, { name: '上下文句柄', type: 'longLong' }], 'int', '让浏览器改用指定 RequestContext 原地重建：先关闭旧浏览器，关闭完成后自动以新上下文重启（指纹多 profile 场景）。', { visibility: 'advanced' })
];

const transferEntries = [
  api('FBro传输_开始下载', 'LB_FBro_StartDownload', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }], 'int', '使用当前浏览器会话开始下载。'),
  api('FBro下载_是否进行中', 'LB_FBro_DownloadItemIsInProgress', [{ name: '下载句柄', type: 'longLong' }], 'int', '判断下载是否仍在进行。', { visibility: 'advanced' }),
  api('FBro下载_是否完成', 'LB_FBro_DownloadItemIsComplete', [{ name: '下载句柄', type: 'longLong' }], 'int', '判断下载是否已完成。', { visibility: 'advanced' }),
  api('FBro下载_是否已取消', 'LB_FBro_DownloadItemIsCanceled', [{ name: '下载句柄', type: 'longLong' }], 'int', '判断下载是否已取消。', { visibility: 'advanced' }),
  api('FBro下载_取百分比', 'LB_FBro_DownloadItemGetPercentComplete', [{ name: '下载句柄', type: 'longLong' }], 'int', '取下载进度百分比（0~100）。', { visibility: 'advanced' }),
  api('FBro下载_取下载ID', 'LB_FBro_DownloadItemGetDownloadId', [{ name: '下载句柄', type: 'longLong' }], 'int', '取下载项标识。', { visibility: 'advanced' }),
  api('FBro下载_取速度', 'LB_FBro_DownloadItemGetCurrentSpeedBytes', [{ name: '下载句柄', type: 'longLong' }], 'longLong', '取当前下载速度（字节/秒）。', { visibility: 'advanced' }),
  api('FBro下载_取总长度', 'LB_FBro_DownloadItemGetTotalBytes', [{ name: '下载句柄', type: 'longLong' }], 'longLong', '取下载总字节数（未知为 0 或 -1）。', { visibility: 'advanced' }),
  api('FBro下载_取已接收字节', 'LB_FBro_DownloadItemGetReceivedBytes', [{ name: '下载句柄', type: 'longLong' }], 'longLong', '取已接收字节数。', { visibility: 'advanced' }),
  api('FBro下载_取开始时间', 'LB_FBro_DownloadItemGetStartTime', [{ name: '下载句柄', type: 'longLong' }], 'longLong', '取开始时间（Unix 时间戳秒）。', { visibility: 'advanced' }),
  api('FBro下载_取结束时间', 'LB_FBro_DownloadItemGetEndTime', [{ name: '下载句柄', type: 'longLong' }], 'longLong', '取结束时间（Unix 时间戳秒，未结束为 0）。', { visibility: 'advanced' }),
  api('FBro下载_取完整路径', 'LB_FBro_DownloadItemGetFullPath', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取下载文件的完整保存路径。', { visibility: 'advanced' }),
  api('FBro下载_取地址', 'LB_FBro_DownloadItemGetDownloadURL', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取下载地址。', { visibility: 'advanced' }),
  api('FBro下载_取原始地址', 'LB_FBro_DownloadItemGetDownloadOriginalUrl', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取重定向前的原始下载地址。', { visibility: 'advanced' }),
  api('FBro下载_取建议文件名', 'LB_FBro_DownloadItemGetSuggestedFileName', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取服务器建议的文件名。', { visibility: 'advanced' }),
  api('FBro下载_取MIME类型', 'LB_FBro_DownloadItemGetDownloadMimeType', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取下载内容的 MIME 类型。', { visibility: 'advanced' }),
  api('FBro下载_取内容处置', 'LB_FBro_DownloadItemGetContentDisposition', [{ name: '下载句柄', type: 'longLong' }], 'wideString', '取 Content-Disposition 响应头值。', { visibility: 'advanced' }),
  api('FBro传输_打印', 'LB_FBro_Print', [{ name: '控件名', type: 'controlRef' }], 'int', '打开当前浏览器页面的原生打印流程。'),
  api('FBro传输_异步生成PDF', 'LB_FBro_PrintToPdfAsync', [{ name: '控件名', type: 'controlRef' }, { name: '输出路径', type: 'wideString' }, { name: '设置JSON', type: 'wideString' }], 'longLong', '异步生成 PDF；设置使用 UTF-16 JSON，任务结果包含成功状态和绝对路径。'),
  api('FBro传输_生成PDF', 'LB_FBro_PrintToPdfSync', [{ name: '控件名', type: 'controlRef' }, { name: '输出路径', type: 'wideString' }, { name: '设置JSON', type: 'wideString' }], 'int', '同步生成 PDF 并等待完成（60 秒超时）；设置 JSON 传空文本使用默认，返回 1 表示文件已生成。', { visibility: 'advanced' }),
  api('FBro传输_异步打开文件对话框', 'LB_FBro_RunFileDialogAsync', [{ name: '控件名', type: 'controlRef' }, { name: '模式', type: 'int' }, { name: '标题', type: 'wideString' }, { name: '默认路径', type: 'wideString' }, { name: '筛选器JSON', type: 'wideString' }], 'longLong', '调用独立 STA Windows 安全文件对话框；模式为 0打开、1多选、2文件夹、3保存，任务返回 cancelled 和 paths UTF-16 JSON 字段。'),
  api('FBro传输_异步截图', 'LB_FBro_CaptureScreenshotAsync', [{ name: '控件名', type: 'controlRef' }, { name: '格式', type: 'wideString' }, { name: '质量', type: 'int' }, { name: '横坐标', type: 'int' }, { name: '纵坐标', type: 'int' }, { name: '宽度', type: 'int' }, { name: '高度', type: 'int' }, { name: '缩放', type: 'int' }, { name: '来自表面', type: 'bool' }, { name: '超出视口', type: 'bool' }], 'longLong', '通过 FBro VIP Page.captureScreenshot 异步截图；任务结果通过受管缓冲返回。')
];

const automationEntries = [
  api('FBro自动化_执行JS异步', 'LB_FBro_ExecuteJsAsync', [{ name: '控件名', type: 'controlRef' }, { name: '脚本', type: 'wideString' }], 'longLong', '异步执行 JavaScript 并返回受管任务 ID。', { visibility: 'advanced' }),
  api('FBro框架_取主框架', 'FBroHsBrowser_GetMainFrame', [{ name: '控件名', type: 'controlRef' }], 'longLong', '取得浏览器主框架的受管句柄。', { visibility: 'advanced' }),
  api('FBro框架_取焦点框架', 'FBroHsBrowser_GetFocusedFrame', [{ name: '控件名', type: 'controlRef' }], 'longLong', '取得当前焦点框架的受管句柄。', { visibility: 'advanced' }),
  api('FBro框架_按标识取框架', 'FBroHsBrowser_GetFrameById', [{ name: '控件名', type: 'controlRef' }, { name: '标识', type: 'wideString' }], 'longLong', '按官方字符串标识取得受管框架句柄。', { visibility: 'advanced' }),
  api('FBro框架_按名称取框架', 'FBroHsBrowser_GetFrameByName', [{ name: '控件名', type: 'controlRef' }, { name: '名称', type: 'wideString' }], 'longLong', '按框架名称取得受管框架句柄。', { visibility: 'advanced' }),
  api('FBro框架_取标识列表JSON', 'FBroHsBrowser_GetFrameIdentifiers', [{ name: '控件名', type: 'controlRef' }], 'wideString', '取得全部框架标识的 UTF-16 JSON 数组。', { visibility: 'advanced' }),
  api('FBro框架_取名称列表JSON', 'FBroHsBrowser_GetFrameNames', [{ name: '控件名', type: 'controlRef' }], 'wideString', '取得全部框架名称的 UTF-16 JSON 数组。', { visibility: 'advanced' }),
  api('FBro框架_是否有效', 'FBroHsBrowserFrame_IsValid', [{ name: '框架句柄', type: 'longLong' }], 'int', '检查受管框架是否仍有效。', { visibility: 'advanced' }),
  api('FBro框架_是否主框架', 'FBroHsBrowserFrame_IsMain', [{ name: '框架句柄', type: 'longLong' }], 'int', '检查是否为主框架。', { visibility: 'advanced' }),
  api('FBro框架_是否焦点框架', 'FBroHsBrowserFrame_IsFocused', [{ name: '框架句柄', type: 'longLong' }], 'int', '检查框架是否拥有焦点。', { visibility: 'advanced' }),
  api('FBro框架_取地址', 'FBroHsBrowserFrame_GetURL', [{ name: '框架句柄', type: 'longLong' }], 'wideString', '取得框架当前地址。', { visibility: 'advanced' }),
  api('FBro框架_取名称', 'FBroHsBrowserFrame_GetName', [{ name: '框架句柄', type: 'longLong' }], 'wideString', '取得框架名称。', { visibility: 'advanced' }),
  api('FBro框架_取标识', 'FBroHsBrowserFrame_GetIdentifier', [{ name: '框架句柄', type: 'longLong' }], 'wideString', '取得框架官方字符串标识。', { visibility: 'advanced' }),
  api('FBro框架_取父框架', 'FBroHsBrowserFrame_GetParent', [{ name: '框架句柄', type: 'longLong' }], 'longLong', '取得父框架受管句柄；主框架返回零。', { visibility: 'advanced' }),
  api('FBro框架_取浏览器实例', 'FBroHsBrowserFrame_GetBrowser', [{ name: '框架句柄', type: 'longLong' }], 'longLong', '取得框架所属的 LingBuilder 浏览器实例 ID。', { visibility: 'advanced' }),
  api('FBro框架_撤销', 'FBroHsBrowserFrame_Undo', [{ name: '框架句柄', type: 'longLong' }], 'int', '在框架中执行撤销。', { visibility: 'advanced' }),
  api('FBro框架_重做', 'FBroHsBrowserFrame_Redo', [{ name: '框架句柄', type: 'longLong' }], 'int', '在框架中执行重做。', { visibility: 'advanced' }),
  api('FBro框架_剪切', 'FBroHsBrowserFrame_Cut', [{ name: '框架句柄', type: 'longLong' }], 'int', '剪切框架当前选择。', { visibility: 'advanced' }),
  api('FBro框架_复制', 'FBroHsBrowserFrame_Copy', [{ name: '框架句柄', type: 'longLong' }], 'int', '复制框架当前选择。', { visibility: 'advanced' }),
  api('FBro框架_粘贴', 'FBroHsBrowserFrame_Paste', [{ name: '框架句柄', type: 'longLong' }], 'int', '在框架中粘贴。', { visibility: 'advanced' }),
  api('FBro框架_删除', 'FBroHsBrowserFrame_Delete', [{ name: '框架句柄', type: 'longLong' }], 'int', '删除框架当前选择。', { visibility: 'advanced' }),
  api('FBro框架_全选', 'FBroHsBrowserFrame_SelectAll', [{ name: '框架句柄', type: 'longLong' }], 'int', '全选框架内容。', { visibility: 'advanced' }),
  api('FBro框架_查看源代码', 'FBroHsBrowserFrame_ViewSource', [{ name: '框架句柄', type: 'longLong' }], 'int', '打开框架源代码查看器。', { visibility: 'advanced' }),
  api('FBro框架_载入地址', 'FBroHsBrowserFrame_LoadURL', [{ name: '框架句柄', type: 'longLong' }, { name: '地址', type: 'wideString' }], 'int', '让指定框架载入地址。', { visibility: 'advanced' }),
  api('FBro框架_执行JS', 'FBroHsBrowserFrame_ExecuteJavaScript', [{ name: '框架句柄', type: 'longLong' }, { name: '脚本', type: 'wideString' }, { name: '脚本地址', type: 'wideString' }, { name: '起始行', type: 'int' }], 'int', '在指定框架执行 JavaScript，不等待返回值。', { visibility: 'advanced' }),
  api('FBro框架_载入请求', 'LB_FBro_FrameLoadRequest', [{ name: '框架句柄', type: 'longLong' }, { name: '请求句柄', type: 'longLong' }], 'int', '让指定框架按受管请求对象载入（URL、方法、头与提交体）。', { visibility: 'advanced' }),
  api('FBro框架_发送进程消息', 'LB_FBro_FrameSendProcessMessage', [{ name: '框架句柄', type: 'longLong' }, { name: '目标进程', type: 'int' }, { name: '消息句柄', type: 'longLong' }], 'int', '向目标进程发送进程消息；目标进程 0=浏览器进程、1=渲染进程。', { visibility: 'advanced' }),
  api('FBro框架_创建URL请求', 'LB_FBro_FrameCreateUrlRequestAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '请求句柄', type: 'longLong' }], 'longLong', '在框架所属上下文中异步发起 URL 请求；任务结果包含 urlRequest 句柄与 status/error/cached 字段。', { visibility: 'advanced' }),
  api('FBro异步请求_发起', 'LB_FBro_UrlRequestStartAsync', [{ name: '控件名', type: 'controlRef' }, { name: '请求句柄', type: 'longLong' }], 'longLong', '使用指定浏览器会话上下文异步发起受管 URL 请求；任务结果包含 urlRequest 句柄、status、error 与 cached。', { visibility: 'advanced' }),
  api('FBro异步请求_取状态', 'LB_FBro_UrlRequestGetStatus', [{ name: 'URL请求句柄', type: 'longLong' }], 'int', '读取 URL 请求官方状态（1=未知 2=进行中 3=成功 4=失败）。', { visibility: 'advanced' }),
  api('FBro异步请求_取原请求', 'LB_FBro_UrlRequestGetRequestObject', [{ name: 'URL请求句柄', type: 'longLong' }], 'longLong', '取得 URL 请求对应的受管请求对象句柄。', { visibility: 'advanced' }),
  api('FBro填表_点击元素', 'LB_FBro_FrameTianBiaoClick', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'int', '按 CSS 选择器点击第 index 个匹配元素（从 0 起）。', { visibility: 'advanced' }),
  api('FBro填表_滚动到元素', 'LB_FBro_FrameTianBiaoScrollIntoView', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '滚到顶部', type: 'bool' }], 'int', '把匹配元素滚动到可视区域；滚到顶部为真时贴顶，否则尽量贴底。', { visibility: 'advanced' }),
  api('FBro填表_聚焦元素', 'LB_FBro_FrameTianBiaoSetFocus', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '是否聚焦', type: 'bool' }], 'int', '设置匹配元素的输入焦点。', { visibility: 'advanced' }),
  api('FBro填表_赋值', 'LB_FBro_FrameTianBiaoSetValue', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '值', type: 'wideString' }], 'int', '设置匹配元素的值（等效表单赋值）。', { visibility: 'advanced' }),
  api('FBro填表_取值', 'LB_FBro_FrameTianBiaoGetValueAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素的值；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_取坐标', 'LB_FBro_FrameTianBiaoGetPointAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素页面坐标；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置选择框', 'LB_FBro_FrameTianBiaoSetChecked', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '是否选中', type: 'bool' }], 'int', '设置匹配复选框/单选框的勾选状态（同步，发后即忘）。', { visibility: 'advanced' }),
  api('FBro填表_取选择框', 'LB_FBro_FrameTianBiaoGetCheckedAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素勾选状态；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置选择项', 'LB_FBro_FrameTianBiaoSetSelected', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '选项序号', type: 'int' }], 'int', '把匹配下拉框选中第选项序号个 option（从 0 起）。', { visibility: 'advanced' }),
  api('FBro填表_取选择项', 'LB_FBro_FrameTianBiaoGetSelectedAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配下拉框当前选中项序号；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置内文本', 'LB_FBro_FrameTianBiaoSetInnerText', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '文本', type: 'wideString' }], 'int', '设置匹配元素 innerText。', { visibility: 'advanced' }),
  api('FBro填表_取内文本', 'LB_FBro_FrameTianBiaoGetInnerTextAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素 innerText；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置外文本', 'LB_FBro_FrameTianBiaoSetOuterText', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '文本', type: 'wideString' }], 'int', '设置匹配元素 outerText。', { visibility: 'advanced' }),
  api('FBro填表_取外文本', 'LB_FBro_FrameTianBiaoGetOuterTextAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素 outerText；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置内代码', 'LB_FBro_FrameTianBiaoSetInnerHTML', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '代码文本', type: 'wideString' }], 'int', '设置匹配元素 innerHTML（富文本/标签结构）。', { visibility: 'advanced' }),
  api('FBro填表_取内代码', 'LB_FBro_FrameTianBiaoGetInnerHTMLAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素 innerHTML；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置外代码', 'LB_FBro_FrameTianBiaoSetOuterHTML', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '代码文本', type: 'wideString' }], 'int', '设置匹配元素 outerHTML（含元素自身标签）。', { visibility: 'advanced' }),
  api('FBro填表_取外代码', 'LB_FBro_FrameTianBiaoGetOuterHTMLAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '读取匹配元素 outerHTML；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_置属性', 'LB_FBro_FrameTianBiaoSetAttribute', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '属性名', type: 'wideString' }, { name: '值', type: 'wideString' }], 'int', '设置匹配元素的指定属性。', { visibility: 'advanced' }),
  api('FBro填表_取属性', 'LB_FBro_FrameTianBiaoGetAttributeAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '属性名', type: 'wideString' }], 'wideString', '读取匹配元素的指定属性；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_元素是否存在', 'LB_FBro_FrameTianBiaoHasAttributeAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }], 'wideString', '判断匹配元素是否存在；内部等待任务完成后返回 JSON 结果。', { visibility: 'advanced' }),
  api('FBro填表_触发事件', 'LB_FBro_FrameTianBiaoDispatchEvent', [{ name: '框架句柄', type: 'longLong' }, { name: '选择器', type: 'wideString' }, { name: '序号', type: 'int' }, { name: '事件名', type: 'wideString' }, { name: '按键代码', type: 'int' }], 'int', '在匹配元素上合成 DOM 事件；事件名如 onclick、ondblclick、keydown、change、input，按键代码回车传 13。', { visibility: 'advanced' }),
  api('FBro框架_取源码', 'LB_FBro_FrameGetSourceAsync', [{ name: '框架句柄', type: 'longLong' }], 'longLong', '异步取框架完整 HTML 源码；用 FBro任务_等待 + FBro任务_取缓冲 取 UTF-8 字节缓冲，再 FBro缓冲_保存文件 或 FBro缓冲_转文本。', { visibility: 'advanced' }),
  api('FBro框架_取文本', 'LB_FBro_FrameGetTextAsync', [{ name: '框架句柄', type: 'longLong' }], 'longLong', '异步取框架可见文本；用 FBro任务_等待 + FBro任务_取缓冲 取 UTF-8 字节缓冲，再 FBro缓冲_转文本。', { visibility: 'advanced' }),
  api('FBro框架_遍历DOM', 'LB_FBro_FrameVisitDomAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '最大深度', type: 'int' }, { name: '最大节点数', type: 'int' }], 'longLong', '按官方 VisitDOM 遍历框架 DOM 并序列化为受管快照；内部等待任务完成，返回快照句柄（0=失败），节点用 FBro遍历_* 按序号访问；深度/节点数传 0 使用默认值（16/4000）。', { visibility: 'advanced' }),
  api('FBro遍历_取标题', 'LB_FBro_DomGetTitle', [{ name: '快照句柄', type: 'longLong' }], 'wideString', '读取 DOM 快照对应的页面标题。', { visibility: 'advanced' }),
  api('FBro遍历_取基础地址', 'LB_FBro_DomGetBaseUrl', [{ name: '快照句柄', type: 'longLong' }], 'wideString', '读取 DOM 快照对应文档的基础地址。', { visibility: 'advanced' }),
  api('FBro遍历_取节点数', 'LB_FBro_DomGetNodeCount', [{ name: '快照句柄', type: 'longLong' }], 'int', '返回 DOM 快照捕获的节点总数。', { visibility: 'advanced' }),
  api('FBro遍历_取节点类型', 'LB_FBro_DomGetNodeType', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'int', '读取节点官方类型（0 未定义、1 元素、2 文本、3 注释等）。', { visibility: 'advanced' }),
  api('FBro遍历_取节点路径', 'LB_FBro_DomGetNodePath', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'wideString', '读取节点路径 JSON（如 [0,2,1]，从 Body 起逐层子序号）；可传给按路径写回命令。', { visibility: 'advanced' }),
  api('FBro遍历_取节点名称', 'LB_FBro_DomGetNodeName', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'wideString', '读取节点名称（元素标签名小写或特殊节点名）。', { visibility: 'advanced' }),
  api('FBro遍历_取节点值', 'LB_FBro_DomGetNodeValue', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'wideString', '读取节点值（文本/注释节点内容）。', { visibility: 'advanced' }),
  api('FBro遍历_取节点内部文本', 'LB_FBro_DomGetNodeInnerText', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'wideString', '读取元素的 innerText（超长截断到 4096 字符）。', { visibility: 'advanced' }),
  api('FBro遍历_取节点属性数', 'LB_FBro_DomGetNodeAttributeCount', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }], 'int', '返回元素节点捕获的属性个数。', { visibility: 'advanced' }),
  api('FBro遍历_取节点属性名', 'LB_FBro_DomGetNodeAttributeName', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }, { name: '属性序号', type: 'int' }], 'wideString', '按序号读取元素属性名。', { visibility: 'advanced' }),
  api('FBro遍历_取节点属性值', 'LB_FBro_DomGetNodeAttributeValue', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }, { name: '属性序号', type: 'int' }], 'wideString', '按序号读取元素属性值。', { visibility: 'advanced' }),
  api('FBro遍历_取节点属性', 'LB_FBro_DomGetNodeAttributeByName', [{ name: '快照句柄', type: 'longLong' }, { name: '节点序号', type: 'int' }, { name: '属性名', type: 'wideString' }], 'wideString', '按名称读取元素属性值；不存在返回空文本。', { visibility: 'advanced' }),
  api('FBro遍历_取焦点节点路径', 'LB_FBro_DomGetFocusedPath', [{ name: '快照句柄', type: 'longLong' }], 'wideString', '读取遍历当时的焦点节点路径 JSON；无焦点节点返回空。', { visibility: 'advanced' }),
  api('FBro遍历_按路径取序号', 'LB_FBro_DomFindNodeByPath', [{ name: '快照句柄', type: 'longLong' }, { name: '路径JSON', type: 'wideString' }], 'int', '把节点路径 JSON 换算成节点序号；未找到返回 -1。', { visibility: 'advanced' }),
  api('FBro遍历_按路径设属性', 'LB_FBro_DomSetAttributeByPathAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '路径JSON', type: 'wideString' }, { name: '属性名', type: 'wideString' }, { name: '属性值', type: 'wideString' }], 'int', '重新遍历定位路径节点并设置元素属性；内部等待任务完成，返回 1=成功。', { visibility: 'advanced' }),
  api('FBro遍历_按路径赋值', 'LB_FBro_DomSetValueByPathAsync', [{ name: '框架句柄', type: 'longLong' }, { name: '路径JSON', type: 'wideString' }, { name: '值', type: 'wideString' }], 'int', '重新遍历定位路径节点并写入节点值（表单赋值语义）；内部等待任务完成，返回 1=成功。', { visibility: 'advanced' })
];

const objectEntries = [
  api('FBro任务_取状态', 'LB_FBro_TaskGetStatus', [{ name: '任务ID', type: 'longLong' }], 'int', '查询异步任务状态。', { visibility: 'advanced' }),
  api('FBro任务_取结果', 'LB_FBro_TaskGetResult', [{ name: '任务ID', type: 'longLong' }], 'wideString', '取得异步任务 UTF-16 结果。', { visibility: 'advanced' }),
  api('FBro任务_取错误', 'LB_FBro_TaskGetError', [{ name: '任务ID', type: 'longLong' }], 'wideString', '取得异步任务中文错误。', { visibility: 'advanced' }),
  api('FBro任务_等待', 'LB_FBro_TaskWait', [{ name: '任务ID', type: 'longLong' }, { name: '超时毫秒', type: 'int' }], 'int', '等待任务进入完成、失败或取消状态，最长十分钟。', { visibility: 'advanced' }),
  api('FBro任务_取对象', 'LB_FBro_TaskGetObject', [{ name: '任务ID', type: 'longLong' }], 'longLong', '取得已完成任务返回的受管对象句柄。', { visibility: 'advanced' }),
  api('FBro任务_取缓冲', 'LB_FBro_TaskGetBuffer', [{ name: '任务ID', type: 'longLong' }], 'longLong', '取得已完成任务返回的受管二进制缓冲句柄。', { visibility: 'advanced' }),
  api('FBro任务_取消', 'LB_FBro_TaskCancel', [{ name: '任务ID', type: 'longLong' }], 'int', '取消尚未完成的任务。', { visibility: 'advanced' }),
  api('FBro任务_释放', 'LB_FBro_TaskRelease', [{ name: '任务ID', type: 'longLong' }], 'int', '释放任务句柄。', { visibility: 'advanced' }),
  api('FBro缓冲_从文本', 'LB_FBro_BufferCreate', [{ name: '文本', type: 'wideString' }], 'longLong', '把 UTF-16 文本复制到受管二进制缓冲并返回句柄。', { visibility: 'advanced' }),
  api('FBro缓冲_取大小', 'LB_FBro_BufferGetSize', [{ name: '缓冲句柄', type: 'longLong' }], 'longLong', '取得受管缓冲字节数。', { visibility: 'advanced' }),
  api('FBro缓冲_转十六进制', 'LB_FBro_BufferToHex', [{ name: '缓冲句柄', type: 'longLong' }], 'wideString', '把受管缓冲转换为十六进制文本。', { visibility: 'advanced' }),
  api('FBro缓冲_保存文件', 'LB_FBro_BufferSaveFile', [{ name: '缓冲句柄', type: 'longLong' }, { name: '路径', type: 'wideString' }], 'int', '保存受管缓冲到文件。', { visibility: 'advanced' }),
  api('FBro缓冲_释放', 'LB_FBro_BufferRelease', [{ name: '缓冲句柄', type: 'longLong' }], 'int', '释放受管缓冲句柄。', { visibility: 'advanced' }),
  api('FBro缓冲_转文本', 'LB_FBro_BufferToText', [{ name: '缓冲句柄', type: 'longLong' }], 'wideString', '按 UTF-8 解码受管缓冲并返回文本（单次上限约 16K 字符；大内容请用 FBro缓冲_保存文件）。', { visibility: 'advanced' }),
  api('FBro缓冲_是否有效', 'LB_FBro_IsBufferValid', [{ name: '缓冲句柄', type: 'longLong' }], 'int', '检查受管缓冲句柄是否仍然有效。', { visibility: 'advanced' }),
  api('FBro工具_创建数据URI', 'LB_FBro_CreateDataUri', [{ name: 'MIME类型', type: 'wideString' }, { name: '数据', type: 'wideString' }], 'wideString', '把文本数据编码为 data: URI；MIME 类型如 image/png、text/html。', { visibility: 'advanced' }),
  api('FBro请求_创建', 'LB_FBro_RequestCreate', [], 'longLong', '创建受管 HTTP 请求对象并返回句柄；可用 FBro框架_载入请求 或 FBro异步请求_发起 使用。', { visibility: 'advanced' }),
  api('FBro请求_取地址', 'LB_FBro_RequestGetUrl', [{ name: '请求句柄', type: 'longLong' }], 'wideString', '读取请求对象当前地址。', { visibility: 'advanced' }),
  api('FBro请求_取方法', 'LB_FBro_RequestGetMethod', [{ name: '请求句柄', type: 'longLong' }], 'wideString', '读取请求对象当前的 HTTP 方法（GET、POST 等）。', { visibility: 'advanced' }),
  api('FBro请求_设置地址', 'LB_FBro_RequestSetUrl', [{ name: '请求句柄', type: 'longLong' }, { name: '地址', type: 'wideString' }], 'int', '设置请求对象地址。', { visibility: 'advanced' }),
  api('FBro请求_设置方法', 'LB_FBro_RequestSetMethod', [{ name: '请求句柄', type: 'longLong' }, { name: '方法', type: 'wideString' }], 'int', '设置请求方法，如 GET、POST。', { visibility: 'advanced' }),
  api('FBro请求_设置引用页', 'LB_FBro_RequestSetReferrer', [{ name: '请求句柄', type: 'longLong' }, { name: '引用页', type: 'wideString' }, { name: '策略', type: 'int' }], 'int', '设置请求引用页与策略（0=清除 1=省略 2=降级 3=始终 4=源）。', { visibility: 'advanced' }),
  api('FBro请求_设置头映射JSON', 'LB_FBro_RequestSetHeaderMapJson', [{ name: '请求句柄', type: 'longLong' }, { name: '头列表JSON', type: 'wideString' }], 'int', '按 [{"name":"...","value":"..."}] 数组设置请求头；不覆盖未列出的已有头。', { visibility: 'advanced' }),
  api('FBro请求_组合设置', 'LB_FBro_RequestComposeSet', [{ name: '请求句柄', type: 'longLong' }, { name: '地址', type: 'wideString' }, { name: '方法', type: 'wideString' }, { name: '提交数据句柄', type: 'longLong' }, { name: '头列表JSON', type: 'wideString' }], 'int', '一次性设置地址、方法、提交体与头；提交数据句柄传 0 跳过，头 JSON 传空跳过。', { visibility: 'advanced' }),
  api('FBro提交数据_创建', 'LB_FBro_PostDataCreate', [], 'longLong', '创建受管提交数据对象（POST 请求体）。', { visibility: 'advanced' }),
  api('FBro提交数据_添加元素', 'LB_FBro_PostDataAddElement', [{ name: '提交数据句柄', type: 'longLong' }, { name: '元素句柄', type: 'longLong' }], 'int', '向提交数据对象追加一个提交元素。', { visibility: 'advanced' }),
  api('FBro提交数据_取元素数量', 'LB_FBro_PostDataGetElementCount', [{ name: '提交数据句柄', type: 'longLong' }], 'int', '取得提交数据对象中的元素数量。', { visibility: 'advanced' }),
  api('FBro提交数据_取元素句柄列表JSON', 'LB_FBro_PostDataGetElementHandlesJson', [{ name: '提交数据句柄', type: 'longLong' }], 'wideString', '取得全部提交元素并注册为受管句柄，返回 JSON 数组。', { visibility: 'advanced' }),
  api('FBro提交数据_创建元素', 'LB_FBro_PostDataElementCreate', [], 'longLong', '创建受管提交元素。', { visibility: 'advanced' }),
  api('FBro提交数据_元素设字节', 'LB_FBro_PostDataElementSetBytes', [{ name: '元素句柄', type: 'longLong' }, { name: '文本', type: 'wideString' }], 'int', '把元素内容设为 UTF-8 字节（按文本传入）。', { visibility: 'advanced' }),
  api('FBro提交数据_元素取字节大小', 'LB_FBro_PostDataElementGetBytesCount', [{ name: '元素句柄', type: 'longLong' }], 'int', '取得元素字节大小。', { visibility: 'advanced' }),
  api('FBro提交数据_元素取文本', 'LB_FBro_PostDataElementGetText', [{ name: '元素句柄', type: 'longLong' }], 'wideString', '按 UTF-8 读取元素字节并返回文本。', { visibility: 'advanced' }),
  api('FBro消息_创建', 'LB_FBro_ProcessMessageCreate', [{ name: '消息名', type: 'wideString' }], 'longLong', '创建受管进程消息对象。', { visibility: 'advanced' }),
  api('FBro消息_取参数列表', 'LB_FBro_ProcessMessageGetArgumentList', [{ name: '消息句柄', type: 'longLong' }], 'longLong', '取得消息参数列表的受管 List 句柄；可用 FBro列表_* 读写。', { visibility: 'advanced' }),
  api('FBro菜单_添加项', 'LB_FBro_MenuModelAddItem', [{ name: '菜单句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '标题', type: 'wideString' }], 'int', '向右键菜单模型添加菜单项；仅可在“上下文菜单显示前”事件处理期内使用。', { visibility: 'advanced' }),
  api('FBro菜单_添加子菜单', 'LB_FBro_MenuModelAddSubMenu', [{ name: '菜单句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '标题', type: 'wideString' }], 'longLong', '向右键菜单模型添加子菜单并返回其受管句柄；仅可在事件处理期内使用。', { visibility: 'advanced' }),
  api('FBro菜单_设置加速键', 'LB_FBro_MenuModelSetAccelerator', [{ name: '菜单句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '键码', type: 'int' }, { name: 'Shift', type: 'bool' }, { name: 'Ctrl', type: 'bool' }, { name: 'Alt', type: 'bool' }], 'int', '为菜单项设置加速键组合。', { visibility: 'advanced' }),
  api('FBro菜单_取颜色', 'LB_FBro_MenuModelGetColor', [{ name: '菜单句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '颜色类型', type: 'int' }], 'wideString', '读取菜单项颜色，返回 red/green/blue/alpha JSON。', { visibility: 'advanced' }),
  api('FBro右键参数_取X', 'LB_FBro_ContextMenuParamsGetX', [{ name: '参数句柄', type: 'longLong' }], 'int', '读取右键菜单弹出坐标 X；仅可在事件处理期内使用。', { visibility: 'advanced' }),
  api('FBro右键参数_取Y', 'LB_FBro_ContextMenuParamsGetY', [{ name: '参数句柄', type: 'longLong' }], 'int', '读取右键菜单弹出坐标 Y；仅可在事件处理期内使用。', { visibility: 'advanced' }),
  api('FBro右键参数_取类型标志', 'LB_FBro_ContextMenuParamsGetTypeFlags', [{ name: '参数句柄', type: 'longLong' }], 'int', '读取右键菜单上下文类型标志位（TypeFlags 位掩码）；仅可在事件处理期内使用。', { visibility: 'advanced' }),
  api('FBro菜单_清空', 'LB_FBro_MenuModelClear', [{ name: '句柄', type: 'longLong' }], 'int', '清空菜单全部项。', { visibility: 'advanced' }),
  api('FBro菜单_取数量', 'LB_FBro_MenuModelGetCount', [{ name: '句柄', type: 'longLong' }], 'int', '取菜单项数量。', { visibility: 'advanced' }),
  api('FBro菜单_添加分隔栏', 'LB_FBro_MenuModelAddSeparator', [{ name: '句柄', type: 'longLong' }], 'int', '在菜单末尾添加分隔栏。', { visibility: 'advanced' }),
  api('FBro菜单_添加复选项', 'LB_FBro_MenuModelAddCheckItem', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '标签', type: 'wideString' }], 'int', '添加带勾选状态的菜单项。', { visibility: 'advanced' }),
  api('FBro菜单_添加单选项', 'LB_FBro_MenuModelAddRadioItem', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '标签', type: 'wideString' }, { name: '分组ID', type: 'int' }], 'int', '添加单选菜单项；同分组ID互斥。', { visibility: 'advanced' }),
  api('FBro菜单_删除项', 'LB_FBro_MenuModelRemove', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '按命令ID删除菜单项。', { visibility: 'advanced' }),
  api('FBro菜单_取标签', 'LB_FBro_MenuModelGetLabel', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'wideString', '取菜单项标签文本。', { visibility: 'advanced' }),
  api('FBro菜单_置标签', 'LB_FBro_MenuModelSetLabel', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '标签', type: 'wideString' }], 'int', '设置菜单项标签文本。', { visibility: 'advanced' }),
  api('FBro菜单_取类型', 'LB_FBro_MenuModelGetType', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '取菜单项类型（命令/复选/单选/分隔栏/子菜单）。', { visibility: 'advanced' }),
  api('FBro菜单_取分组', 'LB_FBro_MenuModelGetGroup', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '取单选项分组ID。', { visibility: 'advanced' }),
  api('FBro菜单_置分组', 'LB_FBro_MenuModelSetGroup', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '分组ID', type: 'int' }], 'int', '设置单选项分组ID。', { visibility: 'advanced' }),
  api('FBro菜单_取子菜单', 'LB_FBro_MenuModelGetSubMenu', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'longLong', '取命令ID对应的子菜单句柄，可继续用 FBro菜单_* 操作。', { visibility: 'advanced' }),
  api('FBro菜单_是否可见', 'LB_FBro_MenuModelIsVisible', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '判断菜单项是否可见。', { visibility: 'advanced' }),
  api('FBro菜单_置可见', 'LB_FBro_MenuModelSetVisible', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '是否可见', type: 'bool' }], 'int', '设置菜单项可见性。', { visibility: 'advanced' }),
  api('FBro菜单_是否启用', 'LB_FBro_MenuModelIsEnabled', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '判断菜单项是否可用（非置灰）。', { visibility: 'advanced' }),
  api('FBro菜单_置启用', 'LB_FBro_MenuModelSetEnabled', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '是否启用', type: 'bool' }], 'int', '设置菜单项可用/置灰。', { visibility: 'advanced' }),
  api('FBro菜单_是否选中', 'LB_FBro_MenuModelIsChecked', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '判断复选/单选项勾选状态。', { visibility: 'advanced' }),
  api('FBro菜单_置选中', 'LB_FBro_MenuModelSetChecked', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '是否选中', type: 'bool' }], 'int', '设置复选/单选项勾选状态。', { visibility: 'advanced' }),
  api('FBro菜单_按序置选中', 'LB_FBro_MenuModelSetCheckedAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }, { name: '是否选中', type: 'bool' }], 'int', '按序号设置勾选状态。', { visibility: 'advanced' }),
  api('FBro菜单_是否有加速键', 'LB_FBro_MenuModelHasAccelerator', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '判断菜单项是否设置了加速键。', { visibility: 'advanced' }),
  api('FBro菜单_按序是否有加速键', 'LB_FBro_MenuModelHasAcceleratorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }], 'int', '按序号判断是否设置了加速键。', { visibility: 'advanced' }),
  api('FBro菜单_按序设置加速键', 'LB_FBro_MenuModelSetAcceleratorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }, { name: '键码', type: 'int' }, { name: '是否Shift', type: 'bool' }, { name: '是否Ctrl', type: 'bool' }, { name: '是否Alt', type: 'bool' }], 'int', '按序号设置加速键组合。', { visibility: 'advanced' }),
  api('FBro菜单_移除加速键', 'LB_FBro_MenuModelRemoveAccelerator', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'int', '移除菜单项加速键。', { visibility: 'advanced' }),
  api('FBro菜单_按序移除加速键', 'LB_FBro_MenuModelRemoveAcceleratorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }], 'int', '按序号移除加速键。', { visibility: 'advanced' }),
  api('FBro菜单_取加速键', 'LB_FBro_MenuModelGetAccelerator', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }], 'wideString', '取菜单项加速键，返回 {"key","shift","ctrl","alt"} JSON。', { visibility: 'advanced' }),
  api('FBro菜单_按序取加速键', 'LB_FBro_MenuModelGetAcceleratorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }], 'wideString', '按序号取加速键，返回 JSON。', { visibility: 'advanced' }),
  api('FBro菜单_置颜色', 'LB_FBro_MenuModelSetColor', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '颜色类型', type: 'int' }, { name: 'Alpha', type: 'int' }, { name: 'Red', type: 'int' }, { name: 'Green', type: 'int' }, { name: 'Blue', type: 'int' }], 'int', '设置菜单项文字/悬停等颜色（颜色类型参考菜单颜色类型常量）。', { visibility: 'advanced' }),
  api('FBro菜单_按序置颜色', 'LB_FBro_MenuModelSetColorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }, { name: '颜色类型', type: 'int' }, { name: 'Alpha', type: 'int' }, { name: 'Red', type: 'int' }, { name: 'Green', type: 'int' }, { name: 'Blue', type: 'int' }], 'int', '按序号设置颜色。', { visibility: 'advanced' }),
  api('FBro菜单_按序取颜色', 'LB_FBro_MenuModelGetColorAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }, { name: '颜色类型', type: 'int' }], 'wideString', '按序号取颜色，返回 {"red","green","blue","alpha"} JSON。', { visibility: 'advanced' }),
  api('FBro菜单_置字体', 'LB_FBro_MenuModelSetFontList', [{ name: '句柄', type: 'longLong' }, { name: '命令ID', type: 'int' }, { name: '字体列表', type: 'wideString' }], 'int', '设置菜单项字体（CSS 字体列表格式）。', { visibility: 'advanced' }),
  api('FBro菜单_按序置字体', 'LB_FBro_MenuModelSetFontListAt', [{ name: '句柄', type: 'longLong' }, { name: '序号', type: 'int' }, { name: '字体列表', type: 'wideString' }], 'int', '按序号设置字体。', { visibility: 'advanced' }),
  api('FBro右键参数_取链接地址', 'LB_FBro_ContextMenuParamsGetLinkUrl', [{ name: '句柄', type: 'longLong' }], 'wideString', '取右键目标链接地址。', { visibility: 'advanced' }),
  api('FBro右键参数_取完整链接地址', 'LB_FBro_ContextMenuParamsGetUnfilteredLinkUrl', [{ name: '句柄', type: 'longLong' }], 'wideString', '取未过滤的完整链接地址。', { visibility: 'advanced' }),
  api('FBro右键参数_取源地址', 'LB_FBro_ContextMenuParamsGetSourceUrl', [{ name: '句柄', type: 'longLong' }], 'wideString', '取媒体/图片等元素源地址。', { visibility: 'advanced' }),
  api('FBro右键参数_取页面地址', 'LB_FBro_ContextMenuParamsGetPageUrl', [{ name: '句柄', type: 'longLong' }], 'wideString', '取右键所在页面地址。', { visibility: 'advanced' }),
  api('FBro右键参数_取框架编码', 'LB_FBro_ContextMenuParamsGetFrameCharset', [{ name: '句柄', type: 'longLong' }], 'wideString', '取右键所在框架的网页编码。', { visibility: 'advanced' }),
  api('FBro右键参数_取框架地址', 'LB_FBro_ContextMenuParamsGetFrameUrl', [{ name: '句柄', type: 'longLong' }], 'wideString', '取右键所在框架地址。', { visibility: 'advanced' }),
  api('FBro右键参数_是否有图片', 'LB_FBro_ContextMenuParamsHasImageContents', [{ name: '句柄', type: 'longLong' }], 'int', '判断右键目标是否含图片内容。', { visibility: 'advanced' }),
  api('FBro右键参数_取媒体类型', 'LB_FBro_ContextMenuParamsGetMediaType', [{ name: '句柄', type: 'longLong' }], 'int', '取右键目标媒体类型。', { visibility: 'advanced' }),
  api('FBro右键参数_取媒体状态标志', 'LB_FBro_ContextMenuParamsGetMediaStateFlags', [{ name: '句柄', type: 'longLong' }], 'int', '取媒体状态标志（可播放/可暂停/可静音等）。', { visibility: 'advanced' }),
  api('FBro右键参数_取选择文本', 'LB_FBro_ContextMenuParamsGetSelectionText', [{ name: '句柄', type: 'longLong' }], 'wideString', '取当前选中的文本。', { visibility: 'advanced' }),
  api('FBro右键参数_取错误单词', 'LB_FBro_ContextMenuParamsGetMisspelledWord', [{ name: '句柄', type: 'longLong' }], 'wideString', '取拼写检查命中的错误单词。', { visibility: 'advanced' }),
  api('FBro右键参数_取字典建议', 'LB_FBro_ContextMenuParamsGetDictionarySuggestions', [{ name: '句柄', type: 'longLong' }], 'wideString', '取拼写建议，返回字符串数组 JSON。', { visibility: 'advanced' }),
  api('FBro右键参数_是否可编辑', 'LB_FBro_ContextMenuParamsIsEditable', [{ name: '句柄', type: 'longLong' }], 'int', '判断右键目标是否为可编辑元素。', { visibility: 'advanced' }),
  api('FBro右键参数_是否启用拼写检查', 'LB_FBro_ContextMenuParamsIsSpellCheckEnabled', [{ name: '句柄', type: 'longLong' }], 'int', '判断拼写检查是否启用。', { visibility: 'advanced' }),
  api('FBro右键参数_取编辑状态标志', 'LB_FBro_ContextMenuParamsGetEditStateFlags', [{ name: '句柄', type: 'longLong' }], 'int', '取编辑状态标志（可撤销/可重做/可剪切/可粘贴等）。', { visibility: 'advanced' }),
  api('FBro右键参数_是否自定义菜单', 'LB_FBro_ContextMenuParamsIsCustomMenu', [{ name: '句柄', type: 'longLong' }], 'int', '判断是否为自定义菜单请求。', { visibility: 'advanced' }),
  api('FBro响应_创建', 'LB_FBro_ResponseCreate', [], 'longLong', '创建自定义响应对象（配合自定义资源处理器使用），用完可 FBro对象_释放。', { visibility: 'advanced' }),
  api('FBro响应_是否只读', 'LB_FBro_ResponseIsReadOnly', [{ name: '响应句柄', type: 'longLong' }], 'int', '判断响应是否只读（事件中收到的响应在改写场景外通常只读）。', { visibility: 'advanced' }),
  api('FBro响应_取错误', 'LB_FBro_ResponseGetError', [{ name: '响应句柄', type: 'longLong' }], 'int', '取响应错误码。', { visibility: 'advanced' }),
  api('FBro响应_置错误', 'LB_FBro_ResponseSetError', [{ name: '响应句柄', type: 'longLong' }, { name: '错误码', type: 'int' }], 'int', '设置响应错误码。', { visibility: 'advanced' }),
  api('FBro响应_取状态码', 'LB_FBro_ResponseGetStatus', [{ name: '响应句柄', type: 'longLong' }], 'int', '取 HTTP 状态码。', { visibility: 'advanced' }),
  api('FBro响应_置状态码', 'LB_FBro_ResponseSetStatus', [{ name: '响应句柄', type: 'longLong' }, { name: '状态码', type: 'int' }], 'int', '设置 HTTP 状态码。', { visibility: 'advanced' }),
  api('FBro响应_取状态文本', 'LB_FBro_ResponseGetStatusText', [{ name: '响应句柄', type: 'longLong' }], 'wideString', '取状态文本（如 OK、Not Found）。', { visibility: 'advanced' }),
  api('FBro响应_置状态文本', 'LB_FBro_ResponseSetStatusText', [{ name: '响应句柄', type: 'longLong' }, { name: '状态文本', type: 'wideString' }], 'int', '设置状态文本。', { visibility: 'advanced' }),
  api('FBro响应_取MIME类型', 'LB_FBro_ResponseGetMimeType', [{ name: '响应句柄', type: 'longLong' }], 'wideString', '取响应 MIME 类型。', { visibility: 'advanced' }),
  api('FBro响应_置MIME类型', 'LB_FBro_ResponseSetMimeType', [{ name: '响应句柄', type: 'longLong' }, { name: 'MIME类型', type: 'wideString' }], 'int', '设置响应 MIME 类型。', { visibility: 'advanced' }),
  api('FBro响应_取字符集', 'LB_FBro_ResponseGetCharset', [{ name: '响应句柄', type: 'longLong' }], 'wideString', '取响应字符集。', { visibility: 'advanced' }),
  api('FBro响应_置字符集', 'LB_FBro_ResponseSetCharset', [{ name: '响应句柄', type: 'longLong' }, { name: '字符集', type: 'wideString' }], 'int', '设置响应字符集。', { visibility: 'advanced' }),
  api('FBro响应_取地址', 'LB_FBro_ResponseGetURL', [{ name: '响应句柄', type: 'longLong' }], 'wideString', '取响应地址。', { visibility: 'advanced' }),
  api('FBro响应_置地址', 'LB_FBro_ResponseSetURL', [{ name: '响应句柄', type: 'longLong' }, { name: '地址', type: 'wideString' }], 'int', '设置响应地址。', { visibility: 'advanced' }),
  api('FBro响应_取协议头', 'LB_FBro_ResponseGetHeaderByName', [{ name: '响应句柄', type: 'longLong' }, { name: '头名', type: 'wideString' }], 'wideString', '按名称取响应协议头。', { visibility: 'advanced' }),
  api('FBro响应_置协议头', 'LB_FBro_ResponseSetHeaderByName', [{ name: '响应句柄', type: 'longLong' }, { name: '头名', type: 'wideString' }, { name: '值', type: 'wideString' }, { name: '覆盖同名', type: 'bool' }], 'int', '按名称设置响应协议头。', { visibility: 'advanced' }),
  api('FBro响应_取协议头映射JSON', 'LB_FBro_ResponseGetHeaderMap', [{ name: '响应句柄', type: 'longLong' }], 'wideString', '取全部协议头，返回 {"名":"值"} JSON。', { visibility: 'advanced' }),
  api('FBro响应_设置协议头映射JSON', 'LB_FBro_ResponseSetHeaderMapJson', [{ name: '响应句柄', type: 'longLong' }, { name: '协议头JSON', type: 'wideString' }, { name: '清除原有', type: 'bool' }], 'int', '按 [{"name":..,"value":..}] JSON 批量设置协议头。', { visibility: 'advanced' }),
  api('FBro响应_删除协议头', 'LB_FBro_ResponseDeleteHeaderMap', [{ name: '响应句柄', type: 'longLong' }, { name: '头名', type: 'wideString' }], 'int', '按名称删除协议头。', { visibility: 'advanced' }),
  api('FBro对象_取类型', 'LB_FBro_ObjectGetType', [{ name: '对象句柄', type: 'longLong' }], 'int', '取得受管对象注册表类型。', { visibility: 'advanced' }),
  api('FBro对象_释放', 'LB_FBro_ObjectRelease', [{ name: '对象句柄', type: 'longLong' }], 'int', '释放受管对象；重复释放返回稳定错误码。', { visibility: 'advanced' }),

  api('FBro值_创建', 'FBroHsValue_Create', [], 'longLong', '创建受管 Value 对象并返回不透明句柄。', { visibility: 'advanced' }),
  api('FBro值_是否有效', 'FBroHsValue_IsValid', [{ name: '值句柄', type: 'longLong' }], 'int', '检查 Value 对象是否有效。', { visibility: 'advanced' }),
  api('FBro值_是否被拥有', 'FBroHsValue_IsOwned', [{ name: '值句柄', type: 'longLong' }], 'int', '检查 Value 对象是否已归属于其它容器。', { visibility: 'advanced' }),
  api('FBro值_是否只读', 'FBroHsValue_IsReadOnly', [{ name: '值句柄', type: 'longLong' }], 'int', '检查 Value 对象是否只读。', { visibility: 'advanced' }),
  api('FBro值_是否同一对象', 'FBroHsValue_IsSame', [{ name: '值句柄', type: 'longLong' }, { name: '另一值句柄', type: 'longLong' }], 'int', '检查两个 Value 句柄是否引用同一官方对象。', { visibility: 'advanced' }),
  api('FBro值_是否相等', 'FBroHsValue_IsEqual', [{ name: '值句柄', type: 'longLong' }, { name: '另一值句柄', type: 'longLong' }], 'int', '比较两个 Value 的内容。', { visibility: 'advanced' }),
  api('FBro值_复制', 'FBroHsValue_Copy', [{ name: '值句柄', type: 'longLong' }], 'longLong', '复制 Value 并返回独立受管句柄。', { visibility: 'advanced' }),
  api('FBro值_取类型', 'FBroHsValue_GetType', [{ name: '值句柄', type: 'longLong' }], 'int', '取得 Value 的官方值类型。', { visibility: 'advanced' }),
  api('FBro值_取逻辑', 'FBroHsValue_GetBool', [{ name: '值句柄', type: 'longLong' }], 'int', '读取逻辑值。', { visibility: 'advanced' }),
  api('FBro值_取整数', 'FBroHsValue_GetInt', [{ name: '值句柄', type: 'longLong' }], 'int', '读取整数值。', { visibility: 'advanced' }),
  api('FBro值_取小数', 'FBroHsValue_GetDouble', [{ name: '值句柄', type: 'longLong' }], 'double', '读取小数值。', { visibility: 'advanced' }),
  api('FBro值_取文本', 'FBroHsValue_GetString', [{ name: '值句柄', type: 'longLong' }], 'wideString', '读取 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro值_设为空', 'FBroHsValue_SetNull', [{ name: '值句柄', type: 'longLong' }], 'int', '把 Value 设置为空值。', { visibility: 'advanced' }),
  api('FBro值_设置逻辑', 'FBroHsValue_SetBool', [{ name: '值句柄', type: 'longLong' }, { name: '值', type: 'bool' }], 'int', '写入逻辑值。', { visibility: 'advanced' }),
  api('FBro值_设置整数', 'FBroHsValue_SetInt', [{ name: '值句柄', type: 'longLong' }, { name: '值', type: 'int' }], 'int', '写入整数值。', { visibility: 'advanced' }),
  api('FBro值_设置小数', 'FBroHsValue_SetDouble', [{ name: '值句柄', type: 'longLong' }, { name: '值', type: 'double' }], 'int', '写入小数值。', { visibility: 'advanced' }),
  api('FBro值_设置文本', 'FBroHsValue_SetString', [{ name: '值句柄', type: 'longLong' }, { name: '值', type: 'wideString' }], 'int', '写入 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro值_取二进制', 'FBroHsValue_GetBinary', [{ name: '值句柄', type: 'longLong' }], 'longLong', '复制二进制值到受管缓冲并返回句柄。', { visibility: 'advanced' }),
  api('FBro值_设置二进制', 'FBroHsValue_SetBinary', [{ name: '值句柄', type: 'longLong' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '从受管缓冲写入二进制值。', { visibility: 'advanced' }),
  api('FBro值_取字典', 'FBroHsValue_GetDictionary', [{ name: '值句柄', type: 'longLong' }], 'longLong', '取得受父对象管理的 Dictionary 句柄。', { visibility: 'advanced' }),
  api('FBro值_取列表', 'FBroHsValue_GetList', [{ name: '值句柄', type: 'longLong' }], 'longLong', '取得受父对象管理的 List 句柄。', { visibility: 'advanced' }),
  api('FBro值_设置字典', 'FBroHsValue_SetDictionary', [{ name: '值句柄', type: 'longLong' }, { name: '字典句柄', type: 'longLong' }], 'int', '把 Dictionary 交由 Value 管理。', { visibility: 'advanced' }),
  api('FBro值_设置列表', 'FBroHsValue_SetList', [{ name: '值句柄', type: 'longLong' }, { name: '列表句柄', type: 'longLong' }], 'int', '把 List 交由 Value 管理。', { visibility: 'advanced' }),

  api('FBro字典_创建', 'FBroHsDictionaryValue_Create', [], 'longLong', '创建受管 Dictionary 对象。', { visibility: 'advanced' }),
  api('FBro字典_是否有效', 'FBroHsDictionaryValue_IsValid', [{ name: '字典句柄', type: 'longLong' }], 'int', '检查 Dictionary 是否有效。', { visibility: 'advanced' }),
  api('FBro字典_是否被拥有', 'FBroHsDictionaryValue_IsOwned', [{ name: '字典句柄', type: 'longLong' }], 'int', '检查 Dictionary 是否已被拥有。', { visibility: 'advanced' }),
  api('FBro字典_是否只读', 'FBroHsDictionaryValue_IsReadOnly', [{ name: '字典句柄', type: 'longLong' }], 'int', '检查 Dictionary 是否只读。', { visibility: 'advanced' }),
  api('FBro字典_是否同一对象', 'FBroHsDictionaryValue_IsSame', [{ name: '字典句柄', type: 'longLong' }, { name: '另一字典句柄', type: 'longLong' }], 'int', '检查两个 Dictionary 句柄是否引用同一官方对象。', { visibility: 'advanced' }),
  api('FBro字典_是否相等', 'FBroHsDictionaryValue_IsEqual', [{ name: '字典句柄', type: 'longLong' }, { name: '另一字典句柄', type: 'longLong' }], 'int', '比较两个 Dictionary 的内容。', { visibility: 'advanced' }),
  api('FBro字典_复制', 'FBroHsDictionaryValue_Copy', [{ name: '字典句柄', type: 'longLong' }, { name: '排除空子项', type: 'bool' }], 'longLong', '复制 Dictionary 并返回独立受管句柄。', { visibility: 'advanced' }),
  api('FBro字典_取数量', 'FBroHsDictionaryValue_GetSize', [{ name: '字典句柄', type: 'longLong' }], 'int', '取得键数量。', { visibility: 'advanced' }),
  api('FBro字典_清空', 'FBroHsDictionaryValue_Clear', [{ name: '字典句柄', type: 'longLong' }], 'int', '删除全部键。', { visibility: 'advanced' }),
  api('FBro字典_是否存在键', 'FBroHsDictionaryValue_HasKey', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '检查键是否存在。', { visibility: 'advanced' }),
  api('FBro字典_删除', 'FBroHsDictionaryValue_Remove', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '删除指定键。', { visibility: 'advanced' }),
  api('FBro字典_取类型', 'FBroHsDictionaryValue_GetType', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '取得指定键的官方值类型。', { visibility: 'advanced' }),
  api('FBro字典_取逻辑', 'FBroHsDictionaryValue_GetBool', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '读取逻辑值。', { visibility: 'advanced' }),
  api('FBro字典_取整数', 'FBroHsDictionaryValue_GetInt', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '读取整数值。', { visibility: 'advanced' }),
  api('FBro字典_取小数', 'FBroHsDictionaryValue_GetDouble', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'double', '读取小数值。', { visibility: 'advanced' }),
  api('FBro字典_取文本', 'FBroHsDictionaryValue_GetString', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'wideString', '读取 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro字典_取键列表JSON', 'FBroHsDictionaryValue_GetKeys', [{ name: '字典句柄', type: 'longLong' }], 'wideString', '取得 UTF-16 JSON 键数组，不向源码暴露 StringList 或 STL。', { visibility: 'advanced' }),
  api('FBro字典_取值对象', 'FBroHsDictionaryValue_GetValue', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'longLong', '取得受字典管理的 Value 句柄。', { visibility: 'advanced' }),
  api('FBro字典_取二进制', 'FBroHsDictionaryValue_GetBinary', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'longLong', '复制指定键的二进制值到受管缓冲。', { visibility: 'advanced' }),
  api('FBro字典_取字典', 'FBroHsDictionaryValue_GetDictionary', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'longLong', '取得受父字典管理的 Dictionary 句柄。', { visibility: 'advanced' }),
  api('FBro字典_取列表', 'FBroHsDictionaryValue_GetList', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'longLong', '取得受父字典管理的 List 句柄。', { visibility: 'advanced' }),
  api('FBro字典_设为空', 'FBroHsDictionaryValue_SetNull', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }], 'int', '把指定键设置为空值。', { visibility: 'advanced' }),
  api('FBro字典_设置逻辑', 'FBroHsDictionaryValue_SetBool', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '值', type: 'bool' }], 'int', '写入逻辑值。', { visibility: 'advanced' }),
  api('FBro字典_设置整数', 'FBroHsDictionaryValue_SetInt', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '值', type: 'int' }], 'int', '写入整数值。', { visibility: 'advanced' }),
  api('FBro字典_设置小数', 'FBroHsDictionaryValue_SetDouble', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '值', type: 'double' }], 'int', '写入小数值。', { visibility: 'advanced' }),
  api('FBro字典_设置文本', 'FBroHsDictionaryValue_SetString', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '值', type: 'wideString' }], 'int', '写入 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro字典_设置值对象', 'FBroHsDictionaryValue_SetValue', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '值句柄', type: 'longLong' }], 'int', '把 Value 交由指定键管理。', { visibility: 'advanced' }),
  api('FBro字典_设置二进制', 'FBroHsDictionaryValue_SetBinary', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '从受管缓冲写入指定键。', { visibility: 'advanced' }),
  api('FBro字典_设置字典', 'FBroHsDictionaryValue_SetDictionary', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '子字典句柄', type: 'longLong' }], 'int', '把子 Dictionary 交由指定键管理。', { visibility: 'advanced' }),
  api('FBro字典_设置列表', 'FBroHsDictionaryValue_SetList', [{ name: '字典句柄', type: 'longLong' }, { name: '键', type: 'wideString' }, { name: '列表句柄', type: 'longLong' }], 'int', '把 List 交由指定键管理。', { visibility: 'advanced' }),

  api('FBro列表_创建', 'FBroHsListValue_Create', [], 'longLong', '创建受管 List 对象。', { visibility: 'advanced' }),
  api('FBro列表_是否有效', 'FBroHsListValue_IsValid', [{ name: '列表句柄', type: 'longLong' }], 'int', '检查 List 是否有效。', { visibility: 'advanced' }),
  api('FBro列表_是否被拥有', 'FBroHsListValue_IsOwned', [{ name: '列表句柄', type: 'longLong' }], 'int', '检查 List 是否已被拥有。', { visibility: 'advanced' }),
  api('FBro列表_是否只读', 'FBroHsListValue_IsReadOnly', [{ name: '列表句柄', type: 'longLong' }], 'int', '检查 List 是否只读。', { visibility: 'advanced' }),
  api('FBro列表_是否同一对象', 'FBroHsListValue_IsSame', [{ name: '列表句柄', type: 'longLong' }, { name: '另一列表句柄', type: 'longLong' }], 'int', '检查两个 List 句柄是否引用同一官方对象。', { visibility: 'advanced' }),
  api('FBro列表_是否相等', 'FBroHsListValue_IsEqual', [{ name: '列表句柄', type: 'longLong' }, { name: '另一列表句柄', type: 'longLong' }], 'int', '比较两个 List 的内容。', { visibility: 'advanced' }),
  api('FBro列表_复制', 'FBroHsListValue_Copy', [{ name: '列表句柄', type: 'longLong' }], 'longLong', '复制 List 并返回独立受管句柄。', { visibility: 'advanced' }),
  api('FBro列表_设置数量', 'FBroHsListValue_SetSize', [{ name: '列表句柄', type: 'longLong' }, { name: '数量', type: 'int' }], 'int', '设置列表长度。', { visibility: 'advanced' }),
  api('FBro列表_取数量', 'FBroHsListValue_GetSize', [{ name: '列表句柄', type: 'longLong' }], 'int', '取得列表长度。', { visibility: 'advanced' }),
  api('FBro列表_清空', 'FBroHsListValue_Clear', [{ name: '列表句柄', type: 'longLong' }], 'int', '清空列表。', { visibility: 'advanced' }),
  api('FBro列表_删除', 'FBroHsListValue_Remove', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'int', '删除指定索引。', { visibility: 'advanced' }),
  api('FBro列表_取类型', 'FBroHsListValue_GetType', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'int', '取得指定索引的官方值类型。', { visibility: 'advanced' }),
  api('FBro列表_取逻辑', 'FBroHsListValue_GetBool', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'int', '读取逻辑值。', { visibility: 'advanced' }),
  api('FBro列表_取整数', 'FBroHsListValue_GetInt', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'int', '读取整数值。', { visibility: 'advanced' }),
  api('FBro列表_取小数', 'FBroHsListValue_GetDouble', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'double', '读取小数值。', { visibility: 'advanced' }),
  api('FBro列表_取文本', 'FBroHsListValue_GetString', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'wideString', '读取 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro列表_取值对象', 'FBroHsListValue_GetValue', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '取得受列表管理的 Value 句柄。', { visibility: 'advanced' }),
  api('FBro列表_取二进制', 'FBroHsListValue_GetBinary', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '复制指定项的二进制值到受管缓冲。', { visibility: 'advanced' }),
  api('FBro列表_取字典', 'FBroHsListValue_GetDictionary', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '取得受父列表管理的 Dictionary 句柄。', { visibility: 'advanced' }),
  api('FBro列表_取列表', 'FBroHsListValue_GetList', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '取得受父列表管理的 List 句柄。', { visibility: 'advanced' }),
  api('FBro列表_设为空', 'FBroHsListValue_SetNull', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'int', '把指定索引设置为空值。', { visibility: 'advanced' }),
  api('FBro列表_设置逻辑', 'FBroHsListValue_SetBool', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '值', type: 'bool' }], 'int', '写入逻辑值。', { visibility: 'advanced' }),
  api('FBro列表_设置整数', 'FBroHsListValue_SetInt', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '值', type: 'int' }], 'int', '写入整数值。', { visibility: 'advanced' }),
  api('FBro列表_设置小数', 'FBroHsListValue_SetDouble', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '值', type: 'double' }], 'int', '写入小数值。', { visibility: 'advanced' }),
  api('FBro列表_设置文本', 'FBroHsListValue_SetString', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '值', type: 'wideString' }], 'int', '写入 UTF-16 文本值。', { visibility: 'advanced' }),
  api('FBro列表_设置值对象', 'FBroHsListValue_SetValue', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '值句柄', type: 'longLong' }], 'int', '把 Value 交由指定索引管理。', { visibility: 'advanced' }),
  api('FBro列表_设置二进制', 'FBroHsListValue_SetBinary', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '从受管缓冲写入指定索引。', { visibility: 'advanced' }),
  api('FBro列表_设置字典', 'FBroHsListValue_SetDictionary', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '字典句柄', type: 'longLong' }], 'int', '把 Dictionary 交由指定索引管理。', { visibility: 'advanced' }),
  api('FBro列表_设置列表', 'FBroHsListValue_SetList', [{ name: '列表句柄', type: 'longLong' }, { name: '索引', type: 'int' }, { name: '子列表句柄', type: 'longLong' }], 'int', '把子 List 交由指定索引管理。', { visibility: 'advanced' }),

  api('FBro流_从文件创建', 'FBroStream_CreateForFile', [{ name: '路径', type: 'wideString' }], 'longLong', '从文件创建受管只读 Stream 句柄。', { visibility: 'advanced' }),
  api('FBro流_从缓冲创建', 'FBroStream_CreateForData', [{ name: '缓冲句柄', type: 'longLong' }], 'longLong', '复制受管缓冲并创建内存 Stream，保证底层数据生命周期。', { visibility: 'advanced' }),
  api('FBro流_读取', 'FBroStream_Read', [{ name: '流句柄', type: 'longLong' }, { name: '元素大小', type: 'longLong' }, { name: '元素数量', type: 'longLong' }], 'longLong', '读取数据并返回新的受管缓冲句柄，单次最多 256 MiB。', { visibility: 'advanced' }),
  api('FBro流_定位', 'FBroStream_Seek', [{ name: '流句柄', type: 'longLong' }, { name: '偏移', type: 'longLong' }, { name: '基准', type: 'int' }], 'int', '按 0=开头、1=当前位置、2=结尾定位 Stream。', { visibility: 'advanced' }),
  api('FBro流_取位置', 'FBroStream_Tell', [{ name: '流句柄', type: 'longLong' }], 'longLong', '取得当前字节位置。', { visibility: 'advanced' }),
  api('FBro流_是否结束', 'FBroStream_Eof', [{ name: '流句柄', type: 'longLong' }], 'int', '检查 Stream 是否到达结尾。', { visibility: 'advanced' }),
  api('FBro流_是否可能阻塞', 'FBroStream_MayBlock', [{ name: '流句柄', type: 'longLong' }], 'int', '查询该 Stream 操作是否可能阻塞。', { visibility: 'advanced' }),

  api('FBro图像_异步下载', 'FBroHsBrowserHost_DownloadImage', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }, { name: '作为图标', type: 'bool' }, { name: '最大尺寸', type: 'int' }, { name: '绕过缓存', type: 'bool' }], 'longLong', '通过当前浏览器会话异步下载图像并返回任务 ID。', { visibility: 'advanced' }),
  api('FBro图像_下载', 'LB_FBro_DownloadImageSync', [{ name: '控件名', type: 'controlRef' }, { name: '地址', type: 'wideString' }, { name: '作为图标', type: 'bool' }, { name: '最大尺寸', type: 'int' }, { name: '绕过缓存', type: 'bool' }], 'longLong', '同步下载图像并直接返回图像句柄（60 秒超时，失败返回 0）；用完调用 FBro对象_释放。', { visibility: 'advanced' }),
  api('FBro图像_是否为空', 'FBroHsImage_IsEmpty', [{ name: '图像句柄', type: 'longLong' }], 'int', '检查受管 Image 是否为空。', { visibility: 'advanced' }),
  api('FBro图像_取宽度', 'FBroHsImage_GetWidth', [{ name: '图像句柄', type: 'longLong' }], 'int', '取得图像 DIP 宽度。', { visibility: 'advanced' }),
  api('FBro图像_取高度', 'FBroHsImage_GetHeight', [{ name: '图像句柄', type: 'longLong' }], 'int', '取得图像 DIP 高度。', { visibility: 'advanced' }),
  api('FBro图像_取表示信息JSON', 'FBroHsImage_GetRepresentationInfo', [{ name: '图像句柄', type: 'longLong' }, { name: '缩放因子', type: 'double' }], 'wideString', '返回实际缩放、像素宽度和像素高度的 UTF-16 JSON。', { visibility: 'advanced' }),
  api('FBro图像_转位图缓冲', 'FBroHsImage_GetAsBitmap', [{ name: '图像句柄', type: 'longLong' }, { name: '缩放因子', type: 'double' }, { name: '颜色类型', type: 'int' }, { name: '透明类型', type: 'int' }], 'longLong', '把最接近的位图表示复制到受管缓冲。', { visibility: 'advanced' }),
  api('FBro图像_转JPEG缓冲', 'FBroHsImage_GetAsJPEG', [{ name: '图像句柄', type: 'longLong' }, { name: '缩放因子', type: 'double' }, { name: '质量', type: 'int' }], 'longLong', '把图像编码为 JPEG 受管缓冲。', { visibility: 'advanced' }),
  api('FBro图像_转PNG缓冲', 'FBroHsImage_GetAsPNG', [{ name: '图像句柄', type: 'longLong' }, { name: '缩放因子', type: 'double' }, { name: '保留透明', type: 'bool' }], 'longLong', '把图像编码为 PNG 受管缓冲。', { visibility: 'advanced' }),

  api('FBro证书_异步取当前', 'LB_FBro_GetCurrentCertificateAsync', [{ name: '控件名', type: 'controlRef' }], 'longLong', '从当前可见导航项异步取得 TLS 证书任务。', { visibility: 'advanced' }),
  api('FBro证书_取主体', 'FBroHsX509Certificate_GetSubject', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得受证书管理的主体 Principal 句柄。', { visibility: 'advanced' }),
  api('FBro证书_取颁发者', 'FBroHsX509Certificate_GetIssuer', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得受证书管理的颁发者 Principal 句柄。', { visibility: 'advanced' }),
  api('FBro证书_取序列号缓冲', 'FBroHsX509Certificate_GetSerialNumber', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得证书序列号受管缓冲。', { visibility: 'advanced' }),
  api('FBro证书_取DER缓冲', 'FBroHsX509Certificate_GetDEREncoded', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得 DER 编码证书受管缓冲。', { visibility: 'advanced' }),
  api('FBro证书_取PEM缓冲', 'FBroHsX509Certificate_GetPEMEncoded', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得 PEM 编码证书受管缓冲。', { visibility: 'advanced' }),
  api('FBro证书_取生效时间', 'FBroHsX509Certificate_GetValidStart', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得证书生效 Unix 时间。', { visibility: 'advanced' }),
  api('FBro证书_取失效时间', 'FBroHsX509Certificate_GetValidExpiry', [{ name: '证书句柄', type: 'longLong' }], 'longLong', '取得证书失效 Unix 时间。', { visibility: 'advanced' }),
  api('FBro证书_取颁发链数量', 'FBroHsX509Certificate_GetIssuerChainSize', [{ name: '证书句柄', type: 'longLong' }], 'int', '取得颁发链数量。', { visibility: 'advanced' }),
  api('FBro证书_取DER颁发链项', 'FBroHsX509Certificate_GetDEREncodedIssuerChain', [{ name: '证书句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '取得指定颁发链项的 DER 受管缓冲。', { visibility: 'advanced' }),
  api('FBro证书_取PEM颁发链项', 'FBroHsX509Certificate_GetPEMEncodedIssuerChain', [{ name: '证书句柄', type: 'longLong' }, { name: '索引', type: 'int' }], 'longLong', '取得指定颁发链项的 PEM 受管缓冲。', { visibility: 'advanced' }),
  api('FBro证书主体_取显示名', 'FBroHsX509CertPrincipal_GetDisplayName', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得证书主体显示名。', { visibility: 'advanced' }),
  api('FBro证书主体_取通用名', 'FBroHsX509CertPrincipal_GetCommonName', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得证书主体通用名。', { visibility: 'advanced' }),
  api('FBro证书主体_取地区名', 'FBroHsX509CertPrincipal_GetLocalityName', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得证书主体地区名。', { visibility: 'advanced' }),
  api('FBro证书主体_取省州名', 'FBroHsX509CertPrincipal_GetStateOrProvinceName', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得证书主体省或州名。', { visibility: 'advanced' }),
  api('FBro证书主体_取国家名', 'FBroHsX509CertPrincipal_GetCountryName', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得证书主体国家名。', { visibility: 'advanced' }),
  api('FBro证书主体_取组织JSON', 'FBroHsX509CertPrincipal_GetOrganizationNames', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得组织名 UTF-16 JSON 数组。', { visibility: 'advanced' }),
  api('FBro证书主体_取组织单位JSON', 'FBroHsX509CertPrincipal_GetOrganizationUnitNames', [{ name: '主体句柄', type: 'longLong' }], 'wideString', '取得组织单位名 UTF-16 JSON 数组。', { visibility: 'advanced' }),
  api('FBro拖放数据_是否有图像', 'FBroHsDragData_HasImage', [{ name: '拖放数据句柄', type: 'longLong' }], 'int', '检查 DragEnter 事件对象是否携带图像。', { visibility: 'advanced' }),
  api('FBro拖放数据_取图像', 'FBroHsDragData_GetImage', [{ name: '拖放数据句柄', type: 'longLong' }], 'longLong', '从 DragEnter 事件对象取得受管 Image 句柄。', { visibility: 'advanced' })
];

const networkEntries = [
  api('FBro网络_设置代理', 'LB_FBro_SetProxy', [{ name: '控件名', type: 'controlRef' }, { name: '代理地址', type: 'wideString' }], 'int', '设置当前 FBro RequestContext 的代理。', { runtimeName: 'FBro_设置代理', visibility: 'advanced' }),
  api('FBro网络_设置代理认证', 'LB_FBro_SetProxyAuthentication', [{ name: '控件名', type: 'controlRef' }, { name: '代理地址', type: 'wideString' }, { name: '用户名', type: 'wideString' }, { name: '密码', type: 'wideString' }], 'int', '设置代理与认证信息。', { runtimeName: 'FBro会话_设置代理认证', visibility: 'advanced' }),
  api('FBro服务器_创建', 'LB_FBro_ServerCreateAsync', [{ name: '控件名', type: 'controlRef' }, { name: '监听地址', type: 'wideString' }, { name: '端口', type: 'int' }, { name: '最大连接数', type: 'int' }], 'longLong', '在指定浏览器实例上创建内嵌 HTTP/WebSocket 服务器；任务结果包含 server 句柄与 address，服务器事件派发给该浏览器实例。', { visibility: 'advanced' }),
  api('FBro服务器_发送WebSocket文本', 'LB_FBro_ServerSendWebSocketMessage', [{ name: '服务器句柄', type: 'longLong' }, { name: '连接ID', type: 'int' }, { name: '文本', type: 'wideString' }], 'int', '向指定连接发送 WebSocket 文本帧（UTF-8）；自动投递到服务器 IO 线程。', { visibility: 'advanced' }),
  api('FBro服务器_发送WebSocket缓冲', 'LB_FBro_ServerSendWebSocketBuffer', [{ name: '服务器句柄', type: 'longLong' }, { name: '连接ID', type: 'int' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '向指定连接发送 WebSocket 二进制帧（受管缓冲）。', { visibility: 'advanced' }),
  api('FBro服务器_取地址', 'LB_FBro_ServerGetAddress', [{ name: '服务器句柄', type: 'longLong' }], 'wideString', '返回服务器监听地址。', { visibility: 'advanced' }),
  api('FBro服务器_是否存在连接', 'LB_FBro_ServerHasConnection', [{ name: '服务器句柄', type: 'longLong' }, { name: '连接ID', type: 'int' }], 'int', '判断指定连接是否仍然有效。', { visibility: 'advanced' }),
  api('FBro服务器_关闭', 'LB_FBro_ServerShutdown', [{ name: '服务器句柄', type: 'longLong' }], 'int', '关闭内嵌服务器并释放监听。', { visibility: 'advanced' }),
  api('FBro页面_发送文本', 'LB_FBro_SocketServerSendByBrowser', [{ name: '控件名', type: 'controlRef' }, { name: '通道名', type: 'wideString' }, { name: '文本', type: 'wideString' }], 'int', '按通道名把文本推送给页面内 WebSocket 拦截挂钩脚本（UTF-8 传输）；用于篡改/回发工作流。', { visibility: 'advanced' }),
  api('FBro页面_发送缓冲', 'LB_FBro_SocketServerSendByBrowserBuffer', [{ name: '控件名', type: 'controlRef' }, { name: '通道名', type: 'wideString' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '按通道名把受管缓冲字节推送给页面内拦截挂钩脚本。', { visibility: 'advanced' }),
  api('FBro页面_客户端发送文本', 'LB_FBro_SocketClientSendByBrowser', [{ name: '控件名', type: 'controlRef' }, { name: '通道名', type: 'wideString' }, { name: '文本', type: 'wideString' }], 'int', '按通道名把文本经客户端拦截通道推送给页面挂钩脚本。', { visibility: 'advanced' }),
  api('FBro页面_客户端发送缓冲', 'LB_FBro_SocketClientSendByBrowserBuffer', [{ name: '控件名', type: 'controlRef' }, { name: '通道名', type: 'wideString' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '按通道名把受管缓冲字节经客户端拦截通道推送给页面挂钩脚本。', { visibility: 'advanced' }),
  api('FBroWS客户端_是否空', 'LB_FBro_WssIsNull', [{ name: 'WS客户端句柄', type: 'longLong' }], 'int', '判断拦截事件下发的 WebSocket 客户端句柄是否为空。', { visibility: 'advanced' }),
  api('FBroWS客户端_取地址', 'LB_FBro_WssGetAddress', [{ name: 'WS客户端句柄', type: 'longLong' }], 'wideString', '读取被拦截 WebSocket 客户端的连接地址。', { visibility: 'advanced' }),
  api('FBroWS客户端_取协议', 'LB_FBro_WssGetProtocol', [{ name: 'WS客户端句柄', type: 'longLong' }], 'wideString', '读取被拦截 WebSocket 客户端的子协议。', { visibility: 'advanced' }),
  api('FBroWS客户端_取扩展', 'LB_FBro_WssGetExtensions', [{ name: 'WS客户端句柄', type: 'longLong' }], 'wideString', '读取被拦截 WebSocket 客户端的扩展协商结果。', { visibility: 'advanced' }),
  api('FBroWS客户端_发送文本', 'LB_FBro_WssSend', [{ name: 'WS客户端句柄', type: 'longLong' }, { name: '文本', type: 'wideString' }], 'int', '通过被拦截的 WebSocket 客户端发送文本帧。', { visibility: 'advanced' }),
  api('FBroWS客户端_发送缓冲', 'LB_FBro_WssSendBuffer', [{ name: 'WS客户端句柄', type: 'longLong' }, { name: '缓冲句柄', type: 'longLong' }], 'int', '通过被拦截的 WebSocket 客户端发送二进制帧（受管缓冲）。', { visibility: 'advanced' })
];

const vipAggregateOptions = {
  visibility: 'advanced' as const,
  category: FBRO_VIP_AGGREGATE_CATEGORY,
  capabilityKind: 'aggregate' as const
};

const FBRO_VIP_PARAM_DOCS: ParamDocTable = {
  命令: '要执行的 VIP 子命令名，取值见对应分类的单项命令文档。',
  参数JSON: '子命令参数 JSON 对象文本。',
  用户名: '启动代理认证用户名。',
  密码: '启动代理认证密码。',
  JSON: '完整指纹配置 JSON 文本，键见模块文档。',
  地址: '启动代理地址，格式 "scheme://host:port"。'
};

const vipEntries = [
  ...FBRO_VIP_OFFICIAL_ENTRIES,
  api('FBroVIP_应用指纹JSON', 'LB_FBro_ApplyFingerprintJson', [{ name: '控件名', type: 'controlRef' }, { name: 'JSON', type: 'wideString' }], 'int', '通过 UTF-16 JSON 批量应用完整直接指纹配置，覆盖浏览器、屏幕、GPU、WebRTC、时区、电池、位置、设备、Canvas/WebGL/Audio 和 User-Agent Data；不会暴露 Key。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_应用配置' }),
  api('FBroVIP_取已应用配置JSON', 'LB_FBro_GetAppliedFingerprintJson', [{ name: '控件名', type: 'controlRef' }], 'wideString', '取得最近一次成功应用的规范化指纹配置与 User-Agent Data JSON。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_取已应用配置' }),
  api('FBroVIP_取授权信息JSON', 'LB_FBro_GetVipLicenseInfoJson', [], 'wideString', '读取脱敏的 VIP 授权状态、版本、授权范围和有效期；不返回 Key。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_取授权信息' }),
  api('FBroVIP_取调用次数', 'LB_FBro_GetFingerprintCallCount', [{ name: '控件名', type: 'controlRef' }], 'wideString', '查询 VIP 指纹调用次数。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_取调用次数' }),
  api('FBroVIP_清空调用次数', 'LB_FBro_ClearFingerprintCallCount', [{ name: '控件名', type: 'controlRef' }], 'int', '清空 VIP 指纹调用次数。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_清空调用次数' }),
  api('FBroVIP_DOM异步命令', 'LB_FBro_VipDomCommandAsync', [{ name: '控件名', type: 'controlRef' }, { name: '命令', type: 'wideString' }, { name: '参数JSON', type: 'wideString' }], 'longLong', 'DOM 批量高级分发入口；单项 DOM 命令已经在 DOM 分类中分别公开。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_DOM异步命令' }),
  api('FBroVIP_扩展异步命令', 'LB_FBro_VipExtensionCommandAsync', [{ name: '控件名', type: 'controlRef' }, { name: '命令', type: 'wideString' }, { name: '参数JSON', type: 'wideString' }], 'longLong', '扩展批量高级分发入口；文件路径必须位于生成程序目录内。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_扩展异步命令' }),
  api('FBroVIP_资源规则异步命令', 'LB_FBro_VipResourceCommandAsync', [{ name: '控件名', type: 'controlRef' }, { name: '命令', type: 'wideString' }, { name: '参数JSON', type: 'wideString' }], 'longLong', '资源与响应规则批量高级分发入口；二进制数据只接受 FBro 受管缓冲句柄。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_资源规则异步命令' }),
  api('FBroVIP_开发者工具异步命令', 'LB_FBro_VipDevToolsCommandAsync', [{ name: '控件名', type: 'controlRef' }, { name: '命令', type: 'wideString' }, { name: '参数JSON', type: 'wideString' }], 'longLong', 'DevTools、Runtime 与输入批量高级分发入口；单项命令已经分别公开。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_开发者工具异步命令' }),
  api('FBroVIP_设置启动代理', 'LB_FBro_SetVipStartupProxy', [{ name: '地址', type: 'wideString' }, { name: '用户名', type: 'wideString' }, { name: '密码', type: 'wideString' }], 'int', '配置 VIP 启动代理；必须在首个 FBro 运行时初始化前调用，凭据只保存在 Bridge 内存中。', { ...vipAggregateOptions, runtimeName: 'FBro指纹_设置启动代理' })
];

export const FBRO_SUBMODULES: LingBuilderModuleManifest[] = [
  module('lingbuilder.fbro.events', 'FBro事件模块', '界面', '提供 UTF-16 JSON 事件包、同步决策与动态处理器绑定。', withParamDocs(FBRO_EVENT_PARAM_DOCS, eventEntries)),
  module('lingbuilder.fbro.session', 'FBro会话模块', '网络', '提供隔离 Profile、Cookie 和代理认证高层能力。', withParamDocs(FBRO_SESSION_PARAM_DOCS, sessionEntries)),
  module('lingbuilder.fbro.transfer', 'FBro传输模块', '网络', '提供下载与原生打印高层能力。', withParamDocs(FBRO_TRANSFER_PARAM_DOCS, transferEntries)),
  module('lingbuilder.fbro.automation', 'FBro自动化模块', '系统', '提供受管异步 JavaScript 任务与类型化 Frame 操作。', withParamDocs(FBRO_AUTOMATION_PARAM_DOCS, automationEntries)),
  module('lingbuilder.fbro.objects', 'FBro受管对象模块', '系统', '提供任务、缓冲及 Value、Dictionary、List、Stream、Image、Certificate、DragData 的类型化不透明句柄 API。', withParamDocs(FBRO_OBJECTS_PARAM_DOCS, objectEntries)),
  module('lingbuilder.fbro.network', 'FBro高级网络模块', '网络', '提供显式启用的代理与认证高级 API。', withParamDocs(FBRO_NETWORK_PARAM_DOCS, networkEntries)),
  module('lingbuilder.fbro.vip', 'FBro VIP 指纹模块', '系统', '提供不泄露授权信息的结构化 VIP 指纹入口。', withParamDocs(FBRO_VIP_PARAM_DOCS, vipEntries))
];
