import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
export interface CoverageLine { line: number; hits: number; state: 'covered' | 'uncovered' }
export interface CoverageFile { filePath: string; covered: number; total: number; percentage: number; lines: CoverageLine[] }
export interface QualityDiagnostic { source: 'sarif' | 'asan' | 'ubsan' | 'static'; severity: 'error' | 'warning' | 'info'; message: string; filePath?: string; line?: number; column?: number; code?: string }
export interface QualityReport { coverage: CoverageFile[]; diagnostics: QualityDiagnostic[]; summary: { coveredLines: number; totalLines: number; coveragePercentage: number; errors: number; warnings: number } }

export class QualityService {
  constructor(private readonly workspaceRoot: string, private readonly tsxImport: string) {}

  async importReports(options: { coveragePath?: string; sarifPath?: string; sanitizerPath?: string }): Promise<QualityReport> {
    const coverage = options.coveragePath ? await this.readCoverage(options.coveragePath) : []; const diagnostics = [
      ...(options.sarifPath ? parseSarif(await fs.readFile(await this.resolveFile(options.sarifPath), 'utf8'), this.workspaceRoot) : []),
      ...(options.sanitizerPath ? parseSanitizer(await fs.readFile(await this.resolveFile(options.sanitizerPath), 'utf8'), this.workspaceRoot) : [])
    ]; return report(coverage, diagnostics);
  }

  async runNodeCoverage(filePath: string, testName?: string): Promise<QualityReport> {
    const file = await this.resolveFile(filePath); if (!/\.(?:test|spec)\.(?:[cm]?js|tsx?)$/iu.test(file)) throw new Error('Node 覆盖率只能运行 *.test/spec.ts/js 文件。');
    const root = await fs.realpath(this.workspaceRoot); const directory = path.join(root, '.lingbuilder', `coverage-${crypto.randomUUID()}`); await fs.mkdir(directory, { recursive: true });
    const env: NodeJS.ProcessEnv = { ...process.env, NODE_V8_COVERAGE: directory }; delete env.NODE_TEST_CONTEXT; const args = ['--import', this.tsxImport, '--test']; if (testName?.trim()) args.push('--test-name-pattern', exactPattern(testName.trim())); args.push(file);
    try { await execFileAsync(process.execPath, args, { cwd: root, env, windowsHide: true, timeout: 120_000, maxBuffer: 8 * 1024 * 1024, encoding: 'utf8' }); }
    catch (error: any) { if (!error?.stdout && !error?.stderr) throw new Error(error?.message || '覆盖率测试运行失败。'); }
    try { const coverage = await parseV8Directory(directory, root); if (!coverage.length) throw new Error('Node 没有生成工作区源码覆盖率数据。'); return report(coverage, []); }
    finally { await fs.rm(directory, { recursive: true, force: true }); }
  }

  private async readCoverage(relative: string): Promise<CoverageFile[]> { const file = await this.resolveFile(relative); const text = await fs.readFile(file, 'utf8'); if (/\.info$|\.lcov$/iu.test(file) || text.startsWith('TN:') || text.includes('\nSF:')) return parseLcov(text, this.workspaceRoot); if (/\.json$/iu.test(file)) return parseIstanbul(text, this.workspaceRoot); throw new Error('覆盖率报告仅支持 LCOV 或 Istanbul coverage-final.json。'); }
  private async resolveFile(value: string): Promise<string> { const root = await fs.realpath(this.workspaceRoot); const file = await fs.realpath(path.resolve(root, value)); const relative = path.relative(root, file); if (relative.startsWith('..') || path.isAbsolute(relative) || !(await fs.stat(file)).isFile()) throw new Error('质量报告路径不能超出当前工作区。'); return file; }
}

export function parseLcov(text: string, root: string): CoverageFile[] { const result: CoverageFile[] = []; let source = ''; let lines: CoverageLine[] = []; const flush = () => { if (!source) return; result.push(coverageFile(relativePath(source, root), lines)); source = ''; lines = []; }; for (const raw of text.split(/\r?\n/u)) { if (raw.startsWith('SF:')) { flush(); source = raw.slice(3).trim(); } else if (raw.startsWith('DA:')) { const [line, hits] = raw.slice(3).split(',').map(Number); if (Number.isInteger(line) && Number.isFinite(hits)) lines.push({ line, hits, state: hits > 0 ? 'covered' : 'uncovered' }); } else if (raw === 'end_of_record') flush(); } flush(); return result; }
export function parseIstanbul(text: string, root: string): CoverageFile[] { let data: any; try { data = JSON.parse(text); } catch { throw new Error('Istanbul 覆盖率 JSON 无效。'); } return Object.entries(data).map(([file, value]: [string, any]) => { const hits = new Map<number, number>(); for (const [key, range] of Object.entries(value.statementMap || {}) as any) { const count = Number(value.s?.[key] || 0); for (let line = range.start.line; line <= range.end.line; line++) hits.set(line, Math.max(hits.get(line) || 0, count)); } return coverageFile(relativePath(file, root), [...hits].map(([line, count]) => ({ line, hits: count, state: count > 0 ? 'covered' as const : 'uncovered' as const }))); }); }
export function parseSarif(text: string, root: string): QualityDiagnostic[] { let data: any; try { data = JSON.parse(text); } catch { throw new Error('SARIF 报告 JSON 无效。'); } const result: QualityDiagnostic[] = []; for (const run of data.runs || []) for (const item of run.results || []) { const location = item.locations?.[0]?.physicalLocation; const uri = location?.artifactLocation?.uri; const region = location?.region || {}; result.push({ source: 'sarif', severity: item.level === 'error' ? 'error' : item.level === 'note' || item.level === 'none' ? 'info' : 'warning', message: String(item.message?.text || item.message?.markdown || '静态分析诊断'), code: item.ruleId ? String(item.ruleId) : undefined, filePath: uri ? relativePath(decodeUri(uri), root) : undefined, line: positive(region.startLine), column: positive(region.startColumn) }); } return result; }
export function parseSanitizer(text: string, root: string): QualityDiagnostic[] { const result: QualityDiagnostic[] = []; const lines = text.split(/\r?\n/u); for (let index = 0; index < lines.length; index++) { const line = lines[index]; const asan = line.match(/ERROR: AddressSanitizer:\s*([^\s]+)/u); const ubsan = line.match(/^(.+?):(\d+):(\d+):\s*runtime error:\s*(.+)$/u); if (ubsan) result.push({ source: 'ubsan', severity: 'error', message: ubsan[4], filePath: relativePath(ubsan[1], root), line: Number(ubsan[2]), column: Number(ubsan[3]), code: 'UBSan' }); else if (asan) { const frame = lines.slice(index + 1, index + 12).map(value => value.match(/(?:at |\s)([A-Za-z]:[^:]+|\/[^:]+):(\d+)(?::(\d+))?/u)).find(Boolean); result.push({ source: 'asan', severity: 'error', message: `AddressSanitizer：${asan[1]}`, filePath: frame?.[1] ? relativePath(frame[1], root) : undefined, line: frame ? Number(frame[2]) : undefined, column: frame?.[3] ? Number(frame[3]) : undefined, code: 'ASan' }); } } return result; }

async function parseV8Directory(directory: string, root: string): Promise<CoverageFile[]> { const files = await fs.readdir(directory); const byFile = new Map<string, Map<number, number>>(); for (const name of files.filter(item => item.endsWith('.json'))) { let data: any; try { data = JSON.parse(await fs.readFile(path.join(directory, name), 'utf8')); } catch { continue; } for (const script of data.result || []) { if (!String(script.url).startsWith('file:')) continue; const file = fileURLToPath(script.url); const relative = path.relative(root, file); if (relative.startsWith('..') || path.isAbsolute(relative)) continue; const source = await fs.readFile(file, 'utf8').catch(() => ''); const offsets = lineOffsets(source); const hits = byFile.get(relative) || new Map<number, number>(); for (const fn of script.functions || []) for (const range of fn.ranges || []) { const start = offsetLine(offsets, range.startOffset); const end = offsetLine(offsets, Math.max(range.startOffset, range.endOffset - 1)); for (let line = start; line <= end; line++) hits.set(line, Math.max(hits.get(line) || 0, Number(range.count || 0))); } byFile.set(relative, hits); } } return [...byFile].map(([file, hits]) => coverageFile(file.replace(/\\/gu, '/'), [...hits].map(([line, count]) => ({ line, hits: count, state: count > 0 ? 'covered' as const : 'uncovered' as const })))); }
function coverageFile(filePath: string, lines: CoverageLine[]): CoverageFile { const unique = [...new Map(lines.map(item => [item.line, item])).values()].sort((a, b) => a.line - b.line); const covered = unique.filter(item => item.hits > 0).length; return { filePath, covered, total: unique.length, percentage: unique.length ? Number((covered * 100 / unique.length).toFixed(2)) : 100, lines: unique }; }
function report(coverage: CoverageFile[], diagnostics: QualityDiagnostic[]): QualityReport { const coveredLines = coverage.reduce((sum, file) => sum + file.covered, 0); const totalLines = coverage.reduce((sum, file) => sum + file.total, 0); return { coverage, diagnostics, summary: { coveredLines, totalLines, coveragePercentage: totalLines ? Number((coveredLines * 100 / totalLines).toFixed(2)) : 100, errors: diagnostics.filter(item => item.severity === 'error').length, warnings: diagnostics.filter(item => item.severity === 'warning').length } }; }
function relativePath(file: string, root: string): string { const absolute = path.isAbsolute(file) ? file : path.resolve(root, file); const relative = path.relative(path.resolve(root), absolute); return (relative.startsWith('..') || path.isAbsolute(relative) ? absolute : relative).replace(/\\/gu, '/'); }
function decodeUri(uri: string): string { try { return uri.startsWith('file:') ? fileURLToPath(uri) : decodeURIComponent(uri); } catch { return uri; } }
function positive(value: unknown): number | undefined { const number = Number(value); return Number.isInteger(number) && number > 0 ? number : undefined; }
function lineOffsets(text: string): number[] { const result = [0]; for (let index = 0; index < text.length; index++) if (text.charCodeAt(index) === 10) result.push(index + 1); return result; }
function offsetLine(offsets: number[], offset: number): number { let low = 0; let high = offsets.length; while (low < high) { const middle = (low + high) >>> 1; if (offsets[middle] <= offset) low = middle + 1; else high = middle; } return Math.max(1, low); }
function exactPattern(value: string): string { return `^${value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}$`; }
