import { fork, type ChildProcess } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { TSX_IMPORT } from '../testing/testExplorerService';
import type { ExtensionDescriptor, ExtensionHostSnapshot, ExtensionManifest, ExtensionPermission } from './types';

interface Pending { resolve: (value: any) => void; reject: (error: Error) => void; timer: ReturnType<typeof setTimeout> }
export class ExtensionService {
  private child: ChildProcess | undefined; private extensions: ExtensionDescriptor[] = []; private readonly pending = new Map<number, Pending>(); private sequence = 1; private intentionalStop = false; private restartTimer: ReturnType<typeof setTimeout> | undefined;
  private snapshot: ExtensionHostSnapshot = { state: 'stopped', restartCount: 0, extensions: [], logs: [] }; private readonly extensionRoot: string; private readonly statePath: string;
  constructor(private readonly workspaceRoot: string, private readonly hostEntry?: string) { this.extensionRoot = path.join(workspaceRoot, '.lingbuilder', 'extensions'); this.statePath = path.join(workspaceRoot, '.lingbuilder', 'extensions-state.json'); }

  async start(): Promise<ExtensionHostSnapshot> { if (this.child?.connected) return this.getSnapshot(); this.intentionalStop = false; this.extensions = await this.scan(); this.snapshot.extensions = this.extensions; this.snapshot.state = 'starting'; await fs.mkdir(this.extensionRoot, { recursive: true }); const entry = await this.resolveHostEntry(); const sourceMode = entry.endsWith('.ts'); const execArgv = ['--permission', `--allow-fs-read=${path.dirname(entry)}`, `--allow-fs-read=${this.extensionRoot}`]; if (sourceMode) execArgv.push(`--allow-fs-read=${process.cwd()}`, '--import', TSX_IMPORT); const child = fork(entry, [], { cwd: process.cwd(), env: { ...process.env, ELECTRON_RUN_AS_NODE: '1', TSX_DISABLE_CACHE: '1' }, execArgv, silent: true }); this.child = child; this.snapshot.pid = child.pid; child.stdout?.on('data', chunk => this.log(`[Host] ${String(chunk).trimEnd()}`)); child.stderr?.on('data', chunk => this.log(`[Host] ${String(chunk).trimEnd()}`)); child.on('message', message => void this.handleMessage(message as any)); child.on('exit', (code, signal) => this.handleExit(child, code, signal));
    await this.waitReady(); await this.request('initialize', { extensions: this.extensions.filter(item => item.enabled).map(item => ({ id: item.id, root: item.root, main: item.manifest.main, activationEvents: item.manifest.activationEvents || [], permissions: item.manifest.permissions || [] })) }, 10_000, false); this.snapshot.state = 'ready'; await this.activateWorkspaceEvents(); return this.getSnapshot(); }
  async stop(): Promise<void> { this.intentionalStop = true; if (this.restartTimer) clearTimeout(this.restartTimer); if (this.child?.connected) this.child.send({ type: 'shutdown' }); await new Promise(resolve => setTimeout(resolve, 50)); this.child?.kill(); this.child = undefined; this.snapshot.state = 'stopped'; this.snapshot.pid = undefined; }
  getSnapshot(): ExtensionHostSnapshot { return { ...this.snapshot, extensions: this.extensions.map(item => ({ ...item, manifest: structuredClone(item.manifest) })), logs: [...this.snapshot.logs] }; }
  async refresh(): Promise<ExtensionHostSnapshot> { await this.stop(); this.snapshot.restartCount = 0; return await this.start(); }
  async setEnabled(extensionId: string, enabled: boolean): Promise<ExtensionHostSnapshot> { const states = await this.readStates(); states[extensionId] = enabled; await atomicJson(this.statePath, states); return await this.refresh(); }
  async executeCommand(command: string, args: unknown[] = []): Promise<unknown> { await this.ensureReady(); const extension = this.extensions.find(item => item.enabled && item.manifest.contributes?.commands?.some(entry => entry.command === command)); if (!extension) throw new Error(`扩展命令 ${command} 未注册或所属扩展已禁用。`); if (!Array.isArray(args) || args.length > 32) throw new Error('扩展命令参数无效。'); return await this.request('execute', { command, args }, 15_000); }
  async activateLanguage(languageId: string): Promise<void> { if (!/^[a-z0-9._-]{1,100}$/iu.test(languageId)) throw new Error('语言 ID 无效。'); await this.ensureReady(); await this.request('activate', { event: `onLanguage:${languageId}` }); }
  async loadTheme(extensionId: string, themeId: string): Promise<{ id: string; base: 'vs' | 'vs-dark'; inherit: boolean; rules: unknown[]; colors: Record<string, string> }> { const extension = this.extensions.find(item => item.id === extensionId && item.enabled); const theme = extension?.manifest.contributes?.themes?.find(item => item.id === themeId); if (!extension || !theme) throw new Error('扩展主题不存在或扩展已禁用。'); const content = await fs.readFile(path.resolve(extension.root, theme.path), 'utf8'); if (Buffer.byteLength(content, 'utf8') > 1024 * 1024) throw new Error('扩展主题文件超过 1 MB。'); const value = JSON.parse(content); if (!value || typeof value !== 'object' || (value.colors && typeof value.colors !== 'object') || (value.rules && !Array.isArray(value.rules))) throw new Error('扩展主题 JSON 无效。'); return { id: theme.id, base: theme.uiTheme === 'vs' ? 'vs' : 'vs-dark', inherit: value.inherit !== false, rules: value.rules || [], colors: value.colors || {} }; }
  async simulateCrashForTest(): Promise<void> { if (!this.child?.pid) throw new Error('Extension Host 未运行。'); this.child.kill('SIGKILL'); await waitUntil(() => this.snapshot.restartCount > 0 && this.snapshot.state === 'ready', 15_000); }

  private async scan(): Promise<ExtensionDescriptor[]> { await fs.mkdir(this.extensionRoot, { recursive: true }); const states = await this.readStates(); const result: ExtensionDescriptor[] = []; for (const entry of await fs.readdir(this.extensionRoot, { withFileTypes: true })) { if (!entry.isDirectory() || entry.isSymbolicLink()) continue; const root = path.join(this.extensionRoot, entry.name); try { const manifest = validateManifest(JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'))); const id = `${manifest.publisher}.${manifest.name}`; const main = path.resolve(root, manifest.main); if (!(await fs.stat(main)).isFile() || path.relative(root, main).startsWith('..')) throw new Error('扩展 main 必须是扩展目录内文件。'); for (const theme of manifest.contributes?.themes || []) { const themeFile = path.resolve(root, theme.path); if (path.relative(root, themeFile).startsWith('..') || !(await fs.stat(themeFile)).isFile()) throw new Error(`主题贡献 ${theme.id} 的文件无效。`); } result.push({ id, root, manifest, enabled: states[id] !== false, state: states[id] === false ? 'disabled' : 'inactive', activationCount: 0 }); } catch (error) { result.push({ id: entry.name, root, manifest: { publisher: 'invalid', name: entry.name, version: '0.0.0', main: '' }, enabled: false, state: 'error', error: error instanceof Error ? error.message : String(error), activationCount: 0 }); } } return result.sort((a, b) => a.id.localeCompare(b.id)); }
  private async handleMessage(message: any) { if (message.type === 'ready') { this.log('Extension Host 已就绪。'); return; } if (message.type === 'result') { const pending = this.pending.get(message.id); if (!pending) return; clearTimeout(pending.timer); this.pending.delete(message.id); message.error ? pending.reject(new Error(message.error)) : pending.resolve(message.result); return; } if (message.type === 'activated') { const extension = this.extensions.find(item => item.id === message.extensionId); if (extension) { extension.state = 'active'; extension.activationCount++; } return; } if (message.type === 'log') { this.log(`[${message.extensionId}] ${message.message}`); return; } if (message.type === 'hostCall') { try { const result = await this.handleHostCall(message.extensionId, message.method, message.params); this.child?.send({ type: 'response', id: message.id, result }); } catch (error) { this.child?.send({ type: 'response', id: message.id, error: error instanceof Error ? error.message : String(error) }); } } }
  private async handleHostCall(extensionId: string, method: string, params: any): Promise<unknown> { const extension = this.extensions.find(item => item.id === extensionId && item.enabled); if (!extension) throw new Error('扩展未启用。'); if (method === 'window.showInformationMessage') { const message = String(params?.message || '').slice(0, 2000); this.log(`[消息] ${message}`); return message; } if (method === 'workspace.readTextFile') { requirePermission(extension, 'workspace.read'); return await fs.readFile(await this.resolveWorkspaceFile(params?.filePath, false), 'utf8'); } if (method === 'workspace.writeTextFile') { requirePermission(extension, 'workspace.write'); const content = params?.content; if (typeof content !== 'string' || Buffer.byteLength(content, 'utf8') > 2 * 1024 * 1024) throw new Error('扩展写入内容无效或超过 2 MB。'); const file = await this.resolveWorkspaceFile(params?.filePath, true); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, content, 'utf8'); return true; } throw new Error(`不支持的扩展 API：${method}`); }
  private async resolveWorkspaceFile(value: unknown, write: boolean): Promise<string> { if (typeof value !== 'string' || !value.trim() || value.includes('\0')) throw new Error('扩展文件路径无效。'); const root = await fs.realpath(this.workspaceRoot); const target = path.resolve(root, value); const relative = path.relative(root, target); if (relative.startsWith('..') || path.isAbsolute(relative) || relative.startsWith(`.lingbuilder${path.sep}extensions`)) throw new Error('扩展文件路径不能越界或修改扩展目录。'); if (!write) { const real = await fs.realpath(target); const checked = path.relative(root, real); if (checked.startsWith('..') || path.isAbsolute(checked)) throw new Error('扩展文件链接不能越界。'); return real; } let parent = path.dirname(target); while (!(await exists(parent))) { const next = path.dirname(parent); if (next === parent) throw new Error('扩展写入目录无效。'); parent = next; } const realParent = await fs.realpath(parent); const checked = path.relative(root, realParent); if (checked.startsWith('..') || path.isAbsolute(checked)) throw new Error('扩展写入目录链接不能越界。'); if (await exists(target)) { const realTarget = await fs.realpath(target); const targetCheck = path.relative(root, realTarget); if (targetCheck.startsWith('..') || path.isAbsolute(targetCheck)) throw new Error('扩展写入文件链接不能越界。'); return realTarget; } return target; }
  private request(type: string, params: Record<string, unknown>, timeout = 10_000, expectResult = true): Promise<any> { if (!this.child?.connected) throw new Error('Extension Host 未连接。'); const id = this.sequence++; this.child.send({ type, id, ...params }); if (!expectResult) return Promise.resolve(); return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); this.child?.kill('SIGKILL'); reject(new Error(`Extension Host 请求 ${type} 超时，已终止无响应宿主。`)); }, timeout); this.pending.set(id, { resolve, reject, timer }); }); }
  private async waitReady() { await waitUntil(() => this.snapshot.logs.some(item => item.includes('Extension Host 已就绪')) || this.snapshot.state === 'crashed', 10_000); if (this.snapshot.state === 'crashed') throw new Error(`Extension Host 启动失败：${this.snapshot.logs.slice(-3).join(' | ')}`); }
  private async ensureReady() { if (this.snapshot.state !== 'ready') await this.start(); }
  private handleExit(child: ChildProcess, code: number | null, signal: NodeJS.Signals | null) { if (this.child !== child) return; this.child = undefined; this.snapshot.pid = undefined; for (const item of this.pending.values()) { clearTimeout(item.timer); item.reject(new Error('Extension Host 已退出。')); } this.pending.clear(); if (this.intentionalStop) { this.snapshot.state = 'stopped'; return; } this.snapshot.state = 'crashed'; this.log(`Extension Host 异常退出：${code ?? signal ?? 'unknown'}。`); if (this.snapshot.restartCount < 3) { this.snapshot.restartCount++; this.restartTimer = setTimeout(() => void this.start().catch(error => this.log(`Extension Host 恢复失败：${error.message}`)), 100); } }
  private async activateWorkspaceEvents() { for (const extension of this.extensions.filter(item => item.enabled)) for (const event of extension.manifest.activationEvents || []) if (event.startsWith('workspaceContains:')) { const pattern = event.slice('workspaceContains:'.length); if (pattern && !pattern.includes('..') && await exists(path.join(this.workspaceRoot, pattern))) await this.request('activate', { event }); } }
  private async resolveHostEntry(): Promise<string> { if (this.hostEntry) return this.hostEntry; const candidates = [path.resolve(typeof __dirname === 'string' ? __dirname : process.cwd(), 'extension-host.cjs'), path.resolve(process.cwd(), 'dist', 'extension-host.cjs')]; for (const compiled of candidates) if (await exists(compiled)) return compiled; return path.resolve(process.cwd(), 'src', 'services', 'extensions', 'extensionHostProcess.ts'); }
  private async readStates(): Promise<Record<string, boolean>> { try { const value = JSON.parse(await fs.readFile(this.statePath, 'utf8')); return value && typeof value === 'object' ? value : {}; } catch { return {}; } }
  private log(message: string) { if (!message) return; this.snapshot.logs.push(message); if (this.snapshot.logs.length > 500) this.snapshot.logs.splice(0, this.snapshot.logs.length - 500); }
}

function validateManifest(value: any): ExtensionManifest { if (!value || typeof value !== 'object') throw new Error('扩展 package.json 无效。'); for (const key of ['name', 'publisher', 'version', 'main']) if (typeof value[key] !== 'string' || !value[key].trim()) throw new Error(`扩展缺少 ${key}。`); if (!/^[a-z0-9._-]+$/iu.test(value.name) || !/^[a-z0-9._-]+$/iu.test(value.publisher)) throw new Error('扩展 publisher/name 无效。'); if (value.activationEvents && (!Array.isArray(value.activationEvents) || value.activationEvents.some((item: any) => typeof item !== 'string' || !/^(?:\*|onCommand:[a-z0-9._-]+|onLanguage:[a-z0-9._-]+|workspaceContains:[^\0]+)$/iu.test(item)))) throw new Error('activationEvents 无效。'); const permissions = value.permissions || []; if (!Array.isArray(permissions) || permissions.some((item: any) => !['workspace.read', 'workspace.write'].includes(item))) throw new Error('扩展权限无效。'); const contributes = value.contributes || {}; if (contributes.commands && (!Array.isArray(contributes.commands) || contributes.commands.some((item: any) => typeof item.command !== 'string' || typeof item.title !== 'string'))) throw new Error('命令贡献无效。'); if (contributes.menus && (!Array.isArray(contributes.menus) || contributes.menus.some((item: any) => typeof item.menu !== 'string' || typeof item.command !== 'string'))) throw new Error('菜单贡献无效。'); if (contributes.views && (!Array.isArray(contributes.views) || contributes.views.some((item: any) => typeof item.id !== 'string' || typeof item.name !== 'string'))) throw new Error('视图贡献无效。'); if (contributes.languages && (!Array.isArray(contributes.languages) || contributes.languages.some((item: any) => typeof item.id !== 'string' || (item.extensions && !Array.isArray(item.extensions))))) throw new Error('语言贡献无效。'); if (contributes.themes && (!Array.isArray(contributes.themes) || contributes.themes.some((item: any) => typeof item.id !== 'string' || typeof item.label !== 'string' || typeof item.path !== 'string'))) throw new Error('主题贡献无效。'); return structuredClone(value); }
function requirePermission(extension: ExtensionDescriptor, permission: ExtensionPermission) { if (!(extension.manifest.permissions || []).includes(permission)) throw new Error(`扩展 ${extension.id} 未声明权限 ${permission}。`); }
async function atomicJson(file: string, value: unknown) { await fs.mkdir(path.dirname(file), { recursive: true }); const temp = `${file}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); await fs.rename(temp, file); }
async function exists(file: string) { try { await fs.access(file); return true; } catch { return false; } }
async function waitUntil(predicate: () => boolean, timeout: number) { const started = Date.now(); while (!predicate()) { if (Date.now() - started > timeout) throw new Error('等待 Extension Host 超时。'); await new Promise(resolve => setTimeout(resolve, 25)); } }
