import crypto from 'node:crypto'; import fs from 'node:fs/promises'; import path from 'node:path'; import { decodeTextFile, encodeTextFile } from '../files/textFileService'; import type { TextFileFormat } from '../files/types';
export interface RcResourceEntry { key: string; kind: 'menu' | 'dialog' | 'string' | 'control'; id: string; text: string; line: number }
export interface RcResourceDocument { filePath: string; token: string; format: TextFileFormat; content: string; entries: RcResourceEntry[] }
export class RcResourceService {
  constructor(private readonly workspaceRoot: string) {}
  async read(filePath: string): Promise<RcResourceDocument> { const file = await this.resolve(filePath); const bytes = await fs.readFile(file); const snapshot = decodeTextFile(bytes); return { filePath: normalize(path.relative(await fs.realpath(this.workspaceRoot), file)), token: hash(bytes), format: snapshot.format, content: snapshot.content, entries: parseRcResources(snapshot.content) }; }
  async apply(filePath: string, token: string, edits: Array<{ key: string; text: string }>): Promise<RcResourceDocument> { const file = await this.resolve(filePath); if (hash(await fs.readFile(file)) !== token) throw new Error('.rc 文件已被外部修改，请重新载入。'); const current = await this.read(filePath); if (!Array.isArray(edits) || edits.length > 1000) throw new Error('资源编辑列表无效。'); const byKey = new Map(edits.map(item => [item.key, validText(item.text)])); const lines = current.content.split(/(?<=\n)/u); for (const entry of current.entries) { const replacement = byKey.get(entry.key); if (replacement === undefined) continue; lines[entry.line - 1] = replaceQuoted(lines[entry.line - 1], replacement); byKey.delete(entry.key); } if (byKey.size) throw new Error('资源条目已变化，请重新载入。'); const next = lines.join(''); const temp = `${file}.${crypto.randomUUID()}.tmp`; await fs.writeFile(temp, encodeTextFile(next, current.format)); await fs.rename(temp, file); return await this.read(filePath); }
  private async resolve(value: string) { if (typeof value !== 'string' || !/\.rc$/iu.test(value)) throw new Error('只能编辑工作区内 .rc 文件。'); const root = await fs.realpath(this.workspaceRoot); const file = await fs.realpath(path.resolve(root, value)); const relative = path.relative(root, file); if (relative.startsWith('..') || path.isAbsolute(relative) || !(await fs.stat(file)).isFile()) throw new Error('.rc 文件不能超出工作区。'); return file; }
}
export function parseRcResources(content: string): RcResourceEntry[] { const result: RcResourceEntry[] = []; const lines = content.split(/\r?\n/u); let block: 'menu' | 'dialog' | 'string' | undefined; let blockId = ''; lines.forEach((line, index) => { const menu = line.match(/^\s*([A-Z0-9_]+)\s+MENU(?:EX)?\b/iu); const dialog = line.match(/^\s*([A-Z0-9_]+)\s+DIALOG(?:EX)?\b/iu); if (menu) { block = 'menu'; blockId = menu[1]; } if (dialog) { block = 'dialog'; blockId = dialog[1]; } if (/^\s*STRINGTABLE\b/iu.test(line)) { block = 'string'; blockId = 'STRINGTABLE'; } if (/^\s*END\s*$/iu.test(line)) { block = undefined; blockId = ''; return; } const quoted = line.match(/"((?:[^"\\]|\\.)*)"/u); if (!quoted) return; let id = ''; let kind: RcResourceEntry['kind']; if (block === 'menu' && /\b(?:POPUP|MENUITEM)\b/iu.test(line)) { id = line.match(/,\s*([A-Z0-9_]+)\s*$/iu)?.[1] || `${blockId}_POPUP_${index + 1}`; kind = 'menu'; } else if (block === 'dialog' && /\bCAPTION\b/iu.test(line)) { id = blockId; kind = 'dialog'; } else if (block === 'dialog' && /\b(?:CONTROL|PUSHBUTTON|DEFPUSHBUTTON|LTEXT|CTEXT|RTEXT|GROUPBOX)\b/iu.test(line)) { id = line.match(/,\s*([A-Z0-9_]+)\s*,/iu)?.[1] || `${blockId}_CONTROL_${index + 1}`; kind = 'control'; } else if (block === 'string') { id = line.trim().split(/\s+/u)[0]; kind = 'string'; } else return; result.push({ key: `${kind}:${id}:${index + 1}`, kind, id, text: unescapeRc(quoted[1]), line: index + 1 }); }); return result; }
function replaceQuoted(line: string, value: string) { return line.replace(/"(?:[^"\\]|\\.)*"/u, `"${value.replace(/\\/gu, '\\\\').replace(/"/gu, '\\"').replace(/\r?\n/gu, '\\n')}"`); } function unescapeRc(value: string) { return value.replace(/\\n/gu, '\n').replace(/\\"/gu, '"').replace(/\\\\/gu, '\\'); } function validText(value: string) { if (typeof value !== 'string' || value.length > 10000 || value.includes('\0')) throw new Error('资源文本无效。'); return value; } function hash(value: Uint8Array) { return crypto.createHash('sha256').update(value).digest('hex'); } function normalize(value: string) { return value.replace(/\\/gu, '/'); }
