import crypto from 'node:crypto';
import { execFile, spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';

export interface NodeTestDebugSnapshot { id: string; state: 'starting' | 'paused' | 'running' | 'terminated' | 'error'; testId: string; inspectorUrl?: string; pid?: number; logs: string[]; error?: string }

export class NodeTestDebugService {
  private session: { snapshot: NodeTestDebugSnapshot; child: ChildProcessWithoutNullStreams; socket?: WebSocket; sequence: number; pending: Map<number, { resolve: () => void; reject: (error: Error) => void; timer: ReturnType<typeof setTimeout> }> } | undefined;
  async start(options: { testId: string; program: string; args: string[]; cwd: string }): Promise<NodeTestDebugSnapshot> {
    await this.stop(); const env = { ...process.env }; delete env.NODE_TEST_CONTEXT; const child = spawn(options.program, options.args, { cwd: options.cwd, env, stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true }); const snapshot: NodeTestDebugSnapshot = { id: crypto.randomUUID(), state: 'starting', testId: options.testId, pid: child.pid, logs: [] }; const session: NonNullable<NodeTestDebugService['session']> = { snapshot, child, sequence: 1, pending: new Map() }; this.session = session;
    child.stdout.on('data', chunk => { const text = String(chunk); push(snapshot.logs, text); if (/duration_ms|tests? \d+/u.test(text) && snapshot.state === 'running') session.socket?.close(); }); child.stderr.on('data', chunk => { const text = String(chunk); push(snapshot.logs, text); const url = text.match(/ws:\/\/[^\s]+/u)?.[0]; if (url && !snapshot.inspectorUrl) { snapshot.inspectorUrl = url; void this.connect(session, url); } if (/Waiting for the debugger to disconnect/iu.test(text)) session.socket?.close(); });
    child.on('error', error => { snapshot.state = 'error'; snapshot.error = error.message; }); child.on('close', code => { if (snapshot.state !== 'error') snapshot.state = 'terminated'; push(snapshot.logs, `Node 测试进程已退出，代码 ${code ?? -1}。`); session.socket?.close(); });
    await waitUntil(() => snapshot.state === 'paused' || snapshot.state === 'error' || snapshot.state === 'terminated', 10_000); if (snapshot.state !== 'paused') throw new Error(snapshot.error || 'Node Inspector 启动失败，未取得调试端点。'); return clone(snapshot);
  }
  getSnapshot(): NodeTestDebugSnapshot | null { return this.session ? clone(this.session.snapshot) : null; }
  async continue(): Promise<NodeTestDebugSnapshot> { const session = this.requireSession(); if (session.snapshot.state !== 'paused') throw new Error('Node 测试当前没有暂停。'); await this.request(session, 'Runtime.runIfWaitingForDebugger'); await this.request(session, 'Debugger.resume').catch(() => undefined); session.snapshot.state = 'running'; session.socket?.close(); return clone(session.snapshot); }
  async stop(): Promise<NodeTestDebugSnapshot | null> { const session = this.session; if (!session) return null; session.socket?.close(); if (!session.child.killed && session.child.pid) { if (process.platform === 'win32') await new Promise<void>(resolve => execFile('taskkill.exe', ['/pid', String(session.child.pid), '/t', '/f'], { windowsHide: true }, () => resolve())); else session.child.kill('SIGTERM'); } session.snapshot.state = 'terminated'; return clone(session.snapshot); }
  private async connect(session: NonNullable<NodeTestDebugService['session']>, url: string) { try { const socket = new WebSocket(url); session.socket = socket; socket.addEventListener('message', event => { try { const message = JSON.parse(String(event.data)); if (!message.id) return; const pending = session.pending.get(message.id); if (!pending) return; clearTimeout(pending.timer); session.pending.delete(message.id); message.error ? pending.reject(new Error(message.error.message || 'Inspector 请求失败。')) : pending.resolve(); } catch { /* ignore protocol noise */ } }); await new Promise<void>((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Inspector WebSocket 连接超时。')), 5000); socket.addEventListener('open', () => { clearTimeout(timer); resolve(); }, { once: true }); socket.addEventListener('error', () => { clearTimeout(timer); reject(new Error('Inspector WebSocket 连接失败。')); }, { once: true }); }); await this.request(session, 'Runtime.enable'); await this.request(session, 'Debugger.enable'); session.snapshot.state = 'paused'; } catch (error) { session.snapshot.state = 'error'; session.snapshot.error = error instanceof Error ? error.message : String(error); session.child.kill(); } }
  private request(session: NonNullable<NodeTestDebugService['session']>, method: string): Promise<void> { if (!session.socket || session.socket.readyState !== WebSocket.OPEN) throw new Error('Node Inspector 尚未连接。'); const id = session.sequence++; return new Promise((resolve, reject) => { const timer = setTimeout(() => { session.pending.delete(id); reject(new Error(`Inspector 请求 ${method} 超时。`)); }, 5000); session.pending.set(id, { resolve, reject, timer }); session.socket!.send(JSON.stringify({ id, method })); }); }
  private requireSession() { if (!this.session || ['terminated', 'error'].includes(this.session.snapshot.state)) throw new Error('当前没有可操作的 Node 测试调试会话。'); return this.session; }
}

function push(logs: string[], text: string) { if (!text) return; logs.push(text.trimEnd()); if (logs.length > 500) logs.splice(0, logs.length - 500); }
function clone(snapshot: NodeTestDebugSnapshot): NodeTestDebugSnapshot { return { ...snapshot, logs: [...snapshot.logs] }; }
async function waitUntil(predicate: () => boolean, timeout: number) { const started = Date.now(); while (!predicate()) { if (Date.now() - started > timeout) throw new Error('等待 Node Inspector 超时。'); await new Promise(resolve => setTimeout(resolve, 25)); } }
