import crypto from 'node:crypto'; import fs from 'node:fs/promises'; import path from 'node:path';
export interface WorkspaceIndexSnapshot { schemaVersion: 1; generatedAt: string; files: Array<{ path: string; sha256: string; preview: string; terms: string[] }> }
export interface WorkspaceIndexHit { path: string; score: number; preview: string }
const ALLOWED = /\.(?:lcpp|cpp|c|h|hpp|md|txt|json|ini|rc|ts|tsx|js|jsx)$/iu; const SKIP = new Set(['node_modules', '.git', 'dist', 'dist-electron', '.lingbuilder-build', 'generated']);
export class WorkspaceIndexService { private controller: AbortController | null = null; private snapshot: WorkspaceIndexSnapshot | null = null; constructor(private readonly workspaceRoot: string) {}
  async rebuild(signal?: AbortSignal): Promise<WorkspaceIndexSnapshot> { if (this.controller) throw new Error('工作区索引正在构建。'); this.controller = new AbortController(); const combined = combineSignals(this.controller.signal, signal); try { const root = await fs.realpath(this.workspaceRoot); const files: WorkspaceIndexSnapshot['files'] = []; await walk(root, root, files, combined); const snapshot: WorkspaceIndexSnapshot = { schemaVersion: 1, generatedAt: new Date().toISOString(), files: files.slice(0, 20_000) }; const directory = path.join(root, '.lingbuilder'); await fs.mkdir(directory, { recursive: true }); const temporary = path.join(directory, `ai-index-${crypto.randomUUID()}.tmp`); await fs.writeFile(temporary, JSON.stringify(snapshot)); combined.throwIfAborted(); await fs.rename(temporary, path.join(directory, 'ai-index.json')); this.snapshot = snapshot; return snapshot; } catch (error) { if (combined.aborted) throw new Error('工作区索引已取消。'); throw error; } finally { this.controller = null; } }
  cancel(): boolean { if (!this.controller) return false; this.controller.abort(); return true; }
  async search(query: string, limit = 20): Promise<WorkspaceIndexHit[]> { const terms = tokenize(query); if (!terms.length) throw new Error('索引查询不能为空。'); const snapshot = this.snapshot || await this.read(); return snapshot.files.map(file => ({ path: file.path, preview: file.preview, score: terms.reduce((sum, term) => sum + (file.terms.includes(term) ? 1 : 0), 0) })).filter(item => item.score > 0).sort((a, b) => b.score - a.score || a.path.localeCompare(b.path)).slice(0, Math.max(1, Math.min(100, limit))); }
  private async read(): Promise<WorkspaceIndexSnapshot> { try { const value = JSON.parse(await fs.readFile(path.join(await fs.realpath(this.workspaceRoot), '.lingbuilder', 'ai-index.json'), 'utf8')); if (value?.schemaVersion !== 1 || !Array.isArray(value.files)) throw new Error(); return value; } catch { throw new Error('尚未建立工作区 AI 索引。'); } }
}
async function walk(root: string, directory: string, result: WorkspaceIndexSnapshot['files'], signal: AbortSignal): Promise<void> { signal.throwIfAborted(); if (result.length >= 20_000) return; for (const entry of await fs.readdir(directory, { withFileTypes: true })) { signal.throwIfAborted(); if (entry.isSymbolicLink() || SKIP.has(entry.name)) continue; const absolute = path.join(directory, entry.name); if (entry.isDirectory()) await walk(root, absolute, result, signal); else if (entry.isFile() && ALLOWED.test(entry.name)) { const stat = await fs.stat(absolute); if (stat.size > 2 * 1024 * 1024) continue; const text = await fs.readFile(absolute, 'utf8'); result.push({ path: path.relative(root, absolute).replace(/\\/gu, '/'), sha256: crypto.createHash('sha256').update(text).digest('hex'), preview: text.replace(/\s+/gu, ' ').slice(0, 240), terms: [...new Set(tokenize(text))].slice(0, 5000) }); } } }
export function tokenize(value: string): string[] { return (value.toLowerCase().match(/[\p{Script=Han}]{1,8}|[a-z_][a-z0-9_]{1,63}/gu) || []).slice(0, 100_000); }
function combineSignals(first: AbortSignal, second?: AbortSignal): AbortSignal { if (!second) return first; return AbortSignal.any([first, second]); }
