import { Body, Controller, Get, Inject, Param, Patch, Post, Query } from '@nestjs/common';
import { authenticator } from 'otplib';
import { BillingService } from '../billing/billing.service.js';
import { CurrentUser, Roles, type AuthenticatedUser } from '../common/current-user.js';
import { PrismaService } from '../prisma.service.js';
import { SecretVaultService } from '../security/secret-vault.service.js';
import { validateProviderUrl } from '../security/network-policy.js';
import { SystemAiProviderService } from '../ai/system-ai-provider.service.js';

@Controller('v1/admin')
@Roles('super_admin', 'operator', 'support', 'auditor')
export class AdminController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService, @Inject(BillingService) private readonly billing: BillingService, @Inject(SecretVaultService) private readonly vault: SecretVaultService, @Inject(SystemAiProviderService) private readonly systemAiProviders: SystemAiProviderService) {}
  @Get('overview') async overview() { const [users, requests, models, providers] = await Promise.all([this.prisma.user.count(), this.prisma.aiRequest.count(), this.prisma.logicalModel.count({ where: { enabled: true } }), this.prisma.providerChannel.count({ where: { enabled: true } })]); const aggregate = await this.prisma.aiRequest.aggregate({ _sum: { inputTokens: true, outputTokens: true, chargedPoints: true, providerCostMicros: true } }); return json({ ok: true, users, requests, models, providers, totals: aggregate._sum }); }
  @Get('users') async users(@Query('query') query = '') { const users = await this.prisma.user.findMany({ where: query ? { email: { contains: query, mode: 'insensitive' } } : {}, include: { creditAccount: true, adminMembership: true }, orderBy: { createdAt: 'desc' }, take: 200 }); return json({ ok: true, users }); }
  @Patch('users/:userId/status') @Roles('super_admin', 'operator') async status(@Param('userId') userId: string, @Body() body: any, @CurrentUser() actor: AuthenticatedUser) { const status = String(body.status || ''); if (!['ACTIVE', 'SUSPENDED'].includes(status)) throw Object.assign(new Error('账号状态无效。'), { status: 400, code: 'VALIDATION_FAILED' }); const user = await this.prisma.user.update({ where: { id: userId }, data: { status: status as any } }); await this.audit(actor, 'user.status', 'user', userId, { status }); return { ok: true, user }; }
  @Post('credits/adjust') @Roles('super_admin', 'operator', 'support') async adjust(@Body() body: any, @CurrentUser() actor: AuthenticatedUser) { const points = BigInt(String(body.points || '0')); if (actor.role === 'support' && (points > 10000n || points < -10000n)) throw Object.assign(new Error('支持人员单次调账不能超过 10,000 点。'), { status: 403, code: 'FORBIDDEN' }); const result = await this.billing.adjust(String(body.userId), points, String(body.reason || ''), actor.id); await this.audit(actor, 'credit.adjust', 'user', String(body.userId), { points: points.toString(), reason: body.reason }); return json({ ok: true, account: result }); }
  @Get('promotions') async promotions() { return json({ ok: true, promotions: await this.prisma.promotionPolicy.findMany({ orderBy: { createdAt: 'desc' } }) }); }
  @Post('promotions') @Roles('super_admin', 'operator') async createPromotion(@Body() body: any, @CurrentUser() actor: AuthenticatedUser) { const policy = await this.prisma.promotionPolicy.create({ data: { name: String(body.name), kind: body.kind === 'signup_gift' ? 'SIGNUP_GIFT' : 'FREE_WINDOW', startsAt: new Date(body.startsAt), endsAt: new Date(body.endsAt), timezone: String(body.timezone || 'Asia/Shanghai'), giftPoints: body.giftPoints ? BigInt(body.giftPoints) : null, perUserListPriceCap: body.perUserListPriceCap ? BigInt(body.perUserListPriceCap) : null, perUserRequestCap: body.perUserRequestCap ? Number(body.perUserRequestCap) : null, modelAliases: Array.isArray(body.modelAliases) ? body.modelAliases.map(String) : [], enabled: body.enabled !== false } }); await this.audit(actor, 'promotion.create', 'promotion', policy.id, { kind: policy.kind }); return json({ ok: true, policy }); }
  @Get('providers') async providers() { const rows = await this.prisma.providerChannel.findMany({ orderBy: { name: 'asc' } }); return { ok: true, providers: rows.map(({ encryptedSecret: _secret, ...item }) => ({ ...item, secretConfigured: true })) }; }
  @Post('providers') @Roles('super_admin', 'operator') async createProvider(@Body() body: any, @CurrentUser() actor: AuthenticatedUser) { const url = await validateProviderUrl(String(body.baseUrl)); const kind = ({ 'openai-compatible': 'OPENAI_COMPATIBLE', anthropic: 'ANTHROPIC', gemini: 'GEMINI' } as any)[String(body.kind)]; if (!kind || !body.secret) throw Object.assign(new Error('供应商类型或密钥无效。'), { status: 400, code: 'VALIDATION_FAILED' }); const provider = await this.prisma.providerChannel.create({ data: { name: String(body.name), kind, baseUrl: url.toString(), encryptedSecret: this.vault.encrypt(String(body.secret)), timeoutMs: Math.max(1000, Math.min(Number(body.timeoutMs || 30000), 120000)), maxConcurrency: Math.max(1, Math.min(Number(body.maxConcurrency || 20), 1000)) } }); await this.audit(actor, 'provider.create', 'provider', provider.id, { name: provider.name, baseUrl: provider.baseUrl }); return { ok: true, provider: { ...provider, encryptedSecret: undefined, secretConfigured: true } }; }
  @Get('system-ai/providers') async systemAiProviderList() { return json({ ok: true, providers: await this.systemAiProviders.list() }); }
  @Post('system-ai/providers') @Roles('super_admin', 'operator') async configureSystemAiProvider(@Body() body: any, @CurrentUser() actor: AuthenticatedUser) { return json({ ok: true, provider: await this.systemAiProviders.configure(undefined, body, actor.id) }); }
  @Patch('system-ai/providers/:providerId') @Roles('super_admin', 'operator') async updateSystemAiProvider(@Param('providerId') providerId: string, @Body() body: any, @CurrentUser() actor: AuthenticatedUser) { return json({ ok: true, provider: await this.systemAiProviders.configure(providerId, body, actor.id) }); }
  @Get('model-routes') async models() { return json({ ok: true, models: await this.prisma.logicalModel.findMany({ include: { routes: { include: { provider: { select: { id: true, name: true, kind: true, enabled: true } } } } }, orderBy: { displayName: 'asc' } }) }); }
  @Post('model-routes') @Roles('super_admin', 'operator') async upsertModel(@Body() body: any, @CurrentUser() actor: AuthenticatedUser) { const alias = String(body.alias || '').trim(); if (!/^[a-z0-9][a-z0-9._-]{1,63}$/u.test(alias)) throw Object.assign(new Error('模型别名格式无效。'), { status: 400, code: 'VALIDATION_FAILED' }); const model = await this.prisma.$transaction(async tx => { const value = await tx.logicalModel.upsert({ where: { alias }, create: { alias, displayName: String(body.displayName), description: String(body.description || ''), contextWindow: Number(body.contextWindow || 128000), maxOutputTokens: Number(body.maxOutputTokens || 4096), inputPointsPerMillion: BigInt(body.inputPointsPerMillion || 0), cachedInputPointsPerMillion: BigInt(body.cachedInputPointsPerMillion || 0), outputPointsPerMillion: BigInt(body.outputPointsPerMillion || 0) }, update: { displayName: String(body.displayName), description: String(body.description || ''), contextWindow: Number(body.contextWindow || 128000), maxOutputTokens: Number(body.maxOutputTokens || 4096), inputPointsPerMillion: BigInt(body.inputPointsPerMillion || 0), cachedInputPointsPerMillion: BigInt(body.cachedInputPointsPerMillion || 0), outputPointsPerMillion: BigInt(body.outputPointsPerMillion || 0), etagVersion: { increment: 1 } } }); if (body.providerId && body.upstreamModel) { const latest = await tx.modelRoute.aggregate({ where: { alias }, _max: { version: true } }); await tx.modelRoute.create({ data: { alias, providerId: String(body.providerId), upstreamModel: String(body.upstreamModel), version: (latest._max.version || 0) + 1, priority: Number(body.priority || 100), weight: Number(body.weight || 100), retryCount: Number(body.retryCount || 1) } }); } return value; }); await this.audit(actor, 'model.upsert', 'model', alias, { displayName: model.displayName }); return json({ ok: true, model }); }
  @Get('usage') async usage() { const requests = await this.prisma.aiRequest.findMany({ orderBy: { startedAt: 'desc' }, take: 500, select: { id: true, userId: true, modelAlias: true, operation: true, status: true, inputTokens: true, outputTokens: true, chargedPoints: true, providerCostMicros: true, errorCode: true, startedAt: true, finishedAt: true } }); return json({ ok: true, requests }); }
  @Get('audit') async auditLogs() { return { ok: true, entries: await this.prisma.adminAuditLog.findMany({ orderBy: { createdAt: 'desc' }, take: 500 }) }; }
  private async audit(actor: AuthenticatedUser, action: string, targetType: string, targetId: string, details: unknown) { await this.prisma.adminAuditLog.create({ data: { actorUserId: actor.id, action, targetType, targetId, requestId: crypto.randomUUID(), details: details as any } }); }
}

function json<T>(value: T): T { return JSON.parse(JSON.stringify(value, (_key, item) => typeof item === 'bigint' ? item.toString() : item)); }
