import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
const execFileAsync = promisify(execFile);
export type DependencyProvider = 'vcpkg' | 'conan' | 'nuget';
export interface DependencyPackage { provider: DependencyProvider; name: string; version: string; manifestPath: string }
export interface DependencyManifest { provider: DependencyProvider; filePath: string; packages: DependencyPackage[] }
export interface DependencyConflict { provider: DependencyProvider; name: string; versions: string[]; manifests: string[] }
export interface DependencySnapshot { manifests: DependencyManifest[]; conflicts: DependencyConflict[]; cache: Record<DependencyProvider, { files: number; bytes: number }> }
type Runner = (command: string, args: string[], options: { cwd: string; timeout: number; env: NodeJS.ProcessEnv }) => Promise<{ stdout: string; stderr: string }>;
export class DependencyService {
  private readonly cacheRoot: string; private readonly installRoot: string;
  constructor(private readonly workspaceRoot: string, private readonly runner: Runner = defaultRunner) { this.cacheRoot = path.join(workspaceRoot, '.lingbuilder', 'package-cache'); this.installRoot = path.join(workspaceRoot, '.lingbuilder', 'packages'); }
  async inspect(): Promise<DependencySnapshot> { const root = await fs.realpath(this.workspaceRoot); const files = await walk(root); const manifests: DependencyManifest[] = []; for (const file of files) { const parsed = await parseManifest(file, root); if (parsed) manifests.push(parsed); } return { manifests, conflicts: conflicts(manifests), cache: { vcpkg: await cacheStats(path.join(this.cacheRoot, 'vcpkg')), conan: await cacheStats(path.join(this.cacheRoot, 'conan')), nuget: await cacheStats(path.join(this.cacheRoot, 'nuget')) } }; }
  async restore(options: { manifestPath: string; offline?: boolean; triplet?: string }): Promise<{ provider: DependencyProvider; stdout: string; stderr: string; snapshot: DependencySnapshot }> { const snapshot = await this.inspect(); if (snapshot.conflicts.length) throw new Error(`检测到 ${snapshot.conflicts.length} 个依赖版本冲突，请先统一清单版本。`); const manifest = snapshot.manifests.find(item => item.filePath === normalize(options.manifestPath)); if (!manifest) throw new Error('依赖清单不存在或尚未被识别。'); const root = await fs.realpath(this.workspaceRoot); const file = path.resolve(root, manifest.filePath); const cwd = path.dirname(file); const cache = path.join(this.cacheRoot, manifest.provider); const output = path.join(this.installRoot, manifest.provider, safeKey(manifest.filePath)); await fs.mkdir(cache, { recursive: true }); await fs.mkdir(output, { recursive: true }); const env: NodeJS.ProcessEnv = { ...process.env }; let command: string; let args: string[];
    if (manifest.provider === 'vcpkg') { command = await findTool('vcpkg'); const triplet = validTriplet(options.triplet || 'x64-windows'); args = ['install', `--x-manifest-root=${cwd}`, `--x-install-root=${output}`, `--triplet=${triplet}`, `--binarysource=clear;files,${cache},${options.offline ? 'read' : 'readwrite'}`]; if (options.offline) args.push('--only-binarycaching'); }
    else if (manifest.provider === 'conan') { command = await findTool('conan'); env.CONAN_HOME = cache; args = ['install', file, `--output-folder=${output}`, options.offline ? '--build=never' : '--build=missing']; if (options.offline) args.push('--no-remote'); }
    else { command = await findTool('nuget'); args = ['restore', file, '-PackagesDirectory', output, '-NonInteractive']; if (options.offline) args.push('-Source', cache); }
    try { const result = await this.runner(command, args, { cwd, timeout: 10 * 60_000, env }); return { provider: manifest.provider, ...result, snapshot: await this.inspect() }; } catch (error: any) { throw new Error(`${manifest.provider} 恢复失败：${String(error?.stderr || error?.message || '未知错误').trim()}`); }
  }
}
async function parseManifest(file: string, root: string): Promise<DependencyManifest | null> { const name = path.basename(file).toLowerCase(); const relative = normalize(path.relative(root, file)); const text = await fs.readFile(file, 'utf8'); const packages: DependencyPackage[] = []; if (name === 'vcpkg.json') { let value: any; try { value = JSON.parse(text); } catch { throw new Error(`${relative} 不是合法 JSON。`); } for (const item of value.dependencies || []) { const dependency = typeof item === 'string' ? { name: item, version: '*' } : { name: item.name, version: item['version>='] || item.version || '*' }; if (dependency.name) packages.push({ provider: 'vcpkg', ...dependency, manifestPath: relative }); } for (const item of value.overrides || []) if (item.name) packages.push({ provider: 'vcpkg', name: item.name, version: item.version || '*', manifestPath: relative }); return { provider: 'vcpkg', filePath: relative, packages }; }
  if (name === 'conanfile.txt' || name === 'conanfile.py') { const requires = name.endsWith('.txt') ? section(text, 'requires').split(/\r?\n/u) : [...text.matchAll(/(?:self\.requires\s*\(|requires\s*=\s*\(?)[\s\[,'"]*([a-z0-9_.+-]+\/[a-z0-9_.+<>=~^*-]+)/giu)].map(item => item[1]); for (const line of requires.map(item => item.trim()).filter(item => item && !item.startsWith('#'))) { const match = line.match(/^([^/\s]+)\/([^@\s,]+)/u); if (match) packages.push({ provider: 'conan', name: match[1], version: match[2], manifestPath: relative }); } return { provider: 'conan', filePath: relative, packages }; }
  if (name === 'packages.config' || /\.(?:csproj|vcxproj)$/iu.test(name)) { const expressions = [/<package\s+[^>]*id="([^"]+)"[^>]*version="([^"]+)"/giu, /<PackageReference\s+[^>]*Include="([^"]+)"[^>]*Version="([^"]+)"/giu, /<PackageReference\s+[^>]*Include="([^"]+)"[^>]*>[\s\S]*?<Version>([^<]+)<\/Version>/giu]; for (const expression of expressions) for (const match of text.matchAll(expression)) packages.push({ provider: 'nuget', name: match[1], version: match[2], manifestPath: relative }); if (packages.length || name === 'packages.config') return { provider: 'nuget', filePath: relative, packages }; } return null; }
function conflicts(manifests: DependencyManifest[]): DependencyConflict[] { const groups = new Map<string, DependencyPackage[]>(); for (const item of manifests.flatMap(manifest => manifest.packages)) { const key = `${item.provider}:${item.name.toLowerCase()}`; groups.set(key, [...(groups.get(key) || []), item]); } const result: DependencyConflict[] = []; for (const items of groups.values()) { const versions = [...new Set(items.map(item => item.version).filter(version => version !== '*'))]; if (versions.length > 1) result.push({ provider: items[0].provider, name: items[0].name, versions, manifests: [...new Set(items.map(item => item.manifestPath))] }); } return result; }
async function walk(root: string) { const result: string[] = []; const queue = [root]; while (queue.length && result.length < 10_000) { const dir = queue.shift()!; let entries: any[]; try { entries = await fs.readdir(dir, { withFileTypes: true }); } catch { continue; } for (const entry of entries) { if (entry.isSymbolicLink()) continue; const target = path.join(dir, entry.name); if (entry.isDirectory()) { if (!['.git', 'node_modules', 'dist', 'release', 'packages', 'vcpkg_installed'].includes(entry.name) && !(entry.name === '.lingbuilder')) queue.push(target); } else if (entry.isFile() && ['vcpkg.json', 'conanfile.txt', 'conanfile.py', 'packages.config'].includes(entry.name.toLowerCase()) || entry.isFile() && /\.(?:csproj|vcxproj)$/iu.test(entry.name)) result.push(target); } } return result; }
async function cacheStats(root: string): Promise<{ files: number; bytes: number }> { let files = 0; let bytes = 0; const queue = [root]; while (queue.length) { const dir = queue.shift()!; let entries: any[]; try { entries = await fs.readdir(dir, { withFileTypes: true }); } catch { continue; } for (const entry of entries) { const target = path.join(dir, entry.name); if (entry.isDirectory()) queue.push(target); else if (entry.isFile()) { files++; bytes += (await fs.stat(target)).size; } } } return { files, bytes }; }
async function findTool(provider: DependencyProvider): Promise<string> { if (provider === 'vcpkg' && process.env.VCPKG_ROOT) { const file = path.join(process.env.VCPKG_ROOT, process.platform === 'win32' ? 'vcpkg.exe' : 'vcpkg'); try { if ((await fs.stat(file)).isFile()) return file; } catch { /* PATH */ } } return process.platform === 'win32' ? `${provider}.exe` : provider; }
async function defaultRunner(command: string, args: string[], options: { cwd: string; timeout: number; env: NodeJS.ProcessEnv }) { return await execFileAsync(command, args, { ...options, windowsHide: true, maxBuffer: 8 * 1024 * 1024, encoding: 'utf8' }) as { stdout: string; stderr: string }; }
function section(text: string, name: string): string { return text.match(new RegExp(`\\[${name}\\]([\\s\\S]*?)(?:\\n\\[|$)`, 'iu'))?.[1] || ''; }
function validTriplet(value: string) { if (!/^[a-z0-9._-]{1,100}$/iu.test(value)) throw new Error('vcpkg triplet 无效。'); return value; }
function normalize(value: string) { return value.replace(/\\/gu, '/'); } function safeKey(value: string) { return value.replace(/[^a-z0-9._-]+/giu, '_').slice(0, 120); }
